174,1
A,Sch,1,divisor_group
T,DivSch,DivSchElt,0
A,DivSch,1,variety
A,DivSchElt,21,divisor_group,ideal_factorisation,sign_split,ideal,radical_ideal,support,is_prime,selfintersection,is_nef,is_strictly_nef,is_ample,is_cartier,is_principal,principal_function,sheaf,rr_numerators,rr_denominator,rr_space,rr_space_map,base_locus,negative_components
V,DivSch,1
S,Print,Print the divisor group G (at print level l),0,2,0,0,1,0,0,0,0,298,,0,0,DivSch,,-38,-38,-38,-38,-38,-38
S,IsCoercible,"True iff D can be coerced into the divisor group G, in which case the resulting divisor is returned as a second value",0,2,0,0,0,0,0,0,0,-1,,0,0,DivSch,,36,DivSchElt,-38,-38,-38,-38
S,in,True iff the divisor D can be coerced into the divisor group G,0,2,0,0,0,0,0,0,0,DivSch,,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,DivisorGroup,The divisor group of the variety X,0,1,0,0,0,0,0,0,0,380,,DivSch,-38,-38,-38,-38,-38
S,Variety,The variety associated with the divisor group G,0,1,0,0,0,0,0,0,0,DivSch,,380,-38,-38,-38,-38,-38
S,eq,True iff the divisor groups G1 and G2 are those of the same variety,0,2,0,0,0,0,0,0,0,DivSch,,0,0,DivSch,,36,-38,-38,-38,-38,-38
S,Variety,The variety on which the divisor D lies,0,1,0,0,0,0,0,0,0,DivSchElt,,380,-38,-38,-38,-38,-38
S,Print,Print a description of the divisor D,0,2,0,0,1,0,0,0,0,298,,0,0,DivSchElt,,-38,-38,-38,-38,-38,-38
S,Parent,The divisor group containing the divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,DivSch,-38,-38,-38,-38,-38
S,Divisor,,0,2,0,0,0,0,0,0,0,427,,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,Divisor,,0,2,0,0,0,0,0,0,0,237,,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,Divisor,,0,2,0,0,0,0,0,0,0,63,,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,Divisor,,0,2,0,0,0,0,0,0,0,82,,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,Divisor,,0,2,0,0,0,0,0,0,0,380,,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,Divisor,The divisor on X defined by (the top dimensional part of) the ideal I (generated by the polynomial or rational function f or sequence of polynomials Q or scheme Y),0,2,0,0,0,0,0,0,0,64,,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,HyperplaneSectionDivisor,A hyperplane section of the variety X as a divisor on X,0,1,0,0,0,0,0,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,ZeroDivisor,The zero divisor on the variety X,0,1,0,0,0,0,0,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,SheafToDivisor,"A divisor D such that invertible sheaf S on X is isomorphic to O_X(D), effective if possible",0,1,0,0,0,0,0,0,0,ShfCoh,,DivSchElt,-38,-38,-38,-38,-38
S,CanonicalDivisor,A canonical divisor for the variety X,0,1,0,0,0,0,0,0,0,380,,DivSchElt,-38,-38,-38,-38,-38
S,FractionalPart,"The effective fractional part of the divisor D, that is, the difference D - rounddown(D)",0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,RoundDownDivisor,The integral divisor whose coefficients of prime components are the round down of those coefficients in the divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,RoundUpDivisor,The integral divisor whose coefficients of prime components are the round up of those coefficients in the divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,IdealFactorisation,The factorisation of the divisor D into ideals and multiplicities currently recorded and used for D,0,1,0,0,0,0,0,0,0,DivSchElt,,82,-38,-38,-38,-38,-38
S,ReducedFactorisation,A factorisation of the divisor D into radical (but not necessarily prime) ideals and multiplicities,0,1,0,0,0,0,0,0,0,DivSchElt,,82,-38,-38,-38,-38,-38
S,PrimeFactorisation,The factorisation of the divisor D into prime ideals and multiplicities,0,1,0,0,0,0,0,0,0,DivSchElt,,82,-38,-38,-38,-38,-38
S,SignDecomposition,"Two effective divisors A,B such that D = A - B",0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,DivSchElt,-38,-38,-38,-38
S,IsFactorisationPrime,True iff all (nontrivial) factors in the factorisation of the divisor D are prime,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,Ideal,An ideal defining the effective divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,64,-38,-38,-38,-38,-38
S,IdealOfSupport,An ideal defining the support of the effective Q-divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,64,-38,-38,-38,-38,-38
S,IsEffective,True iff the divisor D is effective,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsCanonical,True iff the divisor D is a canonical divisor,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsAnticanonical,True iff the divisor D is an anticanonical divisor,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsCanonicalWithTwist,"True iff some (integral) twist by the hyperplane section of the divisor D is a canonical divisor, in which case this integer twist is also returned",0,1,0,0,0,0,0,0,0,DivSchElt,,36,148,-38,-38,-38,-38
S,IsIntegral,True iff the divisor D is integral (possibly after combining irreducible factors),0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsDivisible,"True iff the divisor D is integral and divisible by an integer n > 1, in which case the integer n is also returned",0,1,0,0,0,0,0,0,0,DivSchElt,,36,148,-38,-38,-38,-38
S,IsPrime,True iff the divisor D is prime,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsZeroDivisor,True iff the divisor D is the zero divisor,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,Multiplicity,The multiplicity of the prime divisor E in the divisor D. Replaces the old factorisation of D with a new one containing E with the multiplicity and other terms where the maximal power of E has been divided out,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,267,-38,-38,-38,-38,-38
S,MultiplicityFast,The multiplicity of the prime divisor E in the divisor D. Requires E to be Cartier and doesn't update the ideal factorisation of D,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,267,-38,-38,-38,-38,-38
S,Multiplicities,D is a divisor on an ordinary projective variety and P is a sequence of prime divisors that should contain all prime divisors in the support of D. Returns the sequence of multiplicities of D at the p in P using a reduction to dimension 1 via taking iterated hyperplane sections,1,1,1,82,0,DivSchElt,2,0,0,0,0,0,0,0,82,,0,0,DivSchElt,,82,-38,-38,-38,-38,-38
S,CombineIdealFactorisation,Simplify the ideal factorisation of the divisor D by combining contributions from identical ideals,0,1,0,0,1,0,0,1,1,DivSchElt,,-38,-38,-38,-38,-38,-38
S,ComputeReducedFactorisation,An ideal factorisation of the divisor D into radical ideals with multiplicities,0,1,0,0,1,0,0,1,1,DivSchElt,,-38,-38,-38,-38,-38,-38
S,ComputePrimeFactorisation,A sequence containing the prime divisors that appear nontrivially in the divisor D,0,1,0,0,1,0,0,1,1,DivSchElt,,-38,-38,-38,-38,-38,-38
S,Support,The support of the divisor D as a subscheme of its associated variety,0,1,0,0,0,0,0,0,0,DivSchElt,,380,-38,-38,-38,-38,-38
S,eq,"True iff the two divisors D1 and D2 are equal, that is, they have the same prime components with the same multiplicities",0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,+,The sum D1 + D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,-,The negative -D of the divisors D,0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,-,The difference D1 - D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,*,The product n*D of the divisors D and the rational number n,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,148,,DivSchElt,-38,-38,-38,-38,-38
S,*,The product n*D of the divisors D and the rational number n,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,267,,DivSchElt,-38,-38,-38,-38,-38
S,+,The sum D1 + D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivTorElt,,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,+,The sum D1 + D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivTorElt,,DivSchElt,-38,-38,-38,-38,-38
S,-,The difference D1 - D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivTorElt,,0,0,DivSchElt,,DivSchElt,-38,-38,-38,-38,-38
S,-,The difference D1 - D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivTorElt,,DivSchElt,-38,-38,-38,-38,-38
S,IntegralMultiple,"An integral divisor E and an integer N for which N*D = E, where the given divisor D may have rational coefficients",0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,148,-38,-38,-38,-38
S,IntersectionNumber,The intersection number D1*D2 of two divisors D1 and D2,0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,267,-38,-38,-38,-38,-38
S,SelfIntersection,The self intersection D^2 of the divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,267,-38,-38,-38,-38,-38
S,IntersectionMatrix,"The symmetric intersection matrix of the divisors in the sequence Q of divisor; the i,j entry of the matrix is the intersection number Q[i]*Q[j]",0,1,0,0,0,0,0,0,0,82,,-34,-38,-38,-38,-38,-38
S,Degree,The degree of the divisor D with respect to the hyperplane section,0,1,0,0,0,0,0,0,0,DivSchElt,,267,-38,-38,-38,-38,-38
S,Degree,"The degree of the divisor D with respect to the divisor H, i.e. the intersection number D*H",0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,267,-38,-38,-38,-38,-38
S,IsNef,True iff the effective divisor D has nonnegative intersection with every curve on the underlying surface,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsNefAndBig,True iff the effective divisor D has nonnegative intersection with every curve on the underlying surface and D^2 > 0,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsCartier,True iff D is a Cartier divisor (i.e. locally principal). D must be an integral divisor on an ordinary projective variety here,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,Sheaf,The sheaf O_X(D) corresponding to the (Cartier) divisor D on a variety X. (The integral round down of D is used if D is not itself integral.),0,1,0,0,0,0,0,0,0,DivSchElt,,ShfCoh,-38,-38,-38,-38,-38
S,RiemannRochBasis,"A sequence of rational functions on the ambient space of the variety X of the divisor D (or its round down, if not integral) that form a basis of the Riemann-Roch space of D when restricted to X",0,1,0,0,0,0,0,0,0,DivSchElt,,82,-38,-38,-38,-38,-38
S,RiemannRochCoordinates,"True iff the rational function f lies in the Riemann-Roch space of the divisor D, in which case also return the coordinates of f with respect to the fixed basis of that RR space",0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,-1,,36,82,-38,-38,-38,-38
S,RiemannRochSpace,A vector space and the isomorphism from this space to the Riemann-Roch space of (ambient) function field elements for the divisor D,0,1,0,0,0,0,0,0,0,DivSchElt,,159,175,-38,-38,-38,-38
S,IsLinearSystemNonEmpty,"True iff there is at least one effective divisor linearly equivalent to the divisor D, in which case also return such an effective divisor as a second value",0,1,0,0,0,0,0,0,0,DivSchElt,,36,DivSchElt,-38,-38,-38,-38
S,IsPrincipal,"True iff the divisor D is principal, in which case a rational function f for which D = div(f) is returned as a second value",0,1,0,0,0,0,0,0,0,DivSchElt,,380,427,-38,-38,-38,-38
S,IsLinearlyEquivalent,"True iff the divisors D and E are linearly equivalent (i.e. iff D - E is principal), in which case a rational function f for which D = E + div(f) is returned as a second value",0,2,0,0,0,0,0,0,0,DivSchElt,,0,0,DivSchElt,,380,427,-38,-38,-38,-38
S,EffectiveHypersurfaceTwist,"D should be integral and defined on an ordinary projective scheme. Returns an effective divisor D1 equivalent to D+rH, where r>= 0 and H is the hyperplane divisor, and F, the homogeneous polynomial of degree r such that D1=D+(F). Just returns D,1 if D has an effective presentation. Avoids computing a relatively prime signed decomposition",0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,63,-38,-38,-38,-38
S,BaseLocus,"The base locus of the linear system |D|, that is, the reduced intersection of all effective divisors linearly equivalent to D. (Note that linear equivalence is carried out only on the integral round down; the fractional part {D} of D can be recovered separately.)",0,1,0,0,0,0,0,0,0,DivSchElt,,380,-38,-38,-38,-38,-38
S,IsBasePointFree,True iff the base locus of the linear system |D| is empty,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,IsMobile,True iff the base locus of the linear system |D| contains no components in codimension 1,0,1,0,0,0,0,0,0,0,DivSchElt,,36,-38,-38,-38,-38,-38
S,NegativePrimeDivisors,A sequence of the prime divisors on the underlying variety of the effective divisor D that have negative intersection with D,0,1,0,0,0,0,0,0,0,DivSchElt,,82,-38,-38,-38,-38,-38
S,ZariskiDecomposition,"The two divisors P, N of the Zariski decomposition D = P + N of the divisor D (on a surface) into nef Q-divisor P and Q-divisor N which has negative definite support",0,1,0,0,0,0,0,0,0,DivSchElt,,DivSchElt,DivSchElt,-38,-38,-38,-38
