freeze;
 
////////////////////////////////////////////////////////////////////////
//                                                                    //
//                       Divisors of Number Fields                    //
//                              David Kohel                           //
//                         Created November 2001                      //
//                                                                    //
////////////////////////////////////////////////////////////////////////

intrinsic Divisor(x::FldNumElt) -> DivNumElt
{The fractional ideal generated by x as a divisor.}
    // N.B. The computation of the maximal order is invoked.
    K := Parent(x);
    O := MaximalOrder(K);
    return Divisor(O*x);
end intrinsic;

