174,1
S,CoefficientRing,The base field of K,0,1,0,0,0,0,0,0,0,-9,,-44,-38,-38,-38,-38,-38
S,IsNumberField,Returns true iff K is a number field,0,1,0,0,0,0,0,0,0,-1,,36,-38,-38,-38,-38,-38
S,IsAlgebraicField,Returns true iff K is an algebraic field,0,1,0,0,0,0,0,0,0,-1,,36,-38,-38,-38,-38,-38
S,AbsoluteBasis,A Z-basis for O,0,1,0,0,0,0,0,0,0,215,,82,-38,-38,-38,-38,-38
S,IsSquarefree,True iff the ideal I has no repeated factors,0,1,0,0,0,0,0,0,0,217,,36,-38,-38,-38,-38,-38
S,DecompositionGroup,Computes the decomposition group of p,0,1,0,0,0,0,0,0,0,217,,224,-38,-38,-38,-38,-38
S,RamificationGroup,Computes the i-th ramification group of p (lower index),0,2,0,0,0,0,0,0,0,148,,0,0,217,,224,-38,-38,-38,-38,-38
S,RamificationGroup,Computes the ramification group of p,0,1,0,0,0,0,0,0,0,217,,224,-38,-38,-38,-38,-38
S,InertiaGroup,Computes the inertia group of p,0,1,0,0,0,0,0,0,0,217,,224,-38,-38,-38,-38,-38
S,FixedField,"For a subgroup U of the CyclotomicAutomorphismGroup of K, compute the field fixed by U",0,2,0,0,0,0,0,0,0,107,,0,0,51,,27,175,-38,-38,-38,-38
S,FixedField,"For a subgroup U of the AutomorphismGroup of K, compute the field fixed by U",0,2,0,0,0,0,0,0,0,224,,0,0,-9,,27,175,-38,-38,-38,-38
S,FixedGroup,"For elements L of K, compute the subgroup U of the automorphism group of K that fixes all elements of L",1,1,1,82,0,-10,2,0,0,0,0,0,0,0,82,,0,0,-9,,224,-38,-38,-38,-38,-38
S,FixedGroup,"For an element a of K, compute the subgroup U of the automorphism group of K that fixes it",0,2,0,0,0,0,0,0,0,-10,,0,0,-9,,224,-38,-38,-38,-38,-38
S,FixedGroup,"For a subfield k of K, compute the subgroup U of the automorphism group of K that fixes it",0,2,0,0,0,0,0,0,0,-9,,0,0,-9,,224,-38,-38,-38,-38,-38
S,FixedGroup,"For a subfield k of K, compute the subgroup U of the automorphism group of K that fixes it",0,2,0,0,0,0,0,0,0,262,,0,0,-9,,224,-38,-38,-38,-38,-38
S,DecompositionField,Computes the decomposition field of p,0,1,0,0,0,0,0,0,0,217,,27,175,-38,-38,-38,-38
S,RamificationField,Computes the i-th ramification field of p (lower index),0,2,0,0,0,0,0,0,0,148,,0,0,217,,27,175,-38,-38,-38,-38
S,RamificationField,Computes the ramification field of p,0,1,0,0,0,0,0,0,0,217,,27,175,-38,-38,-38,-38
S,InertiaField,Computes the inertia field of p,0,1,0,0,0,0,0,0,0,217,,27,175,-38,-38,-38,-38
S,Numerator,"Returns the numerator of x, ie. x * Denominator(x)",0,1,0,0,0,0,0,0,0,-10,,-10,-38,-38,-38,-38,-38
S,IsCyclic,Tests if the field is normal with cyclic automorphism group,0,1,0,0,0,0,0,0,0,-9,,36,-38,-38,-38,-38,-38
S,IsNormal,True iff K is normal,1,0,1,51,0,262,1,0,0,0,0,0,0,0,51,,36,-38,-38,-38,-38,-38
S,IsAbelian,True iff K is normal with abelian Galois group,1,0,1,51,0,262,1,0,0,0,0,0,0,0,51,,36,-38,-38,-38,-38,-38
S,Content,The ideal generated by all entries in X,0,1,0,0,0,0,0,0,0,-34,,324,-38,-38,-38,-38,-38
S,Decomposition,"For a map R between two number fields, and a place P of the domain, compute the composition in the codomain",1,0,2,175,0,-9,0,-9,2,0,0,0,0,0,0,0,332,,0,0,175,,82,-38,-38,-38,-38,-38
S,Decomposition,"For a map R between two number fields, and a place P of the domain, compute the composition in the codomain",1,0,2,175,0,262,0,-9,2,0,0,0,0,0,0,0,148,,0,0,175,,82,-38,-38,-38,-38,-38
S,Representation,"Represent x (an element in a number field K) as an O-linear combination of the given elts, where O is Integers(K) by default",1,1,1,82,0,-45,2,0,0,0,0,0,0,0,82,,0,0,-45,,82,-38,-38,-38,-38,-38
S,Orbit,"The orbit of A under G, where the group G acts via the map M (where M may be a map of type Map or a function of type UserProgram)",0,3,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-27,,83,-38,-38,-38,-38,-38
S,OrbitClosure,"The smallest G-invariant set containing A, where the group G acts via the map M (where M may be a map of type Map or a function of type UserProgram)",0,3,0,0,0,0,0,0,0,83,,0,0,-1,,0,0,-27,,83,-38,-38,-38,-38,-38
S,MyGCD,,1,0,1,82,0,-10,1,0,0,0,0,0,0,0,82,,217,-38,-38,-38,-38,-38
S,CoprimeBasisInsert,Inserts an additional ideal into a coprime basis,0,2,0,0,1,0,0,0,0,324,,1,1,82,,-38,-38,-38,-38,-38,-38
S,CoprimeBasis,"A sequence of ideals that generate multiplicatively the same ideals as L and that is closed under Gcd. If GaloisStable is given, it is also closed under operation of the automorphisms",1,0,1,82,0,324,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,Support,"The support of L, ie. the set of (prime) ideal supporting elements in L",1,0,1,82,0,324,1,0,0,0,0,0,0,0,82,,83,-38,-38,-38,-38,-38
S,Support,The minimal set of prime ideals that are neccessary to factor all elements in L completely,1,0,1,82,0,-10,1,0,0,0,0,0,0,0,82,,83,-38,-38,-38,-38,-38
S,&*,The Product of the ideals in L,1,0,1,83,0,324,1,0,0,0,0,0,0,0,83,,324,-38,-38,-38,-38,-38
S,&*,The Product of the ideals in L,1,0,1,82,0,324,1,0,0,0,0,0,0,0,82,,324,-38,-38,-38,-38,-38
S,&meet,The intersection (LCM) of the ideals in L,1,0,1,83,0,324,1,0,0,0,0,0,0,0,83,,324,-38,-38,-38,-38,-38
S,&meet,The intersection (LCM) of the ideals in L,1,0,1,82,0,324,1,0,0,0,0,0,0,0,82,,324,-38,-38,-38,-38,-38
S,IsOne,Return true iff I is the trivial ideal generated by 1,0,1,0,0,0,0,0,0,0,217,,36,-38,-38,-38,-38,-38
S,IsOne,Return true iff I is the trivial ideal generated by 1,0,1,0,0,0,0,0,0,0,324,,36,-38,-38,-38,-38,-38
S,div,Quotient of I by J; J must divide exactly,0,2,0,0,0,0,0,0,0,217,,0,0,217,,217,-38,-38,-38,-38,-38
S,div,The quotient of I by J,0,2,0,0,0,0,0,0,0,324,,0,0,324,,324,-38,-38,-38,-38,-38
S,InternalMinPoly,"Called from MinimalPolynomial(a, R) in the general case",0,2,0,0,0,0,0,0,0,-9,,0,0,-10,,312,-38,-38,-38,-38,-38
S,InternalMinPoly,"Called from MinimalPolynomial(a, R) in the general case",0,2,0,0,0,0,0,0,0,215,,0,0,-10,,312,-38,-38,-38,-38,-38
S,InternalCharPoly,"Called from MinimalPolynomial(a, R) in the general case",0,2,0,0,0,0,0,0,0,-9,,0,0,-10,,312,-38,-38,-38,-38,-38
S,InternalCharPoly,"Called from MinimalPolynomial(a, R) in the general case",0,2,0,0,0,0,0,0,0,215,,0,0,-10,,312,-38,-38,-38,-38,-38
S,RootOfUnity,The primitive n-th root of unity in the field K,0,2,0,0,0,0,0,0,0,-9,,0,0,148,,-10,-38,-38,-38,-38,-38
S,Automorphisms,The list of automorphisms of K,0,1,0,0,0,0,0,0,0,-9,,82,-38,-38,-38,-38,-38
S,Radical,The radical of I (where I is an ideal in the ring of integers of a number field),0,1,0,0,0,0,0,0,0,217,,217,-38,-38,-38,-38,-38
S,PrimesUpTo,A sequence containing the prime ideals in the field K with norm less than or equal to B,0,2,0,0,0,0,0,0,0,262,,0,0,148,,82,-38,-38,-38,-38,-38
S,PrimesUpTo,A sequence containing the prime ideals in the field K with norm less than or equal to B,0,2,0,0,0,0,0,0,0,-9,,0,0,148,,82,-38,-38,-38,-38,-38
S,RelationMatrix,"Given a sequence of primes S, this calculates the S-unit group, and returns a matrix containing the valuations (one column per element) and the corresponding elements",1,0,1,82,0,217,1,0,0,0,0,0,0,0,82,,-34,82,-38,-38,-38,-38
S,RelationMatrix,"Returns RelationMatrix(FactorBasis(O, B))",0,2,0,0,0,0,0,0,0,148,,0,0,215,,-34,82,-38,-38,-38,-38
S,RelationMatrix,"Returns RelationMatrix(FactorBasis(RingOfIntegers(K), B))",0,2,0,0,0,0,0,0,0,148,,0,0,27,,-34,82,-38,-38,-38,-38
S,Components,The simple fields defined by the defining polynomials of K,0,1,0,0,0,0,0,0,0,27,,82,-38,-38,-38,-38,-38
S,Components,The fields of fractions of simple orders defined by the defining polynomials of F,0,1,0,0,0,0,0,0,0,322,,82,-38,-38,-38,-38,-38
S,Components,The simple orders defined by the defining polynomials of O,0,1,0,0,0,0,0,0,0,215,,82,-38,-38,-38,-38,-38
S,PrincipalMultiple,"Given an ideal I, find J such that IJ is principal and gcd(J,IM)=1",0,2,0,0,0,0,0,0,0,217,,0,0,217,,217,-38,-38,-38,-38,-38
