174,1
S,Matrix,The matrix whose rows are given by the elements of Q,1,0,1,82,0,69,1,0,0,0,0,0,0,0,82,,-34,-38,-38,-38,-38,-38
S,Vector,The vector (dense matrix representation) corresponding to v,0,1,0,0,0,0,0,0,0,69,,-34,-38,-38,-38,-38,-38
S,UnitVector,"Return Ambient(M)![0, ..., 0, 1, 0, ..., 0] where the 1 is in the i-th position",0,2,0,0,0,0,0,0,0,148,,0,0,67,,69,-38,-38,-38,-38,-38
S,IsHomogeneous,Return whether all the polynomials in set/sequence S are homogeneous w.r.t the grading of their parent,1,0,1,-52,0,69,1,0,0,0,0,0,0,0,-52,,36,-38,-38,-38,-38,-38
S,MinimalBasis,A minimal basis of the submodule generated by the set/sequence S,1,0,1,-52,0,69,1,0,0,0,0,0,0,0,-52,,82,-38,-38,-38,-38,-38
