174,1
S,NilpotentQuotient,Return a structure constant Lie algebra which is isomorphic to the nilpotent quotient of class d of the free Lie algebra modulo the relations in R,1,0,1,-52,0,353,2,0,0,0,0,0,0,0,-1,,0,0,-52,,15,82,82,175,-38,-38
S,LieAlgebra,Return a structure constant Lie algebra which is isomorphic to the free Lie algebra modulo the relations in R,1,0,1,-52,0,353,1,0,0,0,0,0,0,0,-52,,15,82,82,41,-38,-38
S,InternalQuoAlgFPLie,"Construct the lie algebra L/I, where I is the ideal generated by the elements of R",1,1,1,-52,0,353,2,0,0,0,0,0,0,0,-52,,0,0,354,,15,175,-38,-38,-38,-38
S,InternalHomAlgFPLie,"Construct a hom from L to M, where L.i is mapped to Q[i]. Q must be a sequence of elements of M of length Rank(L)",0,3,0,0,0,0,0,0,0,82,,0,0,-1,,0,0,354,,175,-38,-38,-38,-38,-38
