174,1
A,AlgLie,4,IsRestrictable,PImages,PMap,GradingList
A,Grp,1,JenningsLieAlgebra
S,IsRestrictable,True iff L is a restrictable Lie algebra,0,1,0,0,0,0,0,0,0,15,,36,175,-38,-38,-38,-38
S,IsRestricted,True iff L is a restrictable Lie algebra,0,1,0,0,0,0,0,0,0,15,,36,175,-38,-38,-38,-38
S,IspLieAlgebra,True iff L is a restrictable Lie algebra,0,1,0,0,0,0,0,0,0,15,,36,175,-38,-38,-38,-38
S,IsRestrictedLieAlgebra,True iff L is a restrictable Lie algebra,0,1,0,0,0,0,0,0,0,15,,36,175,-38,-38,-38,-38
S,RestrictionMap,The restriction map of L,0,1,0,0,0,0,0,0,0,15,,175,-38,-38,-38,-38,-38
S,pMap,The restriction map of L,0,1,0,0,0,0,0,0,0,15,,175,-38,-38,-38,-38,-38
S,RestrictedSubalgebra,The restricted subalgebra generated by the input,1,0,1,83,0,16,1,0,0,0,0,0,0,0,83,,15,-38,-38,-38,-38,-38
S,pSubalgebra,The restricted subalgebra generated by the input,1,0,1,83,0,16,1,0,0,0,0,0,0,0,83,,15,-38,-38,-38,-38,-38
S,pClosure,"The restricted subalgebra of the first input, generated by the second",0,2,0,0,0,0,0,0,0,15,,0,0,15,,36,-38,-38,-38,-38,-38
S,IsRestrictedSubalgebra,True iff L is closed under the p-map of M and the p-map of L is a restriction,0,2,0,0,0,0,0,0,0,15,,0,0,15,,36,-38,-38,-38,-38,-38
S,IspSubalgebra,True iff L is closed under the p-map of M and the p-map of L is a restriction,0,2,0,0,0,0,0,0,0,15,,0,0,15,,36,-38,-38,-38,-38,-38
S,pQuotient,"The quotient of L by the p-closure of M, with the inherited p-map",0,2,0,0,0,0,0,0,0,15,,0,0,15,,15,-38,-38,-38,-38,-38
S,JenningsLieAlgebra,for a p-group G this returns the Lie algebra that is the direct sum of subsequent quotients of the Jennings series of G,0,1,0,0,0,0,0,0,0,-27,,15,-38,-38,-38,-38,-38
