174,1
T,TorLat,TorLatElt,0
A,TorLat,15,id,dim,name,dual,emb_maps,proj_maps,summands,sublattice,suplattice,coverlattice,zero,zero_cone,zero_fan,empty_polytope,lattice_cache
S,CacheClearToricLattice,Clear the internal toric lattice cache,0,0,0,0,1,0,0,-38,-38,-38,-38,-38,-38
S,PrintNamed,The toric lattice description,0,3,0,0,1,0,0,0,0,298,,0,0,298,,0,0,TorLat,,-38,-38,-38,-38,-38,-38
S,Hash,The hash value for the toric lattice,0,1,0,0,0,0,0,0,0,TorLat,,148,-38,-38,-38,-38,-38
S,in,Is S an element of the lattice L,0,2,0,0,0,0,0,0,0,TorLat,,0,0,-1,,36,-38,-38,-38,-38,-38
S,IsCoercible,Can the object be coerced into the lattice L,0,2,0,0,0,0,0,0,0,-1,,0,0,TorLat,,36,TorLatElt,-38,-38,-38,-38
S,SubConstr,Sub constructor for lattices,0,2,0,0,0,0,0,0,0,-1,,0,0,TorLat,,TorLat,175,-38,-38,-38,-38
S,eq,True iff the two toric lattices equivalent,0,2,0,0,0,0,0,0,0,TorLat,,0,0,TorLat,,36,-38,-38,-38,-38,-38
S,.,The i-th element of the standard basis of the toric lattice L,0,2,0,0,0,0,0,0,0,148,,0,0,TorLat,,TorLatElt,-38,-38,-38,-38,-38
S,ToricLattice,A toric lattice of dimension n,0,1,0,0,0,0,0,0,0,148,,TorLat,-38,-38,-38,-38,-38
S,ToricLattice,"The toric sublattice generated by the sequence S of sequences of integers, together with the embedding map to the toric lattice Z^n",1,0,1,82,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorLat,175,-38,-38,-38,-38
S,ScalarLattice,The one dimensional toric lattice of scalars,0,0,0,0,0,0,0,TorLat,-38,-38,-38,-38,-38
S,+,The direct sum of L1 and L2,0,2,0,0,0,0,0,0,0,TorLat,,0,0,TorLat,,TorLat,-38,-38,-38,-38,-38
S,DirectSum,"The direct sum of L1 and L2, together with the following natural maps: the embedding of L1, the embedding of L2, the projection onto L1, and the projection onto L2",0,2,0,0,0,0,0,0,0,TorLat,,0,0,TorLat,,TorLat,175,175,175,175,-38
S,DirectSum,"The direct sum of the lattices in S, together with the following sequences of natural maps: the embeddings of lattices in S, and the projections onto lattices in S",1,0,1,82,0,TorLat,1,0,0,0,0,0,0,0,82,,TorLat,82,82,-38,-38,-38
S,^,"The direct sum of n copies of the lattice L, together with the following sequences of natural maps: the embeddings of the components, the projections onto the components",0,2,0,0,0,0,0,0,0,148,,0,0,TorLat,,TorLat,82,82,-38,-38,-38
S,Sublattice,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorLat,175,-38,-38,-38,-38
S,Sublattice,"The toric sublattice generated by the sequence of integral vectors S, together with the embedding map",1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorLat,175,-38,-38,-38,-38
S,Quotient,"The quotient of the toric lattice by the sublattice generated by the primitive vector of v, together with the quotient map",0,1,0,0,0,0,0,0,0,TorLatElt,,TorLat,175,-38,-38,-38,-38
S,Quotient,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorLat,175,-38,-38,-38,-38
S,Quotient,"The quotient of the ambient lattice by the linear subspace spanned by the sequence of vectors S, together with the quotient map",1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorLat,175,-38,-38,-38,-38
S,AddVectorToLattice,,0,1,0,0,0,0,0,0,0,TorLatElt,,TorLat,175,-38,-38,-38,-38
S,AddVectorToLattice,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorLat,175,-38,-38,-38,-38
S,AddVectorToLattice,"The lattice generated by the addition of the vector v, or by the vectors in the sequence S, together with the embedding map into the new lattice",1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorLat,175,-38,-38,-38,-38
S,Dual,The toric lattice dual to L,0,1,0,0,0,0,0,0,0,TorLat,,TorLat,-38,-38,-38,-38,-38
S,IsInDual,True iff the point is in the dual of the lattice L,0,2,0,0,0,0,0,0,0,TorLat,,0,0,TorLatElt,,36,-38,-38,-38,-38,-38
S,Dimension,The dimension of the toric lattice L,0,1,0,0,0,0,0,0,0,TorLat,,148,-38,-38,-38,-38,-38
S,IsDirectSum,True iff the lattice was constructed as a direct sum,0,1,0,0,0,0,0,0,0,TorLat,,36,-38,-38,-38,-38,-38
S,Summands,"If the lattice L was constructed as a direct sum, gives the summands, together with the following sequences of natural maps: the embeddings of lattices in L, and the projections onto lattices in L",0,1,0,0,0,0,0,0,0,TorLat,,82,82,82,-38,-38,-38
S,IsSublattice,True iff the lattice was constructed as a sublattice,0,1,0,0,0,0,0,0,0,TorLat,,36,-38,-38,-38,-38,-38
S,Superlattice,"If the lattice L was constructed as a sublattice of S, gives S together with the embedding map",0,1,0,0,0,0,0,0,0,TorLat,,TorLat,175,-38,-38,-38,-38
S,IsSuperlattice,True iff the lattice was constructed by the addition of a vector,0,1,0,0,0,0,0,0,0,TorLat,,36,-38,-38,-38,-38,-38
S,Sublattice,"If the lattice L was constructed by the addition of a vector to the sublattice S, gives S together with the embedding map",0,1,0,0,0,0,0,0,0,TorLat,,TorLat,175,-38,-38,-38,-38
S,IsQuotient,True iff the lattice was constructed by taking a quotient,0,1,0,0,0,0,0,0,0,TorLat,,36,-38,-38,-38,-38,-38
S,Coverlattice,"If the lattice L was constructed by taking a quotient of the lattice S, gives S together with the projection map",0,1,0,0,0,0,0,0,0,TorLat,,TorLat,175,-38,-38,-38,-38
S,AreGenerators,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,36,-38,-38,-38,-38,-38
S,AreGenerators,True iff the vectors of S generate the toric lattice L. The vectors must be integer,1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,36,-38,-38,-38,-38,-38
S,Basis,The integral standard basis of the lattice L,0,1,0,0,0,0,0,0,0,TorLat,,82,-38,-38,-38,-38,-38
S,Basis,The i-th integral standard basis vector of the lattice L,0,2,0,0,0,0,0,0,0,148,,0,0,TorLat,,TorLatElt,-38,-38,-38,-38,-38
S,Zero,The zero vector of the lattice L,0,1,0,0,0,0,0,0,0,TorLat,,TorLatElt,-38,-38,-38,-38,-38
S,Representative,A representative element of the toric lattice L,0,1,0,0,0,0,0,0,0,TorLat,,TorLatElt,-38,-38,-38,-38,-38
S,PrintName,The print name of the lattice L,0,1,0,0,0,0,0,0,0,TorLat,,298,-38,-38,-38,-38,-38
S,DualPrintName,The print name of the dual lattice to L,0,1,0,0,0,0,0,0,0,TorLat,,298,-38,-38,-38,-38,-38
