174,1
A,GrpAutCrv,11,Fgens,Agens,id,G,Gelts,Aelts,invs,ff_rat,rat_ff,eqn_deg_bnd,no_gcd
A,GrpAutCrvElt,2,ff_map,index
S,InternalGrpAutCrvCoerce,Internal function,0,2,0,0,0,0,0,0,0,376,,0,0,448,,449,-38,-38,-38,-38,-38
S,InternalGrpAutCrvCoerce,Internal function,0,2,0,0,0,0,0,0,0,449,,0,0,448,,449,-38,-38,-38,-38,-38
S,InternalGrpAutCrvCoerce,Internal function,0,2,0,0,0,0,0,0,0,148,,0,0,448,,449,-38,-38,-38,-38,-38
S,Automorphisms,Returns a sequence of at most Bound (default: infinity) automorphisms of a curve,0,1,0,0,0,0,0,0,0,371,,82,-38,-38,-38,-38,-38
S,IsIsomorphic,"Tests if curves C and D are isomorphic. If so, also returns a scheme isomorphism between them",0,2,0,0,0,0,0,0,0,371,,0,0,371,,36,175,-38,-38,-38,-38
S,Isomorphisms,Returns a sequence of at most Bound (default: infinity) isomorphisms between two curves,0,2,0,0,0,0,0,0,0,371,,0,0,371,,82,-38,-38,-38,-38,-38
S,AutomorphismGroup,Returns the full automorphism group of curve C,0,1,0,0,0,0,0,0,0,371,,448,-38,-38,-38,-38,-38
S,AutomorphismGroup,Returns the automorphism group of curve C generated by the sequence of scheme automorphisms in phis,1,1,1,82,0,374,2,0,0,0,0,0,0,0,82,,0,0,371,,448,-38,-38,-38,-38,-38
S,AutomorphismGroup,Returns the (sub-)automorphism group of curve C generated by a sequence gs of elements in an automorphism group of C,1,1,1,82,0,449,2,0,0,0,0,0,0,0,82,,0,0,371,,448,-38,-38,-38,-38,-38
S,in,Returns whether phi is equal to an automorphism in CG,0,2,0,0,0,0,0,0,0,448,,0,0,376,,36,-38,-38,-38,-38,-38
S,in,Returns whether g is equal to an automorphism in CG,0,2,0,0,0,0,0,0,0,448,,0,0,449,,36,-38,-38,-38,-38,-38
S,.,Returns the ith generator of the curve automorphism group,0,2,0,0,0,0,0,0,0,148,,0,0,448,,449,-38,-38,-38,-38,-38
S,subset,Returns whether CH is a subset of CG,0,2,0,0,0,0,0,0,0,448,,0,0,448,,36,-38,-38,-38,-38,-38
S,Curve,Returns the curve on which the automorphism group acts,0,1,0,0,0,0,0,0,0,448,,371,-38,-38,-38,-38,-38
S,Id,Returns the identity element of CG,0,1,0,0,0,0,0,0,0,448,,449,-38,-38,-38,-38,-38
S,Order,Order of the curve automorphism group,0,1,0,0,0,0,0,0,0,448,,148,-38,-38,-38,-38,-38
S,#,Order of the curve automorphism group,0,1,0,0,0,0,0,0,0,448,,148,-38,-38,-38,-38,-38
S,FactoredOrder,Factored order of the curve automorphism group,0,1,0,0,0,0,0,0,0,448,,148,-38,-38,-38,-38,-38
S,NumberOfGenerators,The number of group generators of CG,0,1,0,0,0,0,0,0,0,448,,148,-38,-38,-38,-38,-38
S,Generators,The group generators of CG,0,1,0,0,0,0,0,0,0,448,,82,-38,-38,-38,-38,-38
S,PermutationGroup,The permutation group providing the basic group representation of CG,0,1,0,0,0,0,0,0,0,448,,224,-38,-38,-38,-38,-38
S,PermutationRepresentation,"The permutation group G and isomorphism CG->G, providing the basic group representation of CG",0,1,0,0,0,0,0,0,0,448,,224,175,-38,-38,-38,-38
S,Order,Order of the curve automorphism,0,1,0,0,0,0,0,0,0,449,,148,-38,-38,-38,-38,-38
S,Inverse,Inverse of a curve automorphism,0,1,0,0,0,0,0,0,0,449,,449,-38,-38,-38,-38,-38
S,eq,Returns whether the curve automorphisms given by the two elements are equal,0,2,0,0,0,0,0,0,0,449,,0,0,449,,36,-38,-38,-38,-38,-38
S,ne,Returns whether the curve automorphisms given by the two elements are unequal,0,2,0,0,0,0,0,0,0,449,,0,0,449,,36,-38,-38,-38,-38,-38
S,*,The composition of the two curve automorphisms,0,2,0,0,0,0,0,0,0,449,,0,0,449,,449,-38,-38,-38,-38,-38
S,^,nth power of curve automorphism f,0,2,0,0,0,0,0,0,0,148,,0,0,449,,449,-38,-38,-38,-38,-38
S,SchemeMap,Returns f as a plain MapAutSch,0,1,0,0,0,0,0,0,0,449,,374,-38,-38,-38,-38,-38
S,@,The image of point pt under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,377,,377,-38,-38,-38,-38,-38
S,@,The image of place pl under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,232,,232,-38,-38,-38,-38,-38
S,@@,The pullback of place pl under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,232,,232,-38,-38,-38,-38,-38
S,@,The image of divisor D under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,61,,61,-38,-38,-38,-38,-38
S,@@,The pullback of divisor D under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,61,,61,-38,-38,-38,-38,-38
S,@@,The pullback of function f under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,427,,427,-38,-38,-38,-38,-38
S,@,The pushforward of function f under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,427,,427,-38,-38,-38,-38,-38
S,@@,The pullback of differential df under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,420,,420,-38,-38,-38,-38,-38
S,@,The pushforward of differential df under curve automorphism g,0,2,0,0,0,0,0,0,0,449,,0,0,420,,420,-38,-38,-38,-38,-38
S,Trace,The trace of f under the action of G,0,2,0,0,0,0,0,0,0,448,,0,0,5,,5,-38,-38,-38,-38,-38
S,Norm,The norm of f under the action of G,0,2,0,0,0,0,0,0,0,448,,0,0,5,,5,-38,-38,-38,-38,-38
S,Trace,The trace of f under the action of G,0,2,0,0,0,0,0,0,0,448,,0,0,427,,427,-38,-38,-38,-38,-38
S,Norm,The norm of f under the action of G,0,2,0,0,0,0,0,0,0,448,,0,0,427,,427,-38,-38,-38,-38,-38
S,MatrixRepresentation,"The representation (by pullback) of automorphism group G of the curve C on a basis B of global differentials of C. Genus(C) must be at least 2. Return values are the (finite) matrix group image, the map from G to this image, and the basis of differentials as a sequence",0,1,0,0,0,0,0,0,0,448,,178,175,82,-38,-38,-38
