freeze;

files := [
    "alt_prep",
    "alt_mrep",
    "clas_prep",
    "clas_mrep",
    "exc_mrep",
    "exc_prep",
    "lin_prep",
    "lin_mrep",
    "msc_prep",
    "msc_mrep",
    "b_mrep",
    "co1_prep",
    "co1_mrep",
    "co2_prep",
    "co2_mrep",
    "co3_prep",
    "co3_mrep",
    "f22_prep",
    "f22_mrep",
    "f23_prep",
    "f23_mrep",
    "f24_prep",
    "f24_mrep",
    "hn_prep",
    "hn_mrep",
    "hs_prep",
    "hs_mrep",
    "he_prep",
    "he_mrep",
    "j1_prep",
    "j1_mrep",
    "j2_prep",
    "j2_mrep",
    "j3_prep",
    "j3_mrep",
    "j4_mrep",
    "ly_mrep",
    "m11_prep",
    "m11_mrep",
    "m12_prep",
    "m12_mrep",
    "m22_prep",
    "m22_mrep",
    "m23_prep",
    "m23_mrep",
    "m24_prep",
    "m24_mrep",
    "mcl_prep",
    "mcl_mrep",
    "on_prep",
    "on_mrep",
    "ru_prep",
    "ru_mrep",
    "suz_prep",
    "suz_mrep",
    "th_mrep",
    "alt_max",
    "clas_max",
    "exc_max",
    "lin_max",
    "spo_max" ];

ATLASFileName := function (n)
    return files[n + 1];
end function;
