174,1
A,AlgAssVOrd,4,IsMaximal,Discriminant,FactoredDiscriminant,TraceZeroInternalData
A,AlgQuat,1,FactoredDiscriminant
S,/,The quotient of x by y in their ambient algebra,0,2,0,0,0,0,0,0,0,436,,0,0,436,,-61,-38,-38,-38,-38,-38
S,div,The quotient of x by y; y must divide x exactly,0,2,0,0,0,0,0,0,0,436,,0,0,436,,436,-38,-38,-38,-38,-38
S,IsScalar,Returns true (and R ! a) iff a belongs to the base ring R,0,1,0,0,0,0,0,0,0,436,,36,-45,-38,-38,-38,-38
S,IsIntegral,Returns true iff a is integral,0,1,0,0,0,0,0,0,0,18,,36,-38,-38,-38,-38,-38
S,TraceZeroSubspace,"A basis over Z or F_q[X] for the trace zero submodule of O, where O is an order in a quaternion algebra, returned as a sequence of elements of O",0,1,0,0,0,0,0,0,0,19,,82,-38,-38,-38,-38,-38
S,TraceZeroSubspace,Returns the trace zero subspace of O as a pseudobasis,1,0,1,435,0,215,1,0,0,0,0,0,0,0,435,,82,-38,-38,-38,-38,-38
S,Random,Returns a random (small coefficient) element of O,0,1,0,0,0,0,0,0,0,435,,436,-38,-38,-38,-38,-38
S,Order,Returns some order containing alpha,1,0,1,18,0,-9,1,0,0,0,0,0,0,0,18,,435,-38,-38,-38,-38,-38
S,Order,"Given a sequence S of elements of A, returns the order generated by S as a module (over the maximal order of the underlying number field)",1,0,1,82,1,-61,0,-9,1,0,0,0,0,0,0,0,82,,435,-38,-38,-38,-38,-38
S,Order,"Given a sequence S of elements of A, returns the order generated by S as a module (over the maximal order of the underlying function field)",1,1,1,82,1,-61,0,-3,2,0,0,0,0,0,0,0,82,,0,0,8,,435,-38,-38,-38,-38,-38
S,Order,Returns the order which has pseudobasis given by the basis elements S and the coefficient ideals I,2,0,1,82,1,-61,0,-3,1,1,82,0,10,2,0,0,0,0,0,0,0,82,,0,0,82,,435,-38,-38,-38,-38,-38
S,Order,Returns the order which has pseudobasis given by the basis elements S and the coefficient ideals I,2,0,1,82,1,-61,0,-9,1,1,82,0,324,2,0,0,0,0,0,0,0,82,,0,0,82,,435,-38,-38,-38,-38,-38
S,Adjoin,Returns the order generated by a and O,1,0,1,435,0,215,2,0,0,0,0,0,0,0,-61,,0,0,435,,435,-38,-38,-38,-38,-38
S,Adjoin,Returns the order obtained by adjoining the set a*I to O,1,0,1,435,0,215,3,0,0,0,0,0,0,0,324,,0,0,-61,,0,0,435,,435,-38,-38,-38,-38,-38
S,+,"Computes the sum O1+O2, the smallest order containing both O1 and O2",2,0,1,435,0,215,1,1,435,0,215,2,0,0,0,0,0,0,0,435,,0,0,435,,435,-38,-38,-38,-38,-38
S,meet,Computes the intersection of two orders,2,0,1,435,0,215,1,1,435,0,215,2,0,0,0,0,0,0,0,435,,0,0,435,,435,-38,-38,-38,-38,-38
S,Discriminant,"The discriminant of the order O. For quaternion algebras, this returns the reduced discriminant. For all other types of algebras, it returns the generic discriminant, i.e. the determinant of the trace form (with generic trace)",1,0,1,435,0,215,1,0,0,0,0,0,0,0,435,,217,-38,-38,-38,-38,-38
S,Discriminant,"The discriminant of the order O. For quaternion algebras, this returns the reduced discriminant. For all other types of algebras, it returns the generic discriminant, i.e. the determinant of the trace form (with generic trace)",1,0,1,435,0,8,1,0,0,0,0,0,0,0,435,,217,-38,-38,-38,-38,-38
S,Discriminant,"The discriminant of the order O. For quaternion algebras, this returns the reduced discriminant. For all other types of algebras, it returns the generic discriminant, i.e. the determinant of the trace form (with generic trace)",0,1,0,0,0,0,0,0,0,435,,148,-38,-38,-38,-38,-38
S,FactoredDiscriminant,The factorization of Discriminant(O),0,1,0,0,0,0,0,0,0,435,,82,-38,-38,-38,-38,-38
S,Discriminant,Returns the ideal of finite places and the sequence of real places where A is ramified,1,0,1,17,0,-9,1,0,0,0,0,0,0,0,17,,217,82,-38,-38,-38,-38
S,Discriminant,The reduced discriminant,1,0,1,17,0,239,1,0,0,0,0,0,0,0,17,,312,-38,-38,-38,-38,-38
S,RamifiedPrimes,The ramified (normalized) irreducible polynomials of the quaternion algebra A,1,0,1,17,0,239,1,0,0,0,0,0,0,0,17,,82,-38,-38,-38,-38,-38
S,FactoredDiscriminant,Returns the sequence of finite and real places where A is ramified,0,1,0,0,0,0,0,0,0,17,,82,82,-38,-38,-38,-38
S,RamifiedPlaces,Same as FactoredDiscriminant,0,1,0,0,0,0,0,0,0,17,,82,82,-38,-38,-38,-38
S,IsMatrixRing,Returns true iff A is isomorphic to a matrix ring,0,1,0,0,0,0,0,0,0,17,,36,176,175,-38,-38,-38
S,Norm,Norm of the element a,0,1,0,0,0,0,0,0,0,436,,-45,-38,-38,-38,-38,-38
S,Trace,Trace of the element a,0,1,0,0,0,0,0,0,0,436,,-45,-38,-38,-38,-38,-38
S,Conjugate,Conjugate of the element a,0,1,0,0,0,0,0,0,0,436,,436,-38,-38,-38,-38,-38
S,CharacteristicPolynomial,The characteristic polynomial of a,0,1,0,0,0,0,0,0,0,436,,312,-38,-38,-38,-38,-38
S,IsMaximalAtRamifiedPrimes,Returns true if and only if O is maximal at all ramified primes,0,1,0,0,0,0,0,0,0,435,,36,-38,-38,-38,-38,-38
S,RModule,Returns the quaternion order O as a module over the quadratic order R,0,2,0,0,0,0,0,0,0,215,,0,0,435,,-1,-38,-38,-38,-38,-38
S,RModule,Returns the quaternion order O as a module over the quadratic order R,0,2,0,0,0,0,0,0,0,215,,0,0,19,,-1,-38,-38,-38,-38,-38
