174,1
T,TorPol,-,0
A,TorPol,6,max_dim_poly,max_dim_emb,max_dim_trans,compact_part,hash_value,description
S,PrintNamed,The description of the polyhedron P,0,3,0,0,1,0,0,0,0,298,,0,0,298,,0,0,TorPol,,-38,-38,-38,-38,-38,-38
S,Hash,The hash value of the polyhedron,0,1,0,0,0,0,0,0,0,TorPol,,148,-38,-38,-38,-38,-38
S,eq,True iff the polyhedra P1 and P2 are equal,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,subset,True iff the polyhedron P1 is a subset of the polyhedron P2,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,meet,The polyhedron given by the intersection of the polyhedra P1 and P2,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,+,,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,-,,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,-,,0,2,0,0,0,0,0,0,0,TorLatElt,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,+,The translation of the polyhedra P by Q,0,2,0,0,0,0,0,0,0,TorLatElt,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,+,,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,+,The translation of the cone C by Q,0,2,0,0,0,0,0,0,0,TorLatElt,,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,+,,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,+,The Minkowski sum of the polyhedron P and the cone C,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,+,The Minkowski sum of the polyhedra P and Q,0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,-,The negation -P of the polyhedra P,0,1,0,0,0,0,0,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,*,,0,2,0,0,0,0,0,0,0,TorPol,,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,*,The dilation kP of the polyhedron P,0,2,0,0,0,0,0,0,0,TorPol,,0,0,267,,TorPol,-38,-38,-38,-38,-38
S,*,"The direct product of the polyhedra, lying in the direct sum of their ambient toric lattices",0,2,0,0,0,0,0,0,0,TorPol,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,*,The product P * M of a polyhedron P with a square matrix M,0,2,0,0,0,0,0,0,0,-34,,0,0,TorPol,,TorLatElt,-38,-38,-38,-38,-38
S,/,,0,2,0,0,0,0,0,0,0,148,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,/,The dilation (1/k)P of the polyhedron P,0,2,0,0,0,0,0,0,0,267,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,ChangeAmbient,A polyhedron equal to P except for lying in the ambient toric lattice L,0,2,0,0,0,0,0,0,0,TorLat,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,The polyhedron arising as the preimage of the cone C under the affine map phi + v,1,1,2,175,0,TorLat,0,TorLat,3,0,0,0,0,0,0,0,TorLatElt,,0,0,175,,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,,0,3,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,The polyhedron arising as the intersection of the cone C with the hyperplane H at height h,0,3,0,0,0,0,0,0,0,267,,0,0,TorLatElt,,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,The polyhedron arising as the intersection of the cone C with the hyperplane at height one (can be changed via 'level'),0,1,0,0,0,0,0,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,,1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,,1,0,1,82,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,The polytope defined by taking the convex hull of the sequence of vectors S,1,0,1,82,1,82,0,267,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,Polytope,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorPol,-38,-38,-38,-38,-38
S,Polytope,,1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,Polytope,,1,0,1,82,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,Polytope,The polytope defined by taking the convex hull of the sequence of vectors S,1,0,1,82,1,82,0,267,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,,0,3,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,Polyhedron,The polyhedron arising as the intersection of the polyhedron P with the hyperplane H at height h,0,3,0,0,0,0,0,0,0,267,,0,0,TorLatElt,,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,StandardSimplex,The d-dimensional simplex given by the standard basis and the origin,0,1,0,0,0,0,0,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,StandardSimplex,The simplex given by the standard basis of the toric lattice L and the origin,0,1,0,0,0,0,0,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,BoxPolytope,"The d-dimensional cube [0,1]^d",0,1,0,0,0,0,0,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,BoxPolytope,"The d-dimensional cube [0,1]^d in the toric lattice L",0,1,0,0,0,0,0,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,CrossPolytope,The d-dimensional cross-polytope,0,1,0,0,0,0,0,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,CrossPolytope,The maximum dimensional cross-polytope in the toric lattice L,0,1,0,0,0,0,0,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,CyclicPolytope,The cyclic polytope generated by n points in d-dimensional space,0,2,0,0,0,0,0,0,0,148,,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,CyclicPolytope,The cyclic polytope generated by n points in the toric lattice L,0,2,0,0,0,0,0,0,0,148,,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,ConeToPolyhedron,The cone C realised as a polyhedron,0,1,0,0,0,0,0,0,0,TorCon,,TorPol,-38,-38,-38,-38,-38
S,HyperplaneToPolyhedron,,1,0,1,82,0,148,2,0,0,0,0,0,0,0,148,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HyperplaneToPolyhedron,,1,0,1,82,0,148,2,0,0,0,0,0,0,0,267,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HyperplaneToPolyhedron,,1,0,1,82,0,267,2,0,0,0,0,0,0,0,148,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HyperplaneToPolyhedron,,1,0,1,82,0,267,2,0,0,0,0,0,0,0,267,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HyperplaneToPolyhedron,,0,2,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,HyperplaneToPolyhedron,The hyperplane v * u = h realised as a polyhedron,0,2,0,0,0,0,0,0,0,267,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,HalfspaceToPolyhedron,,1,0,1,82,0,148,2,0,0,0,0,0,0,0,148,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HalfspaceToPolyhedron,,1,0,1,82,0,148,2,0,0,0,0,0,0,0,267,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HalfspaceToPolyhedron,,1,0,1,82,0,267,2,0,0,0,0,0,0,0,148,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HalfspaceToPolyhedron,,1,0,1,82,0,267,2,0,0,0,0,0,0,0,267,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,HalfspaceToPolyhedron,,0,2,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,HalfspaceToPolyhedron,The halfspace v * u >= h realised as a polyhedron,0,2,0,0,0,0,0,0,0,267,,0,0,TorLatElt,,TorPol,-38,-38,-38,-38,-38
S,FixedSubspaceToPolyhedron,,0,1,0,0,0,0,0,0,0,178,,TorPol,-38,-38,-38,-38,-38
S,FixedSubspaceToPolyhedron,"The subspace (realised as a polyhedron) fixed by the action of the matrix group G on the toric lattice L. G should be a subgroup of either GL(n,Z) or of SL(n,Z), where n is the dimension of L",0,2,0,0,0,0,0,0,0,178,,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,RandomPolytope,"A random polytope in the toric lattice L, generated by n points whose coefficients lie between -k and k",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,RandomPolytope,"A random polytope in a d-dimensional toric lattice, generated by n points whose coefficients lie between -k and k",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,PolytopeOfProjectiveSpace,,0,1,0,0,0,0,0,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,PolytopeOfProjectiveSpace,A simplex whose spanning fan corresponds to projective space P^d,0,1,0,0,0,0,0,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,PolytopeOfWPS,A simplex whose spanning fan corresponds to projective space P^d,0,1,0,0,0,0,0,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,PolytopeOfWPS,,1,0,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,PolytopeOfWPS,A simplex whose spanning fan corresponds to weighted projective space P(lambda),1,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,PolyhedronWithInequalities,,2,0,1,82,1,82,0,148,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,PolyhedronWithInequalities,,2,0,1,82,1,82,0,267,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,PolyhedronWithInequalities,"The polyhedron defined by Ai*v >= ci for each Ai,ci in A,c",2,0,1,82,0,TorLatElt,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,82,,TorPol,-38,-38,-38,-38,-38
S,EmptyPolyhedron,The empty polyhedron in a d-dimensional toric lattice,0,1,0,0,0,0,0,0,0,148,,TorPol,-38,-38,-38,-38,-38
S,EmptyPolyhedron,The empty polyhedron in the given toric lattice L,0,1,0,0,0,0,0,0,0,TorLat,,TorPol,-38,-38,-38,-38,-38
S,PolyhedronInSublattice,The polyhedron of maximal dimension given by the intersection of the toric lattice containing the polyhedron P with an affine sublattice of dimension equal to the dimension of P. Also gives the affine embedding as a lattice embedding and translation,0,1,0,0,0,0,0,0,0,TorPol,,TorPol,175,TorLatElt,-38,-38,-38
S,CompactPart,The polytope defined by taking the convex hull of the vertices of the polyhedron P. If P is not pointed then gives a (non-unique) polytope Q such that Q + infinite part equals P,0,1,0,0,0,0,0,0,0,TorPol,,TorPol,-38,-38,-38,-38,-38
S,BoundingBox,The smallest polytope Q that is a hyper-box and contains the polytope P. Also gives the bottom-left and top-right corners of the box,0,1,0,0,0,0,0,0,0,TorPol,,TorPol,TorLatElt,TorLatElt,-38,-38,-38
