174,1
A,TorPol,10,dimension,is_empty,is_polytope,is_affine,is_integral,is_simplicial,is_simple,is_smooth,is_fano,gorenstein_index
S,Dimension,The dimension of the polyhedron P,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,ContainsZero,True iff the polyhedron P contains the origin strictly in its interior,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsEmpty,True iff the polyhedron P is empty,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsAffineLinear,True iff the polyhedron P is an affine linear space,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsLinearSpace,True iff the polyhedron P is a linear space,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsPointed,True iff the polyhedron P is pointed (i.e. if it is empty or has a vertex),0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsPolytope,True iff P is a polytope,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsMaximumDimensional,True iff the dimension of the polyhedron P equals the dimension of the ambient lattice,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsIntegral,"True iff the vertices of the polyhedron P are at integral coordinates in the underlying toric lattice or, if P contains lines, iff the smallest dimensional non-trivial faces of P are generated by integral points",0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsIntegrallyClosed,"True iff the polytope P is integrally closed (i.e. every lattice point in k*P can be written as the sum of k lattice points in P, for all k)",0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsPerfectlyCentered,"True iff the polyhedron P is a polytope containing the origin strictly in its interior, such that for any nonempty face F of P the intersection relint(F) with the (outer) normal cone is nonempty",0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsFano,"True iff the polyhedron P is a Fano polytope (i.e. of maximum dimension, containg the origin strictly in its interior, with primitive lattice vertices)",0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsSimplex,True iff the polyhedron P is a simplex,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsSimplicial,True iff the polyhedron P is a simplicial polytope,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsSimple,True iff the polyhedron P is simple,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsSmooth,True iff the polyhedron P is a smooth polytope,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,IsReflexive,True iff the polyhedron P is a reflexive polytope,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
S,GorensteinIndex,The Gorenstein index of the Fano polytope P,0,1,0,0,0,0,0,0,0,TorPol,,148,-38,-38,-38,-38,-38
S,IsFlag,True iff the simplicial poytope P is flag,0,1,0,0,0,0,0,0,0,TorPol,,36,-38,-38,-38,-38,-38
