174,1
S,AbsoluteModuleOverMinimalField,"Write the absolutely irreducible module M over the smallest possible field containing F, without increasing the dimension of the module",0,2,0,0,0,0,0,0,0,84,,0,0,103,,103,-38,-38,-38,-38,-38
S,AbsoluteModuleOverMinimalField,Write the absolutely irreducible module M over the smallest possible field without increasing the dimension of the module,0,1,0,0,0,0,0,0,0,103,,103,-38,-38,-38,-38,-38
S,AbsoluteModulesOverMinimalField,"Write the sequence Q of modules over the smallest possible field containing F, without increasing the dimension of the module",0,2,0,0,0,0,0,0,0,84,,0,0,82,,82,-38,-38,-38,-38,-38
S,ModuleOverSmallerField,Write the module M over the field F,0,2,0,0,0,0,0,0,0,84,,0,0,103,,103,-38,-38,-38,-38,-38
S,ModulesOverSmallerField,Write the sequence Q of modules over the smallest possible field without increasing the dimension of the module,0,2,0,0,0,0,0,0,0,84,,0,0,82,,82,-38,-38,-38,-38,-38
S,AbsolutelyIrreducibleConstituents,"Given an irreducible module M, return M if it is already absolutely irreducible, else return the absolutely irreducible modules obtained by rewriting M in smaller degree after extending the base field of M to a splitting field",0,1,0,0,0,0,0,0,0,103,,82,-38,-38,-38,-38,-38
S,ModulesOverCommonField,"Given A-modules M and N, change their base fields to F, where F is the smallest overfield containg the base fields of M and N",0,2,0,0,0,0,0,0,0,103,,0,0,103,,103,103,-38,-38,-38,-38
S,CommonOverfield,"Given finite fields K and L, both of characteristic p, return the smallest field which contains both of them",0,2,0,0,0,0,0,0,0,84,,0,0,84,,84,-38,-38,-38,-38,-38
S,IsRealisableOverSmallerField,"Determine whether M be realised over a proper subfield of its base field. If so, return true and the equivalent module",0,1,0,0,0,0,0,0,0,103,,36,103,-38,-38,-38,-38
S,IsRealisableOverSubfield,"Determine whether M can be realised over the subfield F of its base field K. If so, return true and the equivalent module",0,2,0,0,0,0,0,0,0,84,,0,0,103,,36,103,-38,-38,-38,-38
S,ActionGenerators,Return the matrices giving the action on M as a sequence,0,1,0,0,0,0,0,0,0,181,,82,-38,-38,-38,-38,-38
S,ActionGroup,The matrix group generated by the action generators of a G-module M,0,1,0,0,0,0,0,0,0,103,,178,-38,-38,-38,-38,-38
