174,1
S,InternalInduceMap,,0,4,0,0,0,0,0,0,0,41,,0,0,217,,0,0,41,,0,0,27,,175,-38,-38,-38,-38,-38
S,CohomologyModule,"For G acting on A through m, create the Cohomology module. m has to be either a map:G->End(A) through which G acts, or a sequence of maps in End(A), one for each generator of G",0,3,0,0,0,0,0,0,0,-1,,0,0,107,,0,0,224,,397,-38,-38,-38,-38,-38
S,SUnitCohomologyProcess,Creates a cohomology process for the multiplicative group of the number field K. U has to be a subgroup of the automorphism group of K,1,0,1,83,0,217,2,0,0,0,0,0,0,0,224,,0,0,83,,83,-38,-38,-38,-38,-38
S,SimpleCohomologyProcess,Creates a cohomology process for the multiplicative group of the number field K. U has to be a subgroup of the automorphism group of K,0,2,0,0,0,0,0,0,0,224,,0,0,83,,83,-38,-38,-38,-38,-38
S,IsCoprime,True iff a and b are corpime,0,2,0,0,0,0,0,0,0,148,,0,0,148,,36,-38,-38,-38,-38,-38
S,IsCyclotomic,"Tests if K is cyclotomic and if so, return the field",1,0,1,-9,0,262,1,0,0,0,0,0,0,0,-9,,36,51,175,-38,-38,-38
S,EmbedIntoMinimalCyclotomicField,Returns the smallest cyclotomic field containing K and the embedding map,1,0,1,-9,0,262,1,0,0,0,0,0,0,0,-9,,51,175,-38,-38,-38,-38
S,SUnitSubGroup,,1,0,1,82,0,217,1,0,0,0,0,0,0,0,82,,107,175,-38,-38,-38,-38
S,SemiSimpleCohomologyProcess,"""Refines"" the cohomology process to use S-Units from subfields",0,1,0,0,1,0,0,1,1,83,,-38,-38,-38,-38,-38,-38
S,IsGloballySplit,"For a 2-cocyle H with values in the number field K (used to create the SUnitCohomologyProcess C), decide if H is globally split, and, if so, return a 1-cochain in the preimage of the boundary operator",0,2,0,0,0,0,0,0,0,41,,0,0,83,,36,41,-38,-38,-38,-38
S,PowerProduct,The power product B^E,2,0,1,82,0,324,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,82,,324,-38,-38,-38,-38,-38
S,IsSplitAsIdealAt,"For a 2-cocyle with values in the mult. group of some number field and some prime ideal I, see if the projection of l onto the group generated by I is trivial as a cocycle",0,2,0,0,0,0,0,0,0,41,,0,0,324,,-1,-38,-38,-38,-38,-38
