174,1
V,Transvection,4
S,PseudoReflection,The pseudo-reflection with the given root and coroot,0,2,0,0,0,0,0,0,0,192,,0,0,192,,177,-38,-38,-38,-38,-38
S,Transvection,The transvection with the given root and coroot,0,2,0,0,0,0,0,0,0,192,,0,0,192,,177,-38,-38,-38,-38,-38
S,Reflection,The reflection with the given root and coroot,0,2,0,0,0,0,0,0,0,192,,0,0,192,,177,-38,-38,-38,-38,-38
S,Reflection,The reflection with the given root and coroot,0,2,0,0,0,0,0,0,0,165,,0,0,165,,177,-38,-38,-38,-38,-38
S,TransvectionFactors,"A sequence of transvections and at most one dilatation whose product is f. If the determinant of f is not 1, the first element of the sequence will be a dilatation",0,2,0,0,0,0,0,0,0,180,,0,0,159,,82,-38,-38,-38,-38,-38
S,IsPseudoReflection,"If r is a pseudo-reflection, return a root and a coroot",0,1,0,0,0,0,0,0,0,177,,36,160,160,-38,-38,-38
S,IsPseudoReflection,"If r is a pseudo-reflection, return a root and a coroot",0,1,0,0,0,0,0,0,0,180,,36,160,160,-38,-38,-38
S,IsReflection,"If r is a reflection, return a root and a coroot",0,1,0,0,0,0,0,0,0,177,,36,160,160,-38,-38,-38
S,IsReflection,"If r is a reflection, return a root and a coroot",0,1,0,0,0,0,0,0,0,180,,36,160,160,-38,-38,-38
S,IsTransvection,"If r is a transvection, return a root and a coroot",0,1,0,0,0,0,0,0,0,177,,36,160,160,-38,-38,-38
S,IsTransvection,"If r is a transvection, return a root and a coroot",0,1,0,0,0,0,0,0,0,180,,36,160,160,-38,-38,-38
S,SymplecticTransvection,The symplectic transvection with root a and multiplier alpha with respect to the attached form,0,2,0,0,0,0,0,0,0,-25,,0,0,192,,177,-38,-38,-38,-38,-38
S,UnitaryTransvection,"The unitary transvection with root a and multiplier alpha with respect to the attached form, which must be alternating. alpha must have trace 0",0,2,0,0,0,0,0,0,0,-25,,0,0,192,,177,-38,-38,-38,-38,-38
S,UnitaryReflection,"The unitary reflection in the root a with respect to the attached hermitian form. The reflection sends a to zeta*a, where zeta is a root of unity",0,2,0,0,0,0,0,0,0,-25,,0,0,192,,177,-38,-38,-38,-38,-38
S,IsAbstractCartanMatrix,Check if C is the (abstract) Cartan matrix of a collection of reflections,0,1,0,0,0,0,0,0,0,177,,36,-38,-38,-38,-38,-38
S,BasicRootMatrices,A matrix A of roots and a matrix B of coroots of the matrix C such that C is A*Transpose(B). The default (Reduced is true) is to compute the roots and coroots modulo the null space of C,0,1,0,0,0,0,0,0,0,-34,,177,177,-38,-38,-38,-38
S,PseudoReflectionGroup,The pseudo-reflection group with the given basic root and coroot matrices,0,2,0,0,0,0,0,0,0,-34,,0,0,-34,,178,175,-38,-38,-38,-38
S,ShephardTodd,The primitive complex reflection group G_n using the Shephard-Todd numbering,0,1,0,0,0,0,0,0,0,148,,178,175,-38,-38,-38,-38
S,ShephardTodd,"The imprimitive complex reflection (Shephard-Todd) group G(m,p,n)",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,178,175,-38,-38,-38,-38
S,ImprimitiveReflectionGroup,"The imprimitive complex reflection (Shephard-Todd) group G(m,p,n)",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,178,175,-38,-38,-38,-38
S,ComplexReflectionGroup,The reflection group with the given (abstract) Cartan matrix,0,1,0,0,0,0,0,0,0,-34,,178,175,-38,-38,-38,-38
S,ComplexReflectionGroup,The primitive complex reflection group of type X_n,0,2,0,0,0,0,0,0,0,148,,0,0,298,,178,175,-38,-38,-38,-38
S,IsReflectionGroup,Test if the generators of G are reflections. Set Strict to false to test if G is generated by its reflections,0,1,0,0,0,0,0,0,0,178,,36,-38,-38,-38,-38,-38
