174,1
T,GrpBB,GrpBBElt,0
A,GrpBB,5,One,group,generators,supergroup,slots
T,GrpBBElt,-,0
A,GrpBBElt,2,Parent,Element
S,NaturalBlackBoxGroup,Construct the natural blackbox group from concrete group H,0,1,0,0,0,0,0,0,0,-27,,GrpBB,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,GrpBB,,-38,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,GrpBBElt,,-38,-38,-38,-38,-38,-38
S,IsCoercible,,0,2,0,0,0,0,0,0,0,-1,,0,0,GrpBB,,36,-1,-38,-38,-38,-38
S,in,,0,2,0,0,0,0,0,0,0,GrpBB,,0,0,-1,,36,-38,-38,-38,-38,-38
S,Parent,,0,1,0,0,0,0,0,0,0,GrpBBElt,,GrpBB,-38,-38,-38,-38,-38
S,eq,Test equality of the groups G and H,0,2,0,0,0,0,0,0,0,GrpBB,,0,0,GrpBB,,36,-38,-38,-38,-38,-38
S,eq,test equality of x and y,0,2,0,0,0,0,0,0,0,GrpBBElt,,0,0,GrpBBElt,,36,-38,-38,-38,-38,-38
S,*,The product of x and y,0,2,0,0,0,0,0,0,0,GrpBBElt,,0,0,GrpBBElt,,GrpBBElt,-38,-38,-38,-38,-38
S,^,the n-th power of x,0,2,0,0,0,0,0,0,0,148,,0,0,GrpBBElt,,GrpBBElt,-38,-38,-38,-38,-38
S,^,"The conjugate of x by y, y^-1*x*y",0,2,0,0,0,0,0,0,0,GrpBBElt,,0,0,GrpBBElt,,GrpBBElt,-38,-38,-38,-38,-38
S,Commutator,The commutator x^-1*y^-1*x*y,0,2,0,0,0,0,0,0,0,GrpBBElt,,0,0,GrpBBElt,,GrpBBElt,-38,-38,-38,-38,-38
S,.,the i-th generator of G,0,2,0,0,0,0,0,0,0,148,,0,0,GrpBB,,GrpBBElt,-38,-38,-38,-38,-38
S,Ngens,The number of generators of G,0,1,0,0,0,0,0,0,0,GrpBB,,148,-38,-38,-38,-38,-38
S,Generators,The generators of G,0,1,0,0,0,0,0,0,0,GrpBB,,83,-38,-38,-38,-38,-38
S,PseudoRandom,A pseudo-random element of G,0,1,0,0,0,0,0,0,0,GrpBB,,GrpBBElt,-38,-38,-38,-38,-38
S,UnderlyingElement,The underlying concrete group element of x,0,1,0,0,0,0,0,0,0,GrpBBElt,,-28,-38,-38,-38,-38,-38
S,Subgroup,Form the subgroup of G generated by the elements of Q,1,1,1,82,0,GrpBBElt,2,0,0,0,0,0,0,0,82,,0,0,GrpBB,,GrpBB,-38,-38,-38,-38,-38
S,Identity,The identity element of G,0,1,0,0,0,0,0,0,0,GrpBB,,GrpBBElt,-38,-38,-38,-38,-38
S,Order,"The order of the underlying element of x, if it exists",0,1,0,0,0,0,0,0,0,GrpBBElt,,148,-38,-38,-38,-38,-38
