174,1
A,GrpMat,30,Seed,NormalSeed,BlockNumbers,BlockSizes,NmrOfBlocks,BlocksImage,BlockSystem,ImprimitiveFlag,TensorProductFlag,TensorFactors,TensorBasis,Generators,ExtraSpecialFlag,ExtraSpecialGroup,ExtraSpecialParameters,ExtraSpecialBasis,ExtraSpecialGenerators,ExtraSpecialNormaliser,SemiLinearFlag,DegreeOfFieldExtension,LinearPart,CentralisingMatrix,FrobeniusAutomorphisms,SmallerFieldChangeOfBasis,SmallerField,TensorInducedImageBasis,TensorInducedFlag,TensorInducedFactors,TensorInducedPermutations,TensorInducedBasis
A,ModGrp,26,Seed,BlockNumbers,BlockSizes,NmrOfBlocks,BlocksImage,BlockSystem,ImprimitiveFlag,TensorProductFlag,TensorFactors,TensorBasis,Generators,ExtraSpecialFlag,ExtraSpecialGroup,ExtraSpecialParameters,ExtraSpecialBasis,ExtraSpecialGenerators,ExtraSpecialNormaliser,SemiLinearFlag,DegreeOfFieldExtension,LinearPart,CentralisingMatrix,FrobeniusAutomorphisms,TensorInducedFlag,TensorInducedFactors,TensorInducedPermutations,TensorInducedBasis
A,AlgMat,2,Seed,Generators
A,GrpPerm,3,Seed,Generators,NormalSeed
S,GModule,Return G-module generated by sequence of matrices,1,0,1,82,0,-34,1,0,0,0,0,0,0,0,82,,103,-38,-38,-38,-38,-38
S,GModule,Return G-module generated by set of matrices,1,0,1,83,0,-34,1,0,0,0,0,0,0,0,83,,103,-38,-38,-38,-38,-38
S,Dimension,Return degree of matrices of G,0,1,0,0,0,0,0,0,0,178,,148,-38,-38,-38,-38,-38
S,GeneratorsSequence,The sequence of group generators,0,1,0,0,0,0,0,0,0,178,,82,-38,-38,-38,-38,-38
S,BasicParameters,Return the dimension and field for G,0,1,0,0,0,0,0,0,0,178,,148,148,-38,-38,-38,-38
S,BasicParameters,Return the dimension and field for G,0,1,0,0,0,0,0,0,0,176,,148,148,-38,-38,-38,-38
S,BasicParameters,Return the dimension and field for the G-module M,0,1,0,0,0,0,0,0,0,103,,148,148,-38,-38,-38,-38
S,GroupGenerators,Return a sequence containing generators of the underlying group,0,1,0,0,0,0,0,0,0,176,,82,-38,-38,-38,-38,-38
S,GroupGenerators,Return a sequence containing generators of the underlying group,0,1,0,0,0,0,0,0,0,103,,82,-38,-38,-38,-38,-38
S,GroupGenerators,Return as a sequence the generators of the group G,0,1,0,0,0,0,0,0,0,178,,82,-38,-38,-38,-38,-38
