174,1
T,SmpCpx,-,0
A,SmpCpx,4,Faces,HomologyModules,HomologyMaps,ordering
S,SimplicialComplex,Constructs an abstract simplicial complex with the faces in the list faces,1,0,1,-52,0,83,1,0,0,0,0,0,0,0,-52,,SmpCpx,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,SmpCpx,,-38,-38,-38,-38,-38,-38
S,AddSimplex,Adds the simplex s to the simplicial complex smp returning a new complex,0,2,0,0,0,0,0,0,0,83,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,AddSimplex,Adds the simplex s to to the simplicial complex smp,0,2,0,0,1,0,0,0,0,83,,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,AddSimplex,Adds all simplices in s to the simplicial complex smp,0,2,0,0,0,0,0,0,0,82,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,AddSimplex,Adds all simplices in s to the simplicial complex smp,0,2,0,0,1,0,0,0,0,82,,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,Dimension,Returns the dimension of the highest dimensional face of smp,0,1,0,0,0,0,0,0,0,SmpCpx,,148,-38,-38,-38,-38,-38
S,Faces,Returns the faces of one degree of the simplicial complex. Requires deg to be dimension+1,0,2,0,0,0,0,0,0,0,148,,0,0,SmpCpx,,82,-38,-38,-38,-38,-38
S,Facets,Returns the facets of the simplicial complex smp,0,1,0,0,0,0,0,0,0,SmpCpx,,82,-38,-38,-38,-38,-38
S,Boundary,Returns the simplicial complex generated by all simplexes that lie in the boundary of the simplicial complex smp,0,1,0,0,0,0,0,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,BarycentricSubdivision,Returns the barycentric subdivision of the simplicial complex s,0,1,0,0,0,0,0,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Skeleton,Returns the q-skeleton of the simplicial complex smp,0,2,0,0,0,0,0,0,0,148,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,+,"Returns the topological sum, or disjoint union, of two simplicial complexes. Requires both complexes to be normalized",0,2,0,0,0,0,0,0,0,SmpCpx,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Product,Returns the cartesian product of two simplicial complexes,0,2,0,0,0,0,0,0,0,SmpCpx,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,eq,"Compares two simplicial complexes. Will not do any isomorphism finding, only compare whether the two abstract simplicial complexes are the very same",0,2,0,0,0,0,0,0,0,SmpCpx,,0,0,SmpCpx,,36,-38,-38,-38,-38,-38
S,Prune,Removes a face f and all faces containing f from a simplicial complex smp,0,2,0,0,0,0,0,0,0,83,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Prune,Removes a face f and all faces containing f from a simplicial complex smp,0,2,0,0,1,0,0,0,0,83,,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,Glue,"In the simplicial complex smp, identify all points identified by pairs in the sequence eqs",0,2,0,0,0,0,0,0,0,82,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Glue,"In the simplicial complex smp, identify all points identified by pairs in the sequence eqs",0,2,0,0,1,0,0,0,0,82,,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,Join,Constructs the join of two simplicial complexes. Requires both simplicial complexes to be normalized,0,2,0,0,0,0,0,0,0,SmpCpx,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,*,Constructs the join of two simplicial complexes. Requires both simplicial complexes to be normalized,0,2,0,0,0,0,0,0,0,SmpCpx,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Cone,"Constructs a cone over the given complex. The cone is generated by all faces of the complex, with an additional vertex included into each face. Requires a normalized simplicial complex",0,1,0,0,0,0,0,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Suspension,Constructs the suspension (double cone) over the given complex. Requires a normalized simplicial complex,0,1,0,0,0,0,0,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Normalization,Replaces the points with integers from 1 and upwards,0,1,0,0,0,0,0,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Normalization,Replaces the points with integers from 1 and upwards,0,1,0,0,1,0,0,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,Shift,Shifts all integers in the point labels in smp by an offset given by n. Requires the complex to be normalized,0,2,0,0,0,0,0,0,0,148,,0,0,SmpCpx,,SmpCpx,-38,-38,-38,-38,-38
S,Shift,Shifts all integers in the point labels in smp by an offset given by n. Requires the complex to be normalized,0,2,0,0,1,0,0,0,0,148,,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,UnderlyingGraph,The underlying graph of the simplicial complex smp,0,1,0,0,0,0,0,0,0,SmpCpx,,105,310,80,-38,-38,-38
S,FlagComplex,Returns the flag complex of the graph G,0,1,0,0,0,0,0,0,0,-26,,SmpCpx,-38,-38,-38,-38,-38
S,CliqueComplex,Returns the clique complex of the graph G,0,1,0,0,0,0,0,0,0,-26,,SmpCpx,-38,-38,-38,-38,-38
S,SimplicialComplex,Returns the 1-dimensional simplicial complex of the graph,0,1,0,0,0,0,0,0,0,-26,,SmpCpx,-38,-38,-38,-38,-38
S,Simplex,Returns an n-dimensional simplex as a simplicial complex,0,1,0,0,0,0,0,0,0,148,,SmpCpx,-38,-38,-38,-38,-38
S,Sphere,Returns a triangulation of the n-sphere,0,1,0,0,0,0,0,0,0,148,,SmpCpx,-38,-38,-38,-38,-38
S,KleinBottle,Returns a triangulation of the Klein bottle as a simplicial complex,0,0,0,0,0,0,0,SmpCpx,-38,-38,-38,-38,-38
S,Torus,Returns a triangulation of the torus as a simplicial complex,0,0,0,0,0,0,0,SmpCpx,-38,-38,-38,-38,-38
S,Cylinder,Returns a triangulation of a circular cylinder as a simplicial complex,0,0,0,0,0,0,0,SmpCpx,-38,-38,-38,-38,-38
S,MoebiusStrip,Returns a triangulation of the Moebius strip as a simplicial complex,0,0,0,0,0,0,0,SmpCpx,-38,-38,-38,-38,-38
S,SimplicialProjectivePlane,Returns one triangulation of the projective plane,0,0,0,0,0,0,0,SmpCpx,-38,-38,-38,-38,-38
S,LensSpace,"Constructs the lens space L(p,1)",0,1,0,0,0,0,0,0,0,148,,SmpCpx,-38,-38,-38,-38,-38
S,ChainComplex,Constructs a chaincomplex of A-modules corresponding to the abstract simplicial complex s,0,2,0,0,0,0,0,0,0,-44,,0,0,SmpCpx,,183,-38,-38,-38,-38,-38
S,Homology,Calculates the homology of a simplicial complex with coefficients in the ring of integers,0,1,0,0,0,0,0,0,0,-1,,82,82,-38,-38,-38,-38
S,Homology,Calculates and caches the homology of a simplicial complex with coefficients in the ring of integers,0,1,0,0,1,0,0,1,1,-38,,-38,-38,-38,-38,-38,-38
S,Homology,Calculates the homology of a simplicial complex with coefficients in A,0,2,0,0,1,0,0,0,0,-44,,1,1,SmpCpx,,-38,-38,-38,-38,-38,-38
S,Homology,Calculates the homology of a simplicial complex with coefficients in A,0,2,0,0,0,0,0,0,0,-44,,0,0,SmpCpx,,82,82,-38,-38,-38,-38
S,FormalChain,"Prints a chain in the homology class h of dimension d using the lists H and M from H,M := Homology(ChainComplex(smp,R)); for some ring R",0,5,0,0,1,0,0,0,0,SmpCpx,,0,0,82,,0,0,82,,0,0,148,,0,0,192,,-38,-38,-38,-38,-38,-38
S,HomologyGenerators,"Prints generators of the homology groups together with their order, in order of dimension",0,3,0,0,1,0,0,0,0,SmpCpx,,0,0,82,,0,0,82,,-38,-38,-38,-38,-38,-38
S,HomologyGenerators,"Prints generators of the integral homology groups of the simplicial complex smp together with their order, in order of dimension",0,1,0,0,1,0,0,0,0,SmpCpx,,-38,-38,-38,-38,-38,-38
S,HomologyGenerators,"Prints generators of the homology groups of the simplicial complex smp together with their order, in order of dimension",0,2,0,0,1,0,0,0,0,-44,,0,0,SmpCpx,,-38,-38,-38,-38,-38,-38
S,HomologyGroup,Returns the qth homology of the simplicial complex smp,0,2,0,0,0,0,0,0,0,148,,0,0,SmpCpx,,181,-38,-38,-38,-38,-38
S,HomologyGroup,Returns the qth homology of the simplicial complex smp with coefficients in A,0,3,0,0,0,0,0,0,0,-44,,0,0,148,,0,0,SmpCpx,,181,-38,-38,-38,-38,-38
S,BoundaryMatrix,Constructs the qth boundary matrix of the simplicial complex smp with coefficients in A,0,3,0,0,0,0,0,0,0,-44,,0,0,148,,0,0,SmpCpx,,-34,-38,-38,-38,-38,-38
S,BettiNumber,Returns the qth betti number of the simplicial complex,0,2,0,0,0,0,0,0,0,148,,0,0,SmpCpx,,148,-38,-38,-38,-38,-38
S,BettiNumber,Returns the qth betti number of the simplicial complex,0,3,0,0,0,0,0,0,0,-44,,0,0,148,,0,0,SmpCpx,,148,-38,-38,-38,-38,-38
S,TorsionCoefficients,Returns the torsion coefficients of the qth homology group of smp,0,2,0,0,0,0,0,0,0,148,,0,0,SmpCpx,,82,-38,-38,-38,-38,-38
S,TorsionCoefficients,Returns the torsion coefficients of the qth homology group of smp with coefficients in A,0,3,0,0,0,0,0,0,0,-44,,0,0,148,,0,0,SmpCpx,,82,-38,-38,-38,-38,-38
S,EulerCharacteristic,Returns the Euler characteristic of the complex,0,1,0,0,0,0,0,0,0,SmpCpx,,148,-38,-38,-38,-38,-38
