174,1
S,HackobjPrintNamedRootDtmSprs,Internal intrinsic: Print the root datum R at level l,0,3,0,0,1,0,0,0,0,298,,0,0,298,,0,0,490,,-38,-38,-38,-38,-38,-38
S,HackobjPrintRootDtmSprs,Internal intrinsic: Print the root datum R at level l,0,2,0,0,1,0,0,0,0,298,,0,0,490,,-38,-38,-38,-38,-38,-38
S,HackobjHashRootDtmSprs,Internal intrinsic: Return a hash value for a root datum,0,1,0,0,0,0,0,0,0,490,,148,-38,-38,-38,-38,-38
S,HackobjSubConstrRootDtmSprs,Internal intrinsic: The root subdatum of R with the given simples,0,2,0,0,0,0,0,0,0,82,,0,0,490,,489,-1,-38,-38,-38,-38
S,HackobjSubConstrRootDtmSprs,Internal intrinsic: The root subdatum of R generated by gens,0,2,0,0,0,0,0,0,0,83,,0,0,490,,489,-1,-38,-38,-38,-38
S,HackobjSubConstrRootDtmSprs,Internal intrinsic: The root subdatum of R on the subspaces U (resp V) of the (co)root space,0,3,0,0,0,0,0,0,0,159,,0,0,159,,0,0,489,,489,-1,-38,-38,-38,-38
S,SparseRootDatum,Root datum R as sparse root datum,0,1,0,0,0,0,0,0,0,489,,490,-38,-38,-38,-38,-38
S,RootDatum,Return sparse root datum R as non-sparse root datum,0,1,0,0,0,0,0,0,0,490,,490,-38,-38,-38,-38,-38
S,SparseRootDatum,The sparse root datum whose simple (co)roots are the rows of the matrix A (B),0,2,0,0,0,0,0,0,0,-34,,0,0,-34,,490,-38,-38,-38,-38,-38
S,SparseIrreducibleRootDatum,The sparse irreducible root datum with Cartan name X_n,0,2,0,0,0,0,0,0,0,148,,0,0,298,,490,-38,-38,-38,-38,-38
S,SparseRootDatum,The sparse root datum with Cartan name N,0,1,0,0,0,0,0,0,0,298,,490,-38,-38,-38,-38,-38
S,SparseRootDatum,The sparse root datum with Cartan matrix C,0,1,0,0,0,0,0,0,0,177,,490,-38,-38,-38,-38,-38
S,SparseRootDatum,The sparse root datum with Dynkin digraph D,0,1,0,0,0,0,0,0,0,57,,490,-38,-38,-38,-38,-38
S,SparseRootDatum,The sparse root datum of the root system R,0,1,0,0,0,0,0,0,0,491,,490,-38,-38,-38,-38,-38
S,SparseStandardRootDatum,The sparse standard root datum with Cartan name X_n,0,2,0,0,0,0,0,0,0,148,,0,0,298,,490,-38,-38,-38,-38,-38
S,IsTwisted,"Returns true iff the root datum is twisted, that is, nonsplit",0,1,0,0,0,0,0,0,0,490,,36,-38,-38,-38,-38,-38
S,IsSplit,Returns true iff the root datum is split,0,1,0,0,0,0,0,0,0,490,,36,-38,-38,-38,-38,-38
S,CheckSparseRootDatum,Internal. Checks a sparse root datum for consistency,0,1,0,0,1,0,0,0,0,490,,-38,-38,-38,-38,-38,-38
S,Root,The rth root of R,0,2,0,0,0,0,0,0,0,148,,0,0,490,,-1,-38,-38,-38,-38,-38
S,Coroot,The rth coroot of R,0,2,0,0,0,0,0,0,0,148,,0,0,490,,-1,-38,-38,-38,-38,-38
S,RootPosition,The position of the vector v as a root of R,0,2,0,0,0,0,0,0,0,-1,,0,0,490,,148,-38,-38,-38,-38,-38
S,CorootPosition,The position of the vector v as a coroot of R,0,2,0,0,0,0,0,0,0,-1,,0,0,490,,148,-38,-38,-38,-38,-38
S,Roots,The roots of R,0,1,0,0,0,0,0,0,0,490,,151,-38,-38,-38,-38,-38
S,Coroots,The coroots of R,0,1,0,0,0,0,0,0,0,490,,151,-38,-38,-38,-38,-38
S,RootNorms,The squares of the root lengths of R,0,1,0,0,0,0,0,0,0,490,,82,-38,-38,-38,-38,-38
S,CorootNorms,The squares of the coroot lengths of R,0,1,0,0,0,0,0,0,0,490,,82,-38,-38,-38,-38,-38
S,RootNorm,The square of the length of the rth root of R,0,2,0,0,0,0,0,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,CorootNorm,The square of the length of the rth coroot of R,0,2,0,0,0,0,0,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,RootHeight,The height of the rth root of R,0,2,0,0,0,0,0,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,CorootHeight,The height of the rth coroot of R,0,2,0,0,0,0,0,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LeftString,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,82,-38,-38,-38,-38,-38
S,RightString,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,82,-38,-38,-38,-38,-38
S,LeftStringLength,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,82,-38,-38,-38,-38,-38
S,RightStringLength,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,82,-38,-38,-38,-38,-38
S,ReflectionPermutation,,0,2,0,0,0,0,0,0,0,148,,0,0,490,,222,-38,-38,-38,-38,-38
S,ReflectionPermutations,,0,1,0,0,0,0,0,0,0,490,,82,-38,-38,-38,-38,-38
S,ExtraspecialPair,,0,2,0,0,0,0,0,0,0,148,,0,0,490,,148,148,-38,-38,-38,-38
S,ExtraspecialPairs,,0,1,0,0,0,0,0,0,0,490,,82,-38,-38,-38,-38,-38
S,LieConstant_epsilon,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_epsilon,,0,3,0,0,0,0,0,0,0,303,,0,0,303,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_C,,0,5,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_C,,0,5,0,0,0,0,0,0,0,303,,0,0,303,,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_N,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_N,,0,3,0,0,0,0,0,0,0,303,,0,0,303,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_M,,0,4,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_M,,0,4,0,0,0,0,0,0,0,148,,0,0,303,,0,0,303,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_eta,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,LieConstant_eta,,0,3,0,0,0,0,0,0,0,303,,0,0,303,,0,0,490,,148,-38,-38,-38,-38,-38
S,CartanInteger,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,490,,148,-38,-38,-38,-38,-38
S,CartanInteger,,0,3,0,0,0,0,0,0,0,303,,0,0,303,,0,0,490,,148,-38,-38,-38,-38,-38
S,StructureConstants,,0,1,0,0,0,0,0,0,0,490,,82,-38,-38,-38,-38,-38
