{
    5coverings.m
    6and12descent.m
    8descent.m
    8coverings.m  
    ab_grp.m
    alff_heights.m
    anf_heights.m
    auto.m
    base_change.m
    cassels-tate1.m
    cassels-tate_help.m
    cm.m
    compat.m
    cremona.m
    cubic_model.m
    ec_ff_misc.m
    ec_ghs.m
    ec_search.m
    ellmodel.m
    euler_factor.m
    formal_group.m
    functions.m
    heegner.m
    heegnernew.m
    height_diff.m
    height_padic.m
    heights.m
    highertwo.m
    isogenies.m
    isogenies2.m
    minmodel.m
    misc.m
    mw.m
    mw_sha.m
    pairings.m
    periods.m
    rank.m
    rootno.m
    saturation.m
    sintpoints_nf.m
    sintpoints.m
    sintpointsG1.m
    small_classno.m
    supersingular.m
    subgroup_schemes.m
    torsion.m 
    twists.m 
    twodesc.m
    twodesc_nf.m

    CrvEll_FldFun
    {
        +CrvEll_FldFun.spec
    }
    FourDesc
    {
	+d4spec.spec
    }
    ThreeDesc
    {
       +ThreeDesc.spec
    }
    NineDesc
    {
       +NineDesc.spec
    }
    pIsogDesc
    {
       +pIsogDesc.spec
    }
