174,1
S,TraceOfFrobenius,"The trace of the Frobenius endomorphism of E, where E is defined over a finite field",1,0,1,334,0,84,1,0,0,0,0,0,0,0,334,,148,-38,-38,-38,-38,-38
S,Trace,"The trace of the r-th power Frobenius endomorphism, where E is defined over a finite field",1,0,1,334,0,84,2,0,0,0,0,0,0,0,148,,0,0,334,,148,-38,-38,-38,-38,-38
S,TraceOfFrobenius,"The trace of the r-th power Frobenius endomorphism, where E is defined over a finite field",1,0,1,334,0,84,2,0,0,0,0,0,0,0,148,,0,0,334,,148,-38,-38,-38,-38,-38
S,Trace,The trace of Frobenius of the base extension of E to K,0,2,0,0,0,0,0,0,0,84,,0,0,334,,148,-38,-38,-38,-38,-38
S,TraceOfFrobenius,The trace of Frobenius of the base extension of E to K,0,2,0,0,0,0,0,0,0,84,,0,0,334,,148,-38,-38,-38,-38,-38
S,ReductionType,"Returns a string ""Good"", ""Additive"", ""Split multiplicative"" or ""Nonsplit multiplicative"" describing the reduction type of a minimal model for E",0,2,0,0,0,0,0,0,0,148,,0,0,334,,298,-38,-38,-38,-38,-38
S,Order,"The order of the group of rational points on the degree r extension of the base ring, where E is defined over a finite field",0,2,0,0,0,0,0,0,0,148,,0,0,334,,148,-38,-38,-38,-38,-38
S,Order,"The order of the group of rational points on the degree r extension of the ring of E, where E is defined over a finite field",0,2,0,0,0,0,0,0,0,148,,0,0,373,,148,-38,-38,-38,-38,-38
S,Order,"The order the group of rational points on E over K, where E is defined over the rationals or a finite field",0,2,0,0,0,0,0,0,0,84,,0,0,334,,148,-38,-38,-38,-38,-38
S,EulerFactor,"The Euler factor of E, i.e. the reciprocal characteristic polynomial of the Frobenius endomorphism",0,1,0,0,0,0,0,0,0,334,,312,-38,-38,-38,-38,-38
S,EulerFactor,The Euler factor of the base extension of E to K,0,2,0,0,0,0,0,0,0,84,,0,0,334,,312,-38,-38,-38,-38,-38
S,ZetaFunction,The zeta function of E,1,0,1,334,0,84,1,0,0,0,0,0,0,0,334,,238,-38,-38,-38,-38,-38
S,ZetaFunction,The zeta function of the base extension of E to K,1,0,1,334,0,262,2,0,0,0,0,0,0,0,84,,0,0,334,,238,-38,-38,-38,-38,-38
V,ECDom,2
S,CryptographicCurve,"Returns a randomly-generated elliptic curve E over the finite field F, a point P on E, a large prime ord (greater than OrderBound : default 2^160) such that P has order ord on E and (E, <cyclic subgroup generated by P>) satisfy standard security requirements, and finally #E/ord. If the parameter 'Proof' is true (the default), ord will be proved to be prime. If false, ord is only guaranteed to be a strong pseudo-prime. If parameter 'UseSEA' is set to true (not recommended!), the use of the SEA algorithm for computing #E is forced, and advantage can be taken of the early abort mechanism",0,1,0,0,0,0,0,0,0,84,,334,372,148,148,-38,-38
S,ValidateCryptographicCurve,"Checks that ordP is a prime and that P is a point on E of exact order ordP. It also checks that #E is h*ordP and that (E,P) satisfies the standard security conditions for cryptographic use, including ordP >= OrderBound (default 2^160). If parameter Proof is true (the default), ordP is proved to be prime. Otherwise, it is only verified to be a strong pseudo-prime",0,4,0,0,0,0,0,0,0,148,,0,0,148,,0,0,372,,0,0,334,,36,-38,-38,-38,-38,-38
