174,1
V,ECSaturation,3
S,Saturation,"Given a sequence of points on an elliptic curve over Q or a number field, returns a sequence of generators for the group obtained by saturating at all primes up to N",1,0,1,82,0,372,2,0,0,0,0,0,0,0,148,,0,0,82,,82,-38,-38,-38,-38,-38
S,Saturation,"Given a sequence of points on an elliptic curve over Q or a number field, returns a sequence of generators for the subgroup of the Mordell-Weil group consisting of all points P such that m*P for some integer m > 0 lies in the group generated by the given points",1,0,1,82,0,372,1,0,0,0,0,0,0,0,82,,82,36,-38,-38,-38,-38
