{
    SEA
    {
      sea_main.m
      trace_table.m
      torsion_module.m
      schoof.m
      elkies.m
      atkin.m
      canonlift0.m
      canonliftgen.m
      canonlifthyp.m
      deformation_method.m
      lercier.m
      menezes.m
      brent-kung.m
      shanks.m
    }
}
