174,1
A,AlgAssVOrd,1,Normalizer
S,Normalizer,Let O be an order in a definite quaternion algebra Q over a field F. This function returns the normalizer of O in Q^* modulo F^* as an abstract group G. A map from G to Q^* is also provided,1,0,1,19,0,311,1,0,0,0,0,0,0,0,19,,-27,175,-38,-38,-38,-38
S,Normalizer,Let O be an order in a definite quaternion algebra Q over a field F. This function returns the normalizer of O in Q^* modulo F^* as an abstract group G. A map from G to Q^* is also provided,1,0,1,19,0,319,1,0,0,0,0,0,0,0,19,,-27,175,-38,-38,-38,-38
S,Normalizer,Let O be an order in a definite quaternion algebra Q over a field F. This function returns the normalizer of O in Q^* modulo F^* as an abstract group G. A map from G to Q^* is also provided,1,0,1,435,0,215,1,0,0,0,0,0,0,0,435,,-27,175,-38,-38,-38,-38
S,CommutatorIdeal,The twosided ideal of O generated by elements of the form x*y - y*x,0,1,0,0,0,0,0,0,0,435,,437,-38,-38,-38,-38,-38
S,Factorization,"Given a twosided ideal I of an hereditary quaternion order, the function returns the unique factorization of I into twosided O-ideals",0,1,0,0,0,0,0,0,0,437,,82,-38,-38,-38,-38,-38
S,TwoSidedIdealClassGroup,The abelian group generated by the invertible twosided O-ideal classes together with a map to a system of representatives. The optional parameter is explained in TwoSidedIdealClasses,0,1,0,0,0,0,0,0,0,19,,107,175,-38,-38,-38,-38
S,TwoSidedIdealClassGroup,The abelian group generated by the invertible twosided O-ideal classes together with a map to a system of representatives. The optional parameter is explained in TwoSidedIdealClasses,0,1,0,0,0,0,0,0,0,435,,107,175,-38,-38,-38,-38
S,TwoSidedIdealClasses,A system of representatives for the twosided ideal classes of O. Support can be set to a sequence of prime ideals that generate the class group of the base ring. In that case the representents will have norm only supported in Support and the ramified primes of O,0,1,0,0,0,0,0,0,0,435,,82,-38,-38,-38,-38,-38
