174,1
S,Decomposition,A sequence of isogeny simple abelian subvarieties of A whose product is isogenous to A. Each is equipped with an embedding into A,0,1,0,0,0,0,0,0,0,ModAbVar,,82,-38,-38,-38,-38,-38
S,@,"The nth factor in Decomposition(A), denoted A(n)",0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,Factorization,Factorization of A as a product with multiplicities of abelian varieties B=A_f attached to newforms,0,1,0,0,0,0,0,0,0,ModAbVar,,168,-38,-38,-38,-38,-38
S,DecomposeUsing,Decompose A using the endomorphism phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,82,-38,-38,-38,-38,-38
S,DecomposeUsing,Decompose A using the commutative ring of endomorphisms generated by A,0,1,0,0,0,0,0,0,0,HomModAbVar,,82,-38,-38,-38,-38,-38
