174,1
V,ModAbVar,4
T,ModAbVar,ModAbVarElt,0
A,ModAbVar,33,base_ring,associated_abvar_over_Q,component_group_order,conductor,dimension,endomorphism_ring,endomorphism_algebra,hecke_algebra,field_of_definition,frobpolys,homology,inner_twists,weights,num_rational_points,cm_twists,isogeny_decomp,tamagawa_numbers,decomposition,is_simple,is_selfdual,is_Af,is_quaternionic,is_only_motivic,newform_number,newform,modular_param,modular_embedding,modular_degree,embeddings,only_maximal_newform_blocks,level,point_precision,name
S,JZero,"Create the modular abelian variety J_0(N), i.e., the Jacobian of the modular curve X_0(N)",0,1,0,0,0,0,0,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JZero,Create the modular abelian variety J_0(N) of weight k>=2,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JZero,Create the modular abelian variety J_0(N) of weight k>=2,0,2,0,0,0,0,0,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JOne,"Same as JOne(N,2)",0,1,0,0,0,0,0,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JOne,"Create the modular abelian variety J_1(N) of weight k, i.e., the Jacobian of the modular curve X_1(N)",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JOne,"Create the modular abelian variety J_1(N) of weight k, i.e., the Jacobian of the modular curve X_1(N)",0,2,0,0,0,0,0,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JH,"Create the Jacobian of the curve X_H(N), i.e. the quotient of X_1(N) by a subgroup H of the integers modulo N generated by gens",1,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JH,"Create the Jacobian of the curve X_H(N), i.e. the quotient of X_1(N) by a subgroup H of the integers modulo N generated by gens",1,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JH,"Create the Jacobian of the curve X_H(N), i.e. the quotient of X_1(N) by a subgroup H of the integers modulo N such that ((Z/N Z)^*)/H has order d",0,2,0,0,0,0,0,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,JH,"Create the Jacobian of the curve X_H(N), i.e. the quotient of X_1(N) by a subgroup H of the integers modulo N such that ((Z/N Z)^*)/H has order d",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,Js,A modular abelian variety that is Q-isogenous to the weight k version of J_1(N),0,2,0,0,0,0,0,0,0,148,,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,Js,"Same as Js(N,2)",0,1,0,0,0,0,0,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,Newform,A newform f such that A is isogenous to the newform abelian variety A_f,0,1,0,0,0,0,0,0,0,ModAbVar,,ModFrmElt,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety attached to the newform f,0,1,0,0,0,0,0,0,0,ModFrmElt,,ModAbVar,-38,-38,-38,-38,-38
S,ModularAbelianVariety,"Same as ModularAbelianVariety(eps,2)",0,1,0,0,0,0,0,0,0,GrpDrchElt,,ModAbVar,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety associated to eps. This corresponds to the space of modular forms of weight k and character any Galois conjugate of eps,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrchElt,,ModAbVar,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety attached to the sequence X of modular forms spaces,1,0,1,82,0,ModFrm,1,0,0,0,0,0,0,0,82,,ModAbVar,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety attached to the modular forms space M,0,1,0,0,0,0,0,0,0,ModFrm,,ModAbVar,-38,-38,-38,-38,-38
S,ModularSymbols,A sequence of spaces of modular symbols associated to A,0,1,0,0,0,0,0,0,0,ModAbVar,,82,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety attached to the modular symbols space M,0,1,0,0,0,0,0,0,0,ModSym,,ModAbVar,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety attached to the sequence X of modular symbols spaces,1,0,1,82,0,ModSym,1,0,0,0,0,0,0,0,82,,ModAbVar,-38,-38,-38,-38,-38
S,ZeroModularAbelianVariety,The zero-dimensional abelian variety of weight k,0,1,0,0,0,0,0,0,0,148,,ModAbVar,-38,-38,-38,-38,-38
S,ZeroModularAbelianVariety,The zero-dimensional abelian variety,0,0,0,0,0,0,0,ModAbVar,-38,-38,-38,-38,-38
S,ZeroSubvariety,Creates the zero subvariety of A,0,1,0,0,0,0,0,0,0,ModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,DefinesAbelianSubvariety,"True if and only if the subspace V of rational homology defines an abelian subvariety of A. If true, also returns the abelian subvariety",0,2,0,0,0,0,0,0,0,159,,0,0,ModAbVar,,36,ModAbVar,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety defined by the string s,0,1,0,0,0,0,0,0,0,298,,ModAbVar,-38,-38,-38,-38,-38
S,ModularAbelianVariety,The abelian variety with sign Sign defined by the string s,0,2,0,0,0,0,0,0,0,148,,0,0,298,,ModAbVar,-38,-38,-38,-38,-38
S,Weights,The set of weights of A,0,1,0,0,0,0,0,0,0,ModAbVar,,-50,-38,-38,-38,-38,-38
S,Level,An integer N so that A is a quotient of a power of J_1(N),0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,FieldOfDefinition,The best known field of definition of A,0,1,0,0,0,0,0,0,0,ModAbVar,,-24,-38,-38,-38,-38,-38
S,DirichletCharacter,"If A = A_f is attached to a newform, then this returns the Nebentypus character of f",0,1,0,0,0,0,0,0,0,ModAbVar,,GrpDrchElt,-38,-38,-38,-38,-38
S,DirichletCharacters,All Dirichlet characters of spaces of modular symbols associated with the modular symbols abelian variety that parameterizes A,0,1,0,0,0,0,0,0,0,ModAbVar,,168,-38,-38,-38,-38,-38
S,Dimension,The dimension of A,0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,BaseRing,The ring over which A is defined,0,1,0,0,0,0,0,0,0,ModAbVar,,-44,-38,-38,-38,-38,-38
S,Sign,"The sign of A, which is either 0, -1, or +1",0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,Conductor,"The conductor of the abelian variety A, where A is defined over Q",0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,NumberOfRationalPoints,"Divisor and multiple of the cardinality of A(K), where A is a modular abelian variety defined over a field K",0,1,0,0,0,0,0,0,0,ModAbVar,,148,148,-38,-38,-38,-38
S,#,"NumberOfRationalPoints, if an exact value known",0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,CMTwists,The CM inner twists characters of the newform abelian variety A = A_f that are defined over the base ring of A,0,1,0,0,0,0,0,0,0,ModAbVar,,82,-38,-38,-38,-38,-38
S,InnerTwists,"The inner twists characters of the newform abelian variety A = A_f that are defined over the base ring of A. WARNING: Even if Proof is True, the program does not prove that every twist returned is in fact an inner twist (though they are up to precision 0.00001)",0,1,0,0,0,0,0,0,0,ModAbVar,,82,-38,-38,-38,-38,-38
S,IsQuaternionic,True if and only if some simple factor of A over the base ring has quaternionic multiplication,0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsSimple,True if and only if A has no proper abelian subvarieties over BaseRing(A),0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsAttachedToNewform,True if A is isogenous to a newform abelian variety A_f in which case the abelian variety A_f is also returned,0,1,0,0,0,0,0,0,0,ModAbVar,,36,ModAbVar,MapModAbVar,-38,-38,-38
S,CanDetermineIsomorphism,True if we can determine whether or not A and B are isomorphic,0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVar,,36,36,MapModAbVar,-38,-38,-38
S,MinimalIsogeny,"True if A and B are isogenous. In that case returns the minimal degree of an isogeny between A and B and an explicit isogeny of that degree. False if A and B are not isogenous. If A and B are simple and defined over Q, then it is always possible to the minimal degree of an isogeny",0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVar,,36,MapModAbVar,148,-38,-38,-38
S,HasMultiplicityOne,True if the simple factors of A appear with multiplicity one,0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsIsomorphic,"True if A and B are isomorphic. If true, also returns an explicit isomorphism",0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVar,,36,MapModAbVar,-38,-38,-38,-38
S,IsIsogenous,True if A and B are isogenous,0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsAbelianVariety,True if A is an abelian variety,0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsSelfDual,True if A is known to be isomorphic to its dual,0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsAttachedToModularSymbols,True if the underlying homology of A is being computed using a space of modular symbols,0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsOnlyMotivic,True if any of the modular forms attached to A have weight bigger than 2,0,1,0,0,0,0,0,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,ModAbVar,,-38,-38,-38,-38,-38,-38
S,eq,True if A and B are equal,0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,in,True if A is equal to one of the elements of the list X,0,2,0,0,0,0,0,0,0,168,,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,subset,True if A is a subset of B,0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,ModularParameterization,A surjective morphism to A from an abelian variety attached to modular symbols,0,1,0,0,0,0,0,0,0,ModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,ModularEmbedding,A morphism with finite kernel from A to a modular abelian variety attached to modular symbols,0,1,0,0,0,0,0,0,0,ModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,CommonModularStructure,This intrinsic finds modular abelian varieties J_e and J_p associated to modular symbols and returns a list of finite-kernel maps from the abelian varieties in X to J_e and a list of modular paramaterizations from J_p to the abelian varieties in X,1,0,1,82,0,ModAbVar,1,0,0,0,0,0,0,0,82,,168,168,-38,-38,-38,-38
S,IsCoercible,"Coerce x into A. The argument x can be an element of a modular abelian variety, the integer 0, a sequence obtained by Eltseq'ing an element of A (i.e., a linear combination of *integral* homology), a vector on the basis for *rational* homology, or a tuple of the form <P(X,Y),[u,v]> that defines a modular symbol",0,2,0,0,0,0,0,0,0,-1,,0,0,ModAbVar,,36,ModAbVarElt,-38,-38,-38,-38
S,ModularSymbolToRationalHomology,The element of rational homology of the abelian variety A naturally associated to the modular symbol x,0,2,0,0,0,0,0,0,0,ModSymElt,,0,0,ModAbVar,,160,-38,-38,-38,-38,-38
S,ModularSymbolToRationalHomology,The element of rational homology of the abelian variety A naturally associated to the (formal) modular symbol x,0,2,0,0,0,0,0,0,0,82,,0,0,ModAbVar,,160,-38,-38,-38,-38,-38
S,ModularSymbolToRationalHomology,The element of rational homology of the abelian variety A naturally associated to the (formal) modular symbol x,0,2,0,0,0,0,0,0,0,303,,0,0,ModAbVar,,160,-38,-38,-38,-38,-38
S,ModularSymbolToIntegralHomology,The element of integral homology of the abelian variety A naturally associated to the (formal) modular symbol x,0,2,0,0,0,0,0,0,0,82,,0,0,ModAbVar,,160,-38,-38,-38,-38,-38
S,ModularSymbolToIntegralHomology,The element of integral homology of the abelian variety A naturally associated to the (formal) modular symbol x,0,2,0,0,0,0,0,0,0,303,,0,0,ModAbVar,,160,-38,-38,-38,-38,-38
S,Embeddings,Return a list of morphisms from A into abelian varieties,0,1,0,0,0,0,0,0,0,ModAbVar,,168,-38,-38,-38,-38,-38
S,AssertEmbedding,Prepend embedding phi to Embeddings(A),0,2,0,0,1,0,0,0,0,MapModAbVar,,1,1,ModAbVar,,-38,-38,-38,-38,-38,-38
S,BaseExtend,"Extend the base ring of A to R, if possible",0,2,0,0,0,0,0,0,0,-44,,0,0,ModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,ChangeRing,"Change the base ring of A to R, if possible",0,2,0,0,0,0,0,0,0,-44,,0,0,ModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,CanChangeRing,"True if it is possible to change the base ring of A to R, and A over R when possible",0,2,0,0,0,0,0,0,0,-44,,0,0,ModAbVar,,36,ModAbVar,-38,-38,-38,-38
