174,1
T,MapModAbVar,-,0
A,MapModAbVar,15,domain,codomain,matrix,field_of_definition,degree,name,is_isogeny,has_finite_kernel,hecke_operator,charpoly,minpoly,factored_charpoly,parent,denominator,only_up_to_isogeny
S,nIsogeny,The multiplication by n isogeny on A,0,2,0,0,0,0,0,0,0,148,,0,0,ModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,nIsogeny,The multiplication by n isogeny on A,0,2,0,0,0,0,0,0,0,267,,0,0,ModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,IdentityMap,The identity homomorphism from A to A,0,1,0,0,0,0,0,0,0,ModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,ZeroMap,The zero homomorphism from A to A,0,1,0,0,0,0,0,0,0,ModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,Evaluate,"The endomorphism f(phi) of A, where f is a univariant polynomial and phi is an endomorphism of a modular abelian variety A",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,312,,MapModAbVar,-38,-38,-38,-38,-38
S,DivideOutIntegers,"If phi:A to B is a homomorphism of abelian varieties, find the largest integer n such that psi=(1/n)*phi is also a homomorphism from A to B and return psi and n",0,1,0,0,0,0,0,0,0,MapModAbVar,,MapModAbVar,148,-38,-38,-38,-38
S,SurjectivePart,Given a homomorphism phi:Ato B of abelian varieties return the surjective homomorphism pi:A-> phi(A) induced by phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,RestrictEndomorphism,"The restriction of phi to an endomorphism of A, if this obviously makes sense",0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,RestrictEndomorphism,"Given an endomorphism phi of an abelian variety A and i:B -> A an injective morphism of abelian varieties such that i(B) is invariant under phi, return the endomorphism psi of B induced by phi",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,Restriction,The restriction of phi to a morphism from A to the codomain of phi,0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,RestrictionToImage,"Given morphisms i:A -> D and phi:D-> B of abelian varieties, return the restriction of phi to the image of i",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,UniversalPropertyOfCokernel,"Given pi:B -> C, the cokernel of a morphism and f:B -> D, a morphism whose kernel contains the kernel of pi, return the unique morphism psi:C ->D such that pi*psi = f",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,ConnectedKernel,The connected component C of ker(phi) and a morphism from C to the domain of phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVar,MapModAbVar,-38,-38,-38,-38
S,Kernel,"A finite subgroup G of A (the domain of phi), an abelian variety C such that ker(phi) equals f(C)+G, and an injective map f from C to A",0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVarSubGrp,ModAbVar,MapModAbVar,-38,-38,-38
S,ComponentGroupOfKernel,Component group of ker(phi),0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,@,"The image of A under phi, if this makes sense, i.e., if A is the domain of phi, or A has dimension 0, or one of the embeddings of A has codomain equal to the domain of phi",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,ModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,@,"The image of G under phi, if this makes sense. If A is the ambient variety of G, then this makes sense if A is the domain of phi, or A has dimension 0, or one of the embeddings of A has codomain equal to the domain of phi",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,@@,"A finite group who image under phi is equal to G, if possible. If phi has finite kernel, then this is the exact inverse image of G under phi. If not, then this is a group generated by a choice of torsion inverse image for each generator of G, which may not be canonical",0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,Image,"The image C of phi, which is a modular abelian subvariety contained in the codomain of phi, a morphism from C to the codomain of phi, and a surjective morphism from the domain of phi to C",0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVar,MapModAbVar,MapModAbVar,-38,-38,-38
S,Cokernel,The cokernel of phi and a morphism from the codomain of phi to the cokernel,0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVar,MapModAbVar,-38,-38,-38,-38
S,Eltseq,The Eltseq of the underlying matrix that defines phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,82,-38,-38,-38,-38,-38
S,IntegralMatrix,"The matrix which defines phi, written with respect to integral homology",0,1,0,0,0,0,0,0,0,MapModAbVar,,190,-38,-38,-38,-38,-38
S,IntegralMatrixOverQ,"The matrix which defines phi, written with respect to integral homology",0,1,0,0,0,0,0,0,0,MapModAbVar,,155,-38,-38,-38,-38,-38
S,RealMatrix,"The matrix which defines phi, written with respect to real homology",0,1,0,0,0,0,0,0,0,MapModAbVar,,155,-38,-38,-38,-38,-38
S,Matrix,The matrix on chosen basis of rational homology that defines phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,155,-38,-38,-38,-38,-38
S,Rows,The sequence rows of the matrix that defines phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,82,-38,-38,-38,-38,-38
S,Nrows,The number of rows of the matrix that defines phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,148,-38,-38,-38,-38,-38
S,Ncols,The number of columns of the matrix that defines phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,148,-38,-38,-38,-38,-38
S,Inverse,The inverse of phi and an integer d such that d*phi^-1 is a morphism of abelian varieties,0,1,0,0,0,0,0,0,0,MapModAbVar,,MapModAbVar,148,-38,-38,-38,-38
S,*,The composition of the homomorphism phi and psi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,+,The sum of the matrix that defines phi and the matrix psi,0,2,0,0,0,0,0,0,0,177,,0,0,MapModAbVar,,177,-38,-38,-38,-38,-38
S,+,The sum of the matrix that defines phi and the matrix psi,0,2,0,0,0,0,0,0,0,155,,0,0,MapModAbVar,,155,-38,-38,-38,-38,-38
S,+,The sum of the matrix psi and the matrix that defines phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,177,,177,-38,-38,-38,-38,-38
S,+,The sum of the matrix psi and the matrix that defines phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,155,,155,-38,-38,-38,-38,-38
S,-,The difference of the matrix that defines phi and the matrix psi,0,2,0,0,0,0,0,0,0,177,,0,0,MapModAbVar,,177,-38,-38,-38,-38,-38
S,-,The difference of the matrix that defines phi and the matrix psi,0,2,0,0,0,0,0,0,0,155,,0,0,MapModAbVar,,155,-38,-38,-38,-38,-38
S,-,The difference of the matrix psi and the matrix that defines phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,177,,177,-38,-38,-38,-38,-38
S,-,The difference of the matrix psi and the matrix that defines phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,155,,155,-38,-38,-38,-38,-38
S,*,The product of the matrix that defines phi and the matrix psi,0,2,0,0,0,0,0,0,0,177,,0,0,MapModAbVar,,177,-38,-38,-38,-38,-38
S,*,The product of the matrix that defines phi and the matrix psi,0,2,0,0,0,0,0,0,0,155,,0,0,MapModAbVar,,155,-38,-38,-38,-38,-38
S,*,The product of the matrix psi and the matrix that defines phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,177,,177,-38,-38,-38,-38,-38
S,*,The product of the matrix psi and the matrix that defines phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,155,,155,-38,-38,-38,-38,-38
S,*,The product of the integer a times the homomorphism phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,148,,MapModAbVar,-38,-38,-38,-38,-38
S,*,The product of the rational number a times the homomorphism phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,267,,MapModAbVar,-38,-38,-38,-38,-38
S,^,"The n-fold composition phi^n of the endomorphism phi with itself. If n=-1, then this is the inverse of phi, in which case phi must be an isogeny or there is an error",0,2,0,0,0,0,0,0,0,148,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,+,The sum of the homomorphism phi and psi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,-,The difference of the homomorphism phi and psi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,-,The difference of the endomorphism phi and the endomorphism multiplication-by-n,0,2,0,0,0,0,0,0,0,148,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,+,The sum of the endomorphism phi and the endomorphism multiplication-by-n,0,2,0,0,0,0,0,0,0,148,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,-,The difference of the endomorphism multiplication-by-n and the endomorphism phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,148,,MapModAbVar,-38,-38,-38,-38,-38
S,+,The sum of the endomorphism multiplication-by-n and the endomorphism phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,148,,MapModAbVar,-38,-38,-38,-38,-38
S,-,The difference of the endomorphism phi and the endomorphism multiplication-by-n,0,2,0,0,0,0,0,0,0,267,,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,-,The difference of multiplication-by-n and the endomorphism phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,267,,MapModAbVar,-38,-38,-38,-38,-38
S,+,The sum of multiplication by the rational number n and the endomorphism phi,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,267,,MapModAbVar,-38,-38,-38,-38,-38
S,CharacteristicPolynomial,The characteristic polynomial of the endomorphism phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,312,-38,-38,-38,-38,-38
S,MinimalPolynomial,The minimal polynomial of the endomorphism phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,312,-38,-38,-38,-38,-38
S,FactoredCharacteristicPolynomial,The factorization of the characteristic polynomial of the endomorphism phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,312,-38,-38,-38,-38,-38
S,Rank,The dimension of the kernel of phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,148,-38,-38,-38,-38,-38
S,Nullity,The dimension of the kernel of phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,148,-38,-38,-38,-38,-38
S,ClearDenominator,Morphism n*phi with n positive and minimal,0,1,0,0,0,0,0,0,0,MapModAbVar,,MapModAbVar,-38,-38,-38,-38,-38
S,Denominator,The smallest positive integer n such that n*phi is a homomorphism,0,1,0,0,0,0,0,0,0,MapModAbVar,,148,-38,-38,-38,-38,-38
S,Trace,The trace of a matrix that defines phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,267,-38,-38,-38,-38,-38
S,Degree,The degree of the morphism phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,148,-38,-38,-38,-38,-38
S,Domain,The domain of phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,Codomain,The codomain of phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,FieldOfDefinition,A field of definition of phi,0,1,0,0,0,0,0,0,0,MapModAbVar,,ModAbVar,-38,-38,-38,-38,-38
S,IsMorphism,True if and only if phi is a morphism in the category of abelian varieties,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,in,True if phi is one of the homomorphisms in the list X of homomorphisms,0,2,0,0,0,0,0,0,0,168,,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,eq,True if the two homomorphisms phi and psi are equal,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,eq,True if phi is equal to multiplication by the integer n,0,2,0,0,0,0,0,0,0,148,,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,eq,True if phi is equal to multiplication by the integer n,0,2,0,0,0,0,0,0,0,MapModAbVar,,0,0,148,,36,-38,-38,-38,-38,-38
S,IsEndomorphism,"True if phi is an endomorphism, i.e., the domain and codomain of phi are equal",0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsHeckeOperator,"If phi was computed using the HeckeOperator command, then true and the parameter n passed to the HeckeOperator command when creating phi. Otherwise false and 0",0,1,0,0,0,0,0,0,0,MapModAbVar,,36,148,-38,-38,-38,-38
S,HasFiniteKernel,True if the kernel of the homomorphism phi is finite,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsInjective,True if phi is an injective homomorphism,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsOptimal,"True if phi is an optimal quotient map, i.e., phi is surjective and has connected kernel",0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsIsomorphism,True if phi is an isomorphism of abelian varieties,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsIsogeny,True if phi is a surjective homomorphism with finite kernel,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsZero,True if phi is the zero morphism,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,IsInteger,"True if phi is multiplication by n for some integer n. If true, returns that n as well. If false, returns false and the second return value is not defined",0,1,0,0,0,0,0,0,0,MapModAbVar,,36,148,-38,-38,-38,-38
S,IsSurjective,True if the homomorphism phi is surjective,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,OnlyUpToIsogeny,Return true if phi is a homomorphism in the category of abelian varieties only up to isogeny,0,1,0,0,0,0,0,0,0,MapModAbVar,,36,-38,-38,-38,-38,-38
S,Parent,,0,1,0,0,0,0,0,0,0,MapModAbVar,,HomModAbVar,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,MapModAbVar,,-38,-38,-38,-38,-38,-38
