174,1
T,ModAbVarSubGrp,-,0
A,ModAbVarSubGrp,8,abgroup,from_abgroup,to_abgroup,field_of_definition,ambient_variety,generators,over_Q,name
S,nTorsionSubgroup,The kernel A[n] of the multiplication by n isogeny on A,0,2,0,0,0,0,0,0,0,148,,0,0,ModAbVar,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,nTorsionSubgroup,The kernel G[n] of the multiplication by n homomorphism on G,0,2,0,0,0,0,0,0,0,148,,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,ApproximateByTorsionGroup,The subgroup generated by torsion approximations of a set of generators of G,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,ZeroSubgroup,The zero subgroup of the abelian variety A,0,1,0,0,0,0,0,0,0,ModAbVar,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,Subgroup,The subgroup of A generated by the nonempty sequence X of elements of a modular abelian variety,1,0,1,82,0,ModAbVarElt,1,0,0,0,0,0,0,0,82,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,Elements,Sequence of all elements of the finite subgroup G of a modular abelian variety,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,82,-38,-38,-38,-38,-38
S,Ngens,The number generators of G,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,148,-38,-38,-38,-38,-38
S,Generators,Sequence of generators of G. These correspond to generators for the underlying abelian group,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,82,-38,-38,-38,-38,-38
S,.,The i-th generator of G,0,2,0,0,0,0,0,0,0,148,,0,0,ModAbVarSubGrp,,ModAbVarElt,-38,-38,-38,-38,-38
S,Quotient,"Quotient of the abelian variety A by the finite subgroup G, the isogeny A -> A/G and an isogeny A/G -> A, such that composition of the two isogenies is multiplication by the exponent of G",0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVar,,ModAbVar,MapModAbVar,-38,-38,-38,-38
S,Quotient,"The quotient A/G, where A is the ambient variety of G, an isogeny from A to A/G with kernel G, and an isogeny from A/G to A such that the composition of the two isogenies is multiplication by the exponent of G",0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,ModAbVar,MapModAbVar,MapModAbVar,-38,-38,-38
S,/,"The quotient A/G, the isogeny Ato A/G with kernel G, and an isogeny A/Gto A",0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVar,,ModAbVar,MapModAbVar,MapModAbVar,-38,-38,-38
S,+,"The sum of the subgroups groups G_1 and G_2 of abelian varieties A_1 and A_2. If A_1 is not equal to A_2, then G_1 and G_2 are replaced by their image in a common abelian variety",0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,meet,"The intersection of the finite subgroups G_1 and G_2 of an abelian variety. If their ambient varieties are not equal, G_1 and G_2 are replaced by their image in a common abelian variety",0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,meet,"The intersection of the finite subgroup G of an abelian variety B with the abelian variety A. If A is not equal to B, then G and A are replaced by their image in a common abelian variety",0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVarSubGrp,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,meet,"The intersection of the finite subgroup G of an abelian variety B with the abelian variety A. If A is not equal to B, then G and A are replaced by their image in a common abelian variety",0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVar,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,AbelianGroup,"An abstract abelian group H isomorphic to G, a map from H to G, and a map from G to H",0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,107,175,175,-38,-38,-38
S,Lattice,"Given a finite torsion subgroup G with ambient abelian variety A where G is generated by elements of H_1(A,Q)/H_1(A,Z), return the lattice generated by the coset representatives of H_1(A, Z)",0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,164,-38,-38,-38,-38,-38
S,#,The number of elements in G,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,148,-38,-38,-38,-38,-38
S,Order,The number of elements in G,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,148,-38,-38,-38,-38,-38
S,Exponent,An integer that kills G. We assume G is finite,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,148,-38,-38,-38,-38,-38
S,Invariants,Invariants of G as a finite abelian group,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,82,-38,-38,-38,-38,-38
S,FieldOfDefinition,A field over which the group G is defined (this is not guaranteed to be minimal!),0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,-24,-38,-38,-38,-38,-38
S,AmbientVariety,Abelian variety that contains G,0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,ModAbVar,-38,-38,-38,-38,-38
S,eq,True if G_1 equals G_2,0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVarSubGrp,,36,-38,-38,-38,-38,-38
S,subset,True if G1 is a subset of G2,0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVarSubGrp,,36,-38,-38,-38,-38,-38
S,subset,True if G is a subset of the abelian variety A,0,2,0,0,0,0,0,0,0,ModAbVar,,0,0,ModAbVarSubGrp,,36,-38,-38,-38,-38,-38
S,subset,True if the abelian variety A is a subset of the finitely generated group G,0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVar,,36,-38,-38,-38,-38,-38
S,IsFinite,"True if G is known to be finite, e.g., generated by torsion elements",0,1,0,0,0,0,0,0,0,ModAbVarSubGrp,,148,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,ModAbVarSubGrp,,-38,-38,-38,-38,-38,-38
S,in,"True if x is an element of G. If the ambient variety of x is different than the ambient variety of G, then use Embeddings to attempt to find a common abelian variety that contains (up to isogeny) both and check inclusion of images",0,2,0,0,0,0,0,0,0,ModAbVarSubGrp,,0,0,ModAbVarElt,,36,-38,-38,-38,-38,-38
