174,1
S,CuspidalSubgroup,"The subgroup of A generated by all differences of cusps, where we view A as a quotient of a modular symbols abelian variety",0,1,0,0,0,0,0,0,0,ModAbVar,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,RationalCuspidalSubgroup,"Finite subgroup of A generated by all differences of Q-rational cusps, where we view A in some way as a quotient of a modular symbols abelian variety",0,1,0,0,0,0,0,0,0,ModAbVar,,ModAbVarSubGrp,-38,-38,-38,-38,-38
S,TorsionLowerBound,A divisor of the cardinality of the K-rational torsion subgroup of A over K,0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,TorsionMultiple,"Same as TorsionMultiple(A,50)",0,1,0,0,0,0,0,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,TorsionMultiple,"A multiple of the cardinality of the K-rational torsion subgroup of A over K obtained by counting points on A mod p, where p varies over the odd primes p<=n such that p does not divide the level of A",0,2,0,0,0,0,0,0,0,148,,0,0,ModAbVar,,148,-38,-38,-38,-38,-38
S,TorsionSubgroup,"Either false and a subgroup of the torsion subgroup, or true and the exact torsion subgroup of A over the base field",0,1,0,0,0,0,0,0,0,ModAbVar,,36,ModAbVarSubGrp,-38,-38,-38,-38
