#!/bin/sh

unset MAGMA_STARTUP_FILE

if [ "$1" = "-r" ]
then
    shift
    rand=1
fi

#ARGS='-sstart -S1' 
ARGS='-sstart'

magma=$1
if [ "$magma" = "" ]
then
    magma=magma
fi

for x in \
    permg grp_fp integer mat smat vpoly vpoly_mult rspace ff ff_fact \
    language random groebner gb_sol hfe determinant \
    decomp dgcd dfact dfact_ff vfact insep acf lattice invar set iset mset \
    list rational quad mod mata mat_vpoly series ecpc sq eob_matrix basica \
    qform hc newton smith cyclo cyclo_units bool sgp_fp dpoly dpoly_local \
    dmodule ff_log order pselmer scheme lazy saverest gen_grp_ab ellmodel \
    real r4test resolution grp_lie_short grp_lie_reps gl_n cu_n hypercox \
    alff alff_completion E14_example.mag benchmark tpoly code locala locala_rel \
    kummer fld_ab_max_order grp_pc artin kas_prime_split series_ext \
    series_ext_unbounded complex sheaf_n_cohom galois_groups subfields \
    testCodesOverZ4.m galois_groups_reducible grp_mat_inf_test \
    beck_series beck_param small_mod_crvs \
    quad_class qform_class s_unit neq nf1 nfauto fld_fun_div numer_linalg \
    quat/embed-test.m quat/hilbert-test.m quat/ideals-test.m quat/interface-test.m \
    quat/iseichler-test.m quat/maxorder-test.m quat/order-test.m quat/pmatrix-test.m \
    quat/units-test.m \
    RelativeAlffTests/MoreElements \
    GrpPSL2 ModFrm/modsym ModFrm/half ModFrm/newforms ModFrm/ohs ModFrm/wt1 \
    theta_mf lattice_genus \
    ModFrmHil/p1 ModFrmHil/hmf1 ModFrmHil/hmf2 ModFrmHil/hmf3 \
    CrvG1/invariance.m CrvG1/discrete.m CrvG1/misc.m CrvG1/salmon-demo.m \
    CrvG1/minred-demo1.m CrvG1/minred-demo2.m CrvG1/3descent-demo.m CrvG1/add.m \
    Descent/2Q Descent/2isog_power Descent/ct Descent/8 Descent/2charp Descent/2char2 \
    Descent/nice \
    ec ec_fldrat ec_formal chabauty_ec crv_reg_model delpezzo lagrange \
    matg_unip.mag matg_unip_stab.mag \
    alg_lie/cartan-tp.mag alg_lie/chevbas.mag alg_lie/fplie.mag alg_lie/melikian.mag \
    alg_lie/twisted.mag alg_lie/hwrep.mag alg_lie/extr.mag alg_lie/kac.mag \
    convex/lattice convex/cones convex/equivalence convex/isomorphism \
    convex/points convex/polytopes convex/pyramids convex/v24 \
    toric_geom/divisors toric_geom/mmp1 toric_geom/mmp2 toric_geom/mmp3 \
    toric_geom/projective toric_geom/resolution toric_geom/variety \
    toric_geom/laurent_reflexive toric_geom/ambient test_sympconj\
    test_ShephardTodd test_ComplexRootData test_OrderFormulae test_sympconj\
    test_Clifford test_quadform test_GrpLie test_ChevOrder test_Witt\
    test_BasicDegrees test_WittDecomp test_WGraph test_Forms test_NF\
    test_restmat ClassGroupSievePolys ClassGroupSieveFamily\
    ClassGroupSieveQuadDiscNeg ClassGroupSieveQuadDiscPos process \
    order_non_simple crvhyp_pmin_model timd/artin.m timd/lseries.m \
    timd/rational.m timd/groupname.m timd/galrep.m timd/splitfield.m \
    timd/hyplser.m timd/elltwist.m timd/galrepcrv.m hecke_char LatNF\
    alg_ass_max_ord_alff alg_ass_max_ord_anf orderq local local_inf_prec \
    testPermDecodeOverFq.m testDecodeOverZ4_part1.m testDecodeOverZ4_part2.m
do
    echo "Testing $x:"
    if [ "$rand" = 1 ]
    then
	$magma $ARGS -S '' < $x
    else
	$magma $ARGS -S1 < $x
    fi
done
