174,1
S,JacobianSequence,Returns the sequence of all first partial derivatives of the polynomial,0,1,0,0,0,0,0,0,0,63,,82,-38,-38,-38,-38,-38
S,JacobianIdeal,Returns the ideal generated by all first partial derivatives of the polynomial,0,1,0,0,0,0,0,0,0,63,,64,-38,-38,-38,-38,-38
S,JacobianIdeal,"Returns the ideal generated by the partial derivatives of each polynomial in the sequence, by each indeterminate in its parent ring",1,0,1,82,0,63,1,0,0,0,0,0,0,0,82,,64,-38,-38,-38,-38,-38
S,JacobianMatrix,"Returns the matrix with (i,j)'th entry the partial derivative of the i'th polynomial in the list with the j'th indeterminate of its parent ring",1,0,1,82,0,63,1,0,0,0,0,0,0,0,82,,178,-38,-38,-38,-38,-38
S,Saturation,The saturation of I with respect to J,0,2,0,0,0,0,0,0,0,64,,0,0,64,,64,-38,-38,-38,-38,-38
S,Saturation,The saturation of I with respect to the ideal generated by the variables of its polynomial ring,0,1,0,0,0,0,0,0,0,64,,64,-38,-38,-38,-38,-38
S,Extension,The extension of the ideal I with respect to the map phi,0,2,0,0,0,0,0,0,0,64,,0,0,175,,64,-38,-38,-38,-38,-38
S,Degree,Returns the degree of a homogeneous ideal of a polynomial ring all of whose variables have weight one,0,1,0,0,0,0,0,0,0,64,,148,-38,-38,-38,-38,-38
