174,1
A,CrvEll,1,LFunction
S,CharacteristicPolynomialFromTraces,Reciprocal characteristic polynomial from traces of powers of Frobenius,0,1,0,0,0,0,0,0,0,82,,312,-38,-38,-38,-38,-38
S,CharacteristicPolynomialFromTraces,"Degree d reciprocal characteristic polynomials with zeroes of absolute value q^(i/2) from traces of powers of Frobenius. If there are two possible signs of the constant coefficient, then it lists both possibilities. Otherwise it lists the polynomial twice",0,4,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,0,0,82,,312,312,-38,-38,-38,-38
S,ReciprocalPolynomial,Reciprocal of a univariate polynomial,0,1,0,0,0,0,0,0,0,312,,312,-38,-38,-38,-38,-38
S,FrobeniusActionOnReducibleFiber,"Given LocalInformation, computes the matrix representing the Frobenius action on the non-identy components of a reducible fiber",0,1,0,0,0,0,0,0,0,303,,177,-38,-38,-38,-38,-38
S,FrobeniusActionOnTrivialLattice,Matrix representing the Frobenius action on the sublattice of Neron Severi group of elliptic surface that is generated by fiber components and zero section,1,0,1,334,0,239,1,0,0,0,0,0,0,0,334,,177,-38,-38,-38,-38,-38
S,BettiNumber,i-th Betti number of elliptic surface,1,0,1,334,0,-3,2,0,0,0,0,0,0,0,148,,0,0,334,,148,-38,-38,-38,-38,-38
S,NumbersOfPointsOnSurface,,1,0,1,334,0,4,2,0,0,0,0,0,0,0,148,,0,0,334,,82,82,-38,-38,-38,-38
S,NumbersOfPointsOnSurface,"A sequence containing the numbers of points on the Kodaira-Neron model of E over the field extensions of degrees 1 up to e, and sequence containing the numbers of points the base curve over the same fields",1,0,1,334,0,239,2,0,0,0,0,0,0,0,148,,0,0,334,,82,82,-38,-38,-38,-38
S,NumberOfPointsOnSurface,The number of points on the Kodaira-Neron model of E over the constant field extension of degree e,1,0,1,334,0,239,2,0,0,0,0,0,0,0,148,,0,0,334,,148,-38,-38,-38,-38,-38
S,LFunction,L-Function of E,1,0,1,334,0,239,1,0,0,0,0,0,0,0,334,,312,-38,-38,-38,-38,-38
S,LFunction,"L-Function of E. To speed up the compution, points in s are used to reduce the unknown part of H^2. If the parameter Check is false, then the points in s must form a basis for a subgroup of the geometric Mordell-Weil group modulo torsion that is stable under Galois action",1,0,1,334,0,239,2,0,0,0,0,0,0,0,82,,0,0,334,,312,-38,-38,-38,-38,-38
S,LFunction,The L-function for the base change of E by a constant field extension of degree e,1,0,1,334,0,-3,2,0,0,0,0,0,0,0,148,,0,0,334,,312,-38,-38,-38,-38,-38
S,AnalyticInformation,"Given elliptic curve E over a function field over a finite field, output a tuple consisting of the rank, geometric rank, and product of order of Tate-Shafarevich group and regulator of E after extending the constant field with degree e",1,0,1,334,0,-3,2,0,0,0,0,0,0,0,148,,0,0,334,,303,-38,-38,-38,-38,-38
S,AnalyticInformation,"Given elliptic curve E over a function field over a finite field, output a tuple consisting of the rank, geometric rank, and product of order of Tate-Shafarevich group and regulator",1,0,1,334,0,-3,1,0,0,0,0,0,0,0,334,,303,-38,-38,-38,-38,-38
S,AnalyticInformation,"Given E, together with its L-function, output a tuple consisting of the rank, geometric rank, and product of order of Tate-Shafarevich group and regulator",1,0,1,334,0,-3,2,0,0,0,0,0,0,0,312,,0,0,334,,303,-38,-38,-38,-38,-38
S,AnalyticRank,Analytic rank of E,1,0,1,334,0,-3,1,0,0,0,0,0,0,0,334,,148,-38,-38,-38,-38,-38
S,PowerPolynomial,A polynomial whose roots are the nth powers of the roots of f,0,2,0,0,0,0,0,0,0,148,,0,0,312,,312,-38,-38,-38,-38,-38
S,MatrixWithGivenCharacteristicPolynomial,Matrix with characteristic polynomial f,0,1,0,0,0,0,0,0,0,312,,177,-38,-38,-38,-38,-38
