174,1
S,RationalsAsNumberField,Returns the number field Q[x]/(x-1),0,0,0,0,0,0,0,27,-38,-38,-38,-38,-38
S,QNF,Returns the number field Q[x]/(x-1),0,0,0,0,0,0,0,27,-38,-38,-38,-38,-38
S,NumberField,Returns K,0,1,0,0,0,0,0,0,0,262,,262,-38,-38,-38,-38,-38
S,NumberField,Returns K,0,1,0,0,0,0,0,0,0,27,,27,-38,-38,-38,-38,-38
S,NumberField,Returns Rationals(),0,1,0,0,0,0,0,0,0,319,,262,-38,-38,-38,-38,-38
S,MaximalOrder,Returns Integers(),0,1,0,0,0,0,0,0,0,262,,319,-38,-38,-38,-38,-38
S,Decomposition,The factorization of rational prime p into prime ideals in order O,0,2,0,0,0,0,0,0,0,148,,0,0,319,,82,-38,-38,-38,-38,-38
S,Minimum,A generator for the Z-ideal I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,PrimitiveElement,A generator for the Z-ideal I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,Basis,A basis consisting of the generator of the Z-ideal I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,Norm,A basis consisting of the generator of the Z-ideal I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,RamificationIndex,The ramification index for I,0,2,0,0,0,0,0,0,0,148,,0,0,319,,148,-38,-38,-38,-38,-38
S,RamificationIndex,The ramification index for I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,Degree,The inertia degree of I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,TwoElementNormal,Two generators and g for the ideal I forming a two-element g-normal presentation,0,1,0,0,0,0,0,0,0,319,,148,148,-38,-38,-38,-38
S,^,Ideal arithmetic,0,2,0,0,0,0,0,0,0,148,,0,0,319,,319,-38,-38,-38,-38,-38
S,*,Ideal arithmetic,0,2,0,0,0,0,0,0,0,319,,0,0,148,,319,-38,-38,-38,-38,-38
S,*,Ideal arithmetic,0,2,0,0,0,0,0,0,0,319,,0,0,267,,319,-38,-38,-38,-38,-38
S,/,Ideal arithmetic,0,2,0,0,0,0,0,0,0,319,,0,0,319,,319,-38,-38,-38,-38,-38
S,IsIntegral,Returns true,0,1,0,0,0,0,0,0,0,319,,36,-38,-38,-38,-38,-38
S,IsOne,True iff I is the trivial ideal generated by 1,0,1,0,0,0,0,0,0,0,319,,36,-38,-38,-38,-38,-38
S,IsZero,True iff I is the zero ideal,0,1,0,0,0,0,0,0,0,319,,36,-38,-38,-38,-38,-38
S,Order,Returns IntegerRing(),0,1,0,0,0,0,0,0,0,319,,319,-38,-38,-38,-38,-38
S,ChineseRemainderTheorem,The Chinese remainder theorem formulated with ideals,0,4,0,0,0,0,0,0,0,148,,0,0,148,,0,0,319,,0,0,319,,148,-38,-38,-38,-38,-38
S,AbsoluteMinimalPolynomial,The absolute minimal polynomial of x over Q,0,1,0,0,0,0,0,0,0,267,,312,-38,-38,-38,-38,-38
S,Valuation,The valuation of x at the prime ideal p,0,2,0,0,0,0,0,0,0,319,,0,0,267,,148,-38,-38,-38,-38,-38
S,Valuation,The valuation of x at the prime ideal p,0,2,0,0,0,0,0,0,0,319,,0,0,148,,148,-38,-38,-38,-38,-38
S,Valuation,The valuation of x at the prime ideal p,0,2,0,0,0,0,0,0,0,319,,0,0,319,,148,-38,-38,-38,-38,-38
S,Valuation,The valuation of x at the prime ideal p,0,2,0,0,0,0,0,0,0,148,,0,0,319,,148,-38,-38,-38,-38,-38
S,ClassRepresentative,The representative of I in the basis of the class group,0,1,0,0,0,0,0,0,0,319,,319,-38,-38,-38,-38,-38
S,UnitGroup,The unit group of the maximal order of Q (i.e. of Z),0,1,0,0,0,0,0,0,0,262,,107,175,-38,-38,-38,-38
S,pFundamentalUnits,The unit group of the maximal order of Q (i.e. of Z),0,2,0,0,0,0,0,0,0,148,,0,0,262,,107,175,-38,-38,-38,-38
S,TorsionUnitGroup,The unit group of the maximal order of Q (i.e. of Z),0,1,0,0,0,0,0,0,0,262,,107,175,-38,-38,-38,-38
S,Eltseq,Returns [x],0,1,0,0,0,0,0,0,0,267,,82,-38,-38,-38,-38,-38
S,Eltseq,Returns [x],0,1,0,0,0,0,0,0,0,148,,82,-38,-38,-38,-38,-38
S,Signature,The signature (number of real embeddings and pairs of complex embeddings) of Q,0,1,0,0,0,0,0,0,0,319,,148,148,-38,-38,-38,-38
S,Signature,The signature (number of real embeddings and pairs of complex embeddings) of Q,0,1,0,0,0,0,0,0,0,262,,148,148,-38,-38,-38,-38
S,Generators,Returns [1],0,1,0,0,0,0,0,0,0,262,,82,-38,-38,-38,-38,-38
S,IsTotallyPositive,True iff x is positive,0,1,0,0,0,0,0,0,0,267,,36,-38,-38,-38,-38,-38
S,IsTotallyPositive,True iff x is positive,0,1,0,0,0,0,0,0,0,148,,36,-38,-38,-38,-38,-38
S,Generators,Returns [n],0,1,0,0,0,0,0,0,0,148,,82,-38,-38,-38,-38,-38
S,AbsoluteNorm,Returns x,0,1,0,0,0,0,0,0,0,148,,148,-38,-38,-38,-38,-38
S,AbsoluteNorm,Returns x,0,1,0,0,0,0,0,0,0,267,,267,-38,-38,-38,-38,-38
S,AbsoluteNorm,The norm of the ideal I,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,Basis,The basis of Q as a Q vector space,0,1,0,0,0,0,0,0,0,262,,82,-38,-38,-38,-38,-38
S,AbsoluteDegree,The absolute degree of K over Q,0,1,0,0,0,0,0,0,0,262,,148,-38,-38,-38,-38,-38
S,AbsoluteDegree,The absolute degree of O over Z,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,BaseField,The base field of Q,0,1,0,0,0,0,0,0,0,262,,262,-38,-38,-38,-38,-38
S,BaseRing,The base field of Q,0,1,0,0,0,0,0,0,0,262,,262,-38,-38,-38,-38,-38
S,AbsoluteBasis,A Q-basis of K,0,1,0,0,0,0,0,0,0,262,,82,-38,-38,-38,-38,-38
S,AbsoluteDiscriminant,The absolute discrimiant of Q,0,1,0,0,0,0,0,0,0,262,,148,-38,-38,-38,-38,-38
S,AbsoluteDiscriminant,The absolute discrimiant of Z,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,ClassNumber,Returns 1,0,1,0,0,0,0,0,0,0,262,,148,-38,-38,-38,-38,-38
S,ClassNumber,Returns 1,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,NarrowClassNumber,Returns 1,0,1,0,0,0,0,0,0,0,262,,148,-38,-38,-38,-38,-38
S,NarrowClassNumber,Returns 1,0,1,0,0,0,0,0,0,0,319,,148,-38,-38,-38,-38,-38
S,NarrowClassGroup,The narrow class group of the rationals,0,1,0,0,0,0,0,0,0,262,,107,175,-38,-38,-38,-38
S,NarrowClassGroup,The narrow class group of the integers,0,1,0,0,0,0,0,0,0,319,,107,175,-38,-38,-38,-38
S,AbsoluteField,Returns K,0,1,0,0,0,0,0,0,0,262,,262,-38,-38,-38,-38,-38
S,Automorphisms,Sequence containing the identity map,0,1,0,0,0,0,0,0,0,262,,82,-38,-38,-38,-38,-38
S,BachBound,Returns 1,0,1,0,0,0,0,0,0,0,262,,148,-38,-38,-38,-38,-38
S,MinkowskiBound,Returns 1,0,1,0,0,0,0,0,0,0,262,,148,-38,-38,-38,-38,-38
S,CompositeFields,Returns [K],0,2,0,0,0,0,0,0,0,262,,0,0,-9,,-9,-38,-38,-38,-38,-38
S,CompositeFields,Returns [K],0,2,0,0,0,0,0,0,0,-9,,0,0,262,,-9,-38,-38,-38,-38,-38
S,CompositeFields,Returns [Rationals()],0,2,0,0,0,0,0,0,0,262,,0,0,262,,262,-38,-38,-38,-38,-38
S,Compositum,Returns K,0,2,0,0,0,0,0,0,0,262,,0,0,-9,,-9,-38,-38,-38,-38,-38
S,Compositum,Returns K,0,2,0,0,0,0,0,0,0,-9,,0,0,262,,-9,-38,-38,-38,-38,-38
S,Compositum,Returns [Rationals()],0,2,0,0,0,0,0,0,0,262,,0,0,262,,262,-38,-38,-38,-38,-38
S,Embed,Do nothing,0,3,0,0,1,0,0,0,0,-1,,0,0,-9,,0,0,262,,-38,-38,-38,-38,-38,-38
S,Embed,Do nothing,0,3,0,0,1,0,0,0,0,-1,,0,0,262,,0,0,262,,-38,-38,-38,-38,-38,-38
S,PowerIdeal,The set of ideals over R,0,1,0,0,0,0,0,0,0,319,,240,-38,-38,-38,-38,-38
S,LLL,Returns R,0,1,0,0,0,0,0,0,0,319,,319,-38,-38,-38,-38,-38
