174,1
S,ShortenCode,"If possible, shorten the quantum code C=[[n,k,d]] at the positions specified by the complement of the support S of v, yielding a quantum code [[n-s,k'>=k-s,d'>=d]] where s:=n-#S",0,2,0,0,0,0,0,0,0,160,,0,0,317,,317,-38,-38,-38,-38,-38
S,QuantumCode,"If possible, shorten the quantum code C=[[n,k,d]] at the positions specified by the complement of the support S of v, yielding a quantum code [[n-s,k'>=k-s,d'>=d]] where s:=n-#S",0,2,0,0,0,0,0,0,0,160,,0,0,407,,317,-38,-38,-38,-38,-38
S,IsPureQuantumCode,True iff the symplectic dual of the stabilizer code S of C contains a word of minimum weight that is not contained in S or the dimension C is zero,0,1,0,0,0,0,0,0,0,317,,36,-38,-38,-38,-38,-38
S,ShortenStabilizerCode,"If C is a pure quantum code [[n,k,d]] with n>1, n>k, return a quantum code [n-1,k'>=k+1,d'>=d-1]]",0,2,0,0,0,0,0,0,0,148,,0,0,317,,317,-38,-38,-38,-38,-38
S,ShortenStabilizerCode,"If C is a pure quantum code [[n,k,d]] with n>1, n>k, return a quantum code [n-s,k'>=k+s,d'>=d-s]] wher s:=#S",1,1,1,83,0,148,2,0,0,0,0,0,0,0,83,,0,0,317,,317,-38,-38,-38,-38,-38
S,QECCLowerBound,,0,1,0,0,0,0,0,0,0,317,,148,-38,-38,-38,-38,-38
S,QECCUpperBound,,0,1,0,0,0,0,0,0,0,317,,148,-38,-38,-38,-38,-38
S,QuantumTwistedCode,The quantum twisted code over F of length n with defining interval A and parameter kappa (see Bierbrauer and Edel),1,2,1,82,0,148,4,0,0,0,0,0,0,0,148,,0,0,82,,0,0,148,,0,0,84,,317,-38,-38,-38,-38,-38
S,subset,True if the quantum code Q1 is contained in Q2,0,2,0,0,0,0,0,0,0,317,,0,0,317,,36,-38,-38,-38,-38,-38
S,StandardLengthening,,0,1,0,0,0,0,0,0,0,317,,317,-38,-38,-38,-38,-38
S,AdditiveConstaCyclicCode,Return the length n additive code over F generated by consta-cyclic shifts by c of the coefficients of f,0,4,0,0,0,0,0,0,0,85,,0,0,312,,0,0,148,,0,0,84,,407,-38,-38,-38,-38,-38
S,AdditiveQuasiTwistedCyclicCode,Construct the additive quasi-twisted cyclic code over F of length n pasting together the constacylic codes with parameter alpha generated by the polynomials in Gen,1,2,1,82,0,312,4,0,0,0,0,0,0,0,85,,0,0,82,,0,0,148,,0,0,84,,-39,-38,-38,-38,-38,-38
S,AdditiveQuasiTwistedCyclicCode,Construct the additive quasi-twisted cyclic code over F generated by simultaneous constacylic shifts w.r.t. alpha of the vectors in Gen,1,1,1,82,0,192,3,0,0,0,0,0,0,0,85,,0,0,82,,0,0,84,,-39,-38,-38,-38,-38,-38
