174,1
S,AtkinLehnerNumberOfFixedPoints,Computes the number of fixed points of Atkin-Lehner involution W_A acting on X0(N),0,2,0,0,0,0,0,0,0,148,,0,0,148,,148,-38,-38,-38,-38,-38
S,GenusX0N,Genus of X0(N),0,1,0,0,0,0,0,0,0,148,,148,-38,-38,-38,-38,-38
S,GenusX1N,Genus of X1(N),0,1,0,0,0,0,0,0,0,148,,148,-38,-38,-38,-38,-38
S,GenusX0NQuotient,Computes the genus of the quotient of X0(N) by the group of automorphisms generated by the Atkin-Lehner involutions W_A for A in As,1,1,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,148,,148,-38,-38,-38,-38,-38
