174,1
T,TorCon,-,0
A,TorCon,2,height_1_slice,hash
S,PrintNamed,The cone description,0,3,0,0,1,0,0,0,0,298,,0,0,298,,0,0,TorCon,,-38,-38,-38,-38,-38,-38
S,Hash,The hash value for the cone C,0,1,0,0,0,0,0,0,0,TorCon,,148,-38,-38,-38,-38,-38
S,+,The arithmetic sum of the cones C1 and C2,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorCon,,TorCon,-38,-38,-38,-38,-38
S,-,The minus cone C,0,1,0,0,0,0,0,0,0,TorCon,,TorCon,-38,-38,-38,-38,-38
S,*,The cone generated by v * M for each generator v in C with a square matrix M,0,2,0,0,0,0,0,0,0,-34,,0,0,TorCon,,TorLatElt,-38,-38,-38,-38,-38
S,meet,The cone which is the intersection of C1 and C2,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorCon,,TorCon,-38,-38,-38,-38,-38
S,subset,True iff C1 and C2 are the same cone,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,eq,True iff C1 and C2 are the same cone,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,ChangeAmbient,"Creates new cone in lattice L, which have the same geometry as C",0,2,0,0,0,0,0,0,0,TorLat,,0,0,TorCon,,TorCon,-38,-38,-38,-38,-38
S,Cone,,1,0,1,82,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,Cone,,1,0,1,82,1,82,0,267,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,Cone,,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorCon,-38,-38,-38,-38,-38
S,Cone,The cone generated by the vectors in S,1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,Cone,,0,1,0,0,0,0,0,0,0,TorLatElt,,TorCon,-38,-38,-38,-38,-38
S,Cone,,1,0,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,Cone,The one-dimensional cone generated by the toric lattice point v,1,0,1,82,0,267,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,Cones,"The sequence of cones generated by the toric lattice points in R with indices in S (i.e. the i-th cone in the sequence is generated by the points R[i1],...,R[ik], where S[i] = [i1,...,ik])",2,0,1,82,0,TorLatElt,1,1,82,1,82,0,148,2,0,0,0,0,0,0,0,82,,0,0,82,,82,-38,-38,-38,-38,-38
S,Dual,The dual cone to the cone C,0,1,0,0,0,0,0,0,0,TorCon,,TorCon,-38,-38,-38,-38,-38
S,ConeWithInequalities,,1,0,1,82,0,TorLatElt,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,ConeWithInequalities,,1,0,1,82,1,82,0,148,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,ConeWithInequalities,,1,0,1,82,1,82,0,267,1,0,0,0,0,0,0,0,82,,TorCon,-38,-38,-38,-38,-38
S,ConeWithInequalities,The cone defined by inequalities of the form v >= 0 for all v in S,1,0,1,83,0,TorLatElt,1,0,0,0,0,0,0,0,83,,TorCon,-38,-38,-38,-38,-38
S,ZeroCone,The cone in the toric lattice L supported at 0,0,1,0,0,0,0,0,0,0,TorLat,,TorCon,-38,-38,-38,-38,-38
S,ZeroCone,The cone in an n-dimensional lattice supported at 0,0,1,0,0,0,0,0,0,0,148,,TorCon,-38,-38,-38,-38,-38
S,FullCone,The full cone of then toric lattice L,0,1,0,0,0,0,0,0,0,TorLat,,TorCon,-38,-38,-38,-38,-38
S,FullCone,The full cone of an n-dimensional lattice,0,1,0,0,0,0,0,0,0,148,,TorCon,-38,-38,-38,-38,-38
S,PositiveQuadrant,The cone generated by the standard basis of the toric lattice L,0,1,0,0,0,0,0,0,0,TorLat,,TorCon,-38,-38,-38,-38,-38
S,PositiveQuadrant,The cone generated by the standard basis of an n-dimensional lattice,0,1,0,0,0,0,0,0,0,148,,TorCon,-38,-38,-38,-38,-38
S,RandomCone,"A random cone in the toric lattice L, generated by n points whose coefficients lie between -k and k",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,TorLat,,TorCon,-38,-38,-38,-38,-38
S,RandomCone,"A random cone in a d-dimensional toric lattice, generated by n points whose coefficients lie between -k and k",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,TorCon,-38,-38,-38,-38,-38
S,RandomPositiveCone,"A random cone in the toric lattice L, generated by n points whose coefficients lie between 0 and k",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,TorLat,,TorCon,-38,-38,-38,-38,-38
S,RandomPositiveCone,"A random cone in a d-dimensional toric lattice, generated by n points whose coefficients lie between 0 and k",0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,148,,TorCon,-38,-38,-38,-38,-38
