174,1
S,in,True iff the point Q lies in the interior of the cone C,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorLatElt,,36,-38,-38,-38,-38,-38
S,IsInInterior,True iff the point Q lies strictly in the relative interior of the cone C,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorLatElt,,36,-38,-38,-38,-38,-38
S,IsOnBoundary,True iff the point Q lies on the relative boundary of the cone C,0,2,0,0,0,0,0,0,0,TorCon,,0,0,TorLatElt,,36,-38,-38,-38,-38,-38
S,Points,,0,3,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,0,0,TorCon,,83,-38,-38,-38,-38,-38
S,Points,The integral lattice points in the cone C contained in the hyperplane slice H at height h. The intersection of H with C must be compact,0,3,0,0,0,0,0,0,0,267,,0,0,TorLatElt,,0,0,TorCon,,83,-38,-38,-38,-38,-38
S,BoxElements,"For a simplicial cone C, gives the coefficients of the points in the fundamental domain generated by the rays of C, with respect to the rays",0,1,0,0,0,0,0,0,0,TorCon,,83,-38,-38,-38,-38,-38
S,EhrhartCoefficient,The number of lattice points in the cone C at height k in the direction of the ambient grading,0,2,0,0,0,0,0,0,0,148,,0,0,TorCon,,148,-38,-38,-38,-38,-38
S,EhrhartCoefficient,"The number of lattice points in the cone C at height k in the direction H, where H is a primitive lattice point in the dual lattice",0,3,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,0,0,TorCon,,148,-38,-38,-38,-38,-38
S,EhrhartCoefficients,The first l+1 coefficients of the Ehrhart series for the cone C in the direction of the ambient grading,0,2,0,0,0,0,0,0,0,148,,0,0,TorCon,,82,-38,-38,-38,-38,-38
S,EhrhartCoefficients,"The first l+1 coefficients of the Ehrhart series for the cone C in the direction H, where H is a primitive lattice point in the dual lattice",0,3,0,0,0,0,0,0,0,148,,0,0,TorLatElt,,0,0,TorCon,,82,-38,-38,-38,-38,-38
S,EhrhartDeltaVector,The Ehrhart delta-vector for the cone C in the direction of the ambient grading,0,1,0,0,0,0,0,0,0,TorCon,,82,-38,-38,-38,-38,-38
S,EhrhartDeltaVector,"The Ehrhart delta-vector for the cone C in the direction H, where H is a primitive lattice point in the dual lattice",0,2,0,0,0,0,0,0,0,TorLatElt,,0,0,TorCon,,82,-38,-38,-38,-38,-38
S,EhrhartPolynomial,The Ehrhart (quasi-)polynomial for the cone C in the direction of the ambient grading,0,1,0,0,0,0,0,0,0,TorCon,,82,-38,-38,-38,-38,-38
S,EhrhartPolynomial,"The Ehrhart (quasi-)polynomial for the cone C in the direction H, where H is a primitive lattice point in the dual lattice",0,2,0,0,0,0,0,0,0,TorLatElt,,0,0,TorCon,,82,-38,-38,-38,-38,-38
S,EhrhartSeries,The rational generating function of the Ehrhart series for the cone C in the direction of the ambient grading,0,1,0,0,0,0,0,0,0,TorCon,,238,-38,-38,-38,-38,-38
S,EhrhartSeries,"The rational generating function of the Ehrhart series for the cone C in the direction H, where H is a primitive lattice point in the dual lattice",0,2,0,0,0,0,0,0,0,TorLatElt,,0,0,TorCon,,238,-38,-38,-38,-38,-38
