174,1
A,TorCon,6,gorenstein_hyperplane,gorenstein_index,is_smooth,is_isolated,is_terminal,is_canonical
S,IsQFactorial,True iff the cone C is simplicial (i.e. the corresponding affine variety is Q-Factorial),0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,PointToBlowUp,"If C is smooth or not simplicial, then gives the primitive vector of the sum of all MinimalRGenerators of C. Otherwise gives a point such that the blow up at this point will decrease the index of the singularities",0,1,0,0,0,0,0,0,0,TorCon,,TorLatElt,-38,-38,-38,-38,-38
S,IsGorenstein,True iff the cone C has rays contained in one affine hyperplane such that the equation of this hyperplane (which takes unit on each primitive vector of the rays) is integral (i.e. iff the corresponding affine variety is Gorenstein),0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,IsQGorenstein,True iff the cone C has rays contained in one affine hyperplane (i.e. iff the corresponding affine variety is Q-Gorenstein),0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,GorensteinIndex,The Gorenstein index of the affine variety corresponding to the cone C (assuming that it is Q-Gorenstein). Also gives the equation of the hyperplane,0,1,0,0,0,0,0,0,0,TorCon,,148,TorLatElt,-38,-38,-38,-38
S,OuterNormal,"For a Gorenstein cone C (i.e. the primitive generators r_i of the rays of C lie in a common hyperplane), gives an element n in the dual lattice such that n * r_i = 1",0,1,0,0,0,0,0,0,0,TorCon,,TorLatElt,-38,-38,-38,-38,-38
S,InnerNormal,"For a Gorenstein cone C (i.e. the primitive generators r_i of the rays of C lie in a common hyperplane), gives an element n in the dual lattice such that n * r_i = -1",0,1,0,0,0,0,0,0,0,TorCon,,TorLatElt,-38,-38,-38,-38,-38
S,IsIsolated,True iff the singularity of the affine variety associated to cone C is isolated,0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,IsTerminal,True iff the singularity of the affine variety associated to cone C is (at worst) terminal,0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,IsCanonical,True iff the singularity of the affine variety associated to cone C is (at worst) canonical,0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,IsSingular,True iff the affine variety associated to the cone C is singular,0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,IsNonSingular,True iff the affine variety associated to the cone C is nonsingular,0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,IsNonsingular,True iff the affine variety associated to the cone C is nonsingular,0,1,0,0,0,0,0,0,0,TorCon,,36,-38,-38,-38,-38,-38
S,QuotientGenerators,A sequence of generators of the torsion of the ambient lattice of the simplicial toric cone C divided by the sublattice generated by the rays of C; the generators are expressed in the basis given by the rays of C,0,1,0,0,0,0,0,0,0,TorCon,,83,-38,-38,-38,-38,-38
