174,1
A,Map,1,LocalAutoGenerators
A,Map,1,LocalRingMap
S,Continuations,Let m: R -> R be an automorphism of a p-adic ring. Let L be an extension of R. Return the continuations of m to L,0,2,0,0,0,0,0,0,0,395,,0,0,175,,82,-38,-38,-38,-38,-38
S,Automorphisms,Return the automorphisms of the local ring L over K. Automorphisms are returned as a sequence of maps,0,2,0,0,0,0,0,0,0,395,,0,0,395,,82,-38,-38,-38,-38,-38
S,Automorphisms,Return the automorphisms of the local ring L. Automorphisms are returned as a sequence of maps,0,1,0,0,0,0,0,0,0,395,,82,-38,-38,-38,-38,-38
S,Automorphisms,Return the automorphisms of the local ring L. Automorphisms are returned as a sequence of maps,0,2,0,0,0,0,0,0,0,400,,0,0,400,,82,-38,-38,-38,-38,-38
S,Automorphisms,Return the automorphisms of the local ring L. Automorphisms are returned as a sequence of maps,0,1,0,0,0,0,0,0,0,400,,82,-38,-38,-38,-38,-38
S,AutomorphismGroup,Return the automorphism group of L/K as a permutation group,0,2,0,0,0,0,0,0,0,395,,0,0,395,,-27,175,364,-38,-38,-38
S,AutomorphismGroup,Return the automorphism group of L as a permutation group,0,1,0,0,0,0,0,0,0,395,,224,175,364,-38,-38,-38
S,AutomorphismGroup,Return the automorphism group of L over K as a permutation group,0,2,0,0,0,0,0,0,0,400,,0,0,400,,-27,175,364,-38,-38,-38
S,AutomorphismGroup,Return the automorphism group of L as a permutation group,0,1,0,0,0,0,0,0,0,400,,-27,175,364,-38,-38,-38
S,IsNormal,True if L over K is a normal extension,0,2,0,0,0,0,0,0,0,395,,0,0,395,,-1,-38,-38,-38,-38,-38
S,IsNormal,True if L is a normal extension,0,1,0,0,0,0,0,0,0,395,,-1,-38,-38,-38,-38,-38
S,IsNormal,True if L over K is a normal extension,0,2,0,0,0,0,0,0,0,400,,0,0,400,,-1,-38,-38,-38,-38,-38
S,IsNormal,True if L is a normal extension,0,1,0,0,0,0,0,0,0,400,,-1,-38,-38,-38,-38,-38
S,OreConditions,,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,400,,36,-38,-38,-38,-38,-38
S,OreConditions,Return whether R has a totally ramified extension of degree n with discriminant valuation n+j-1,0,3,0,0,0,0,0,0,0,148,,0,0,148,,0,0,395,,36,-38,-38,-38,-38,-38
S,PossibleDiscriminants,Returns a list of possible discriminants of all totally ramified extensions of degree n of R. The discriminants are represented by integers j such that the valuation of the discriminants of the extensions is n+j-1,0,2,0,0,0,0,0,0,0,148,,0,0,395,,148,-38,-38,-38,-38,-38
S,NumberOfExtensions,"The number of extensions of degree n of the local ring R, with given ramification index E, inertia degree F. When F is 1, can also restrict to discriminant valuation vD, and this can also be specified by j with vD=n+j-1. If Galois := true only normal extensions are counted",0,2,0,0,0,0,0,0,0,148,,0,0,395,,148,-38,-38,-38,-38,-38
S,IsIsomorphic,True if the p-adic rings R and S are isomorphic,0,2,0,0,0,0,0,0,0,395,,0,0,395,,36,-38,-38,-38,-38,-38
S,IsIsomorphic,True if the p-adic rings R and S are isomorphic,0,2,0,0,0,0,0,0,0,400,,0,0,400,,36,-38,-38,-38,-38,-38
S,IsIsomorphic,True if the extensions generated by f and g over the common coefficient ring are isomrphic,0,2,0,0,0,0,0,0,0,312,,0,0,312,,36,-38,-38,-38,-38,-38
S,Distance,Distance between two Eisenstein polynomials over a local Ring/Field of the same degree and discriminant,0,2,0,0,0,0,0,0,0,312,,0,0,312,,148,-38,-38,-38,-38,-38
S,AllExtensions,"Returns all extensions (up to isomorphism) of degree n of the p-adic ring R, with given ramification degree E and inertia degree F (zero for arbitrary). When E or F is given, can also restrict to discriminant valuation vD, and in the case where F is 1 this can also be specified by j with vD=n+j-1. If Galois := true only normal extensions are returned",0,2,0,0,0,0,0,0,0,148,,0,0,395,,82,-38,-38,-38,-38,-38
S,AllExtensions,"Returns all extensions of degree n of the p-adic ring R, with given ramification degree E and inertia degree F (zero for arbitrary). When E or F is given, can also restrict to discriminant valuation vD, and in the case where F is 1 this can also be specified by j with vD=n+j-1. If Galois := true only normal extensions are returned",0,2,0,0,0,0,0,0,0,148,,0,0,400,,82,-38,-38,-38,-38,-38
S,Discriminant,,0,2,0,0,0,0,0,0,0,400,,0,0,400,,396,-38,-38,-38,-38,-38
S,Discriminant,Discriminant of the extension S/R,0,2,0,0,0,0,0,0,0,395,,0,0,395,,396,-38,-38,-38,-38,-38
S,Discriminant,Discriminant of R/BaseRing(R),0,1,0,0,0,0,0,0,0,395,,396,-38,-38,-38,-38,-38
S,HasRootOfUnity,Return whether the local ring or field L contains the n-th roots of unity,0,2,0,0,0,0,0,0,0,148,,0,0,395,,36,-38,-38,-38,-38,-38
S,Composite,The composite of R and S. R and S must be normal,0,2,0,0,0,0,0,0,0,395,,0,0,395,,395,-38,-38,-38,-38,-38
S,NormGroup,The norm group of R as a subgroup of the unit group of its base field/ring B; m : UnitGroup(B) -> B,0,2,0,0,0,0,0,0,0,175,,0,0,400,,107,175,-38,-38,-38,-38
S,NormGroup,The norm group of R as a subgroup of the unit group of its base field/ring B; m : UnitGroup(B) -> B,0,2,0,0,0,0,0,0,0,175,,0,0,395,,107,175,-38,-38,-38,-38
S,IsAbelian,True if L over K is an abelian extension,0,2,0,0,0,0,0,0,0,400,,0,0,400,,36,-38,-38,-38,-38,-38
S,NormEquation,"Given the map m : UnitGroup(B) -> B and an element b in B, this solves Norm(a) = b for a in R",0,3,0,0,0,0,0,0,0,-45,,0,0,175,,0,0,400,,36,-45,-38,-38,-38,-38
S,NormEquation,"Given the map m : UnitGroup(B) -> B and an element b in B, this solves Norm(a) = b for a in R",0,3,0,0,0,0,0,0,0,-45,,0,0,175,,0,0,395,,36,-45,-38,-38,-38,-38
S,NormKernel,"m1 : UnitGroup(R1) -> R1, m2 : UnitGroup(R2) -> R2. Return the kernel of the Norm map from UnitGroup(R1) to UnitGroup(R2)",0,2,0,0,0,0,0,0,0,175,,0,0,175,,107,-38,-38,-38,-38,-38
S,Norm,"m1 : UnitGroup(R1) -> R1, m2 : UnitGroup(R2) -> R2, R1 extension of R2, G subgroup of UnitGroup(R1). Returns Norm(G)",0,3,0,0,0,0,0,0,0,107,,0,0,175,,0,0,175,,107,-38,-38,-38,-38,-38
S,NormEquation,"m1 : UnitGroup(R1) -> R1, m2 : UnitGroup(R2) -> R2, R1 extension of R2, G subgroup of UnitGroup(R2). Tries to find a subgroup S of UnitGroup(R1) such that Norm(S,m2) is G",0,3,0,0,0,0,0,0,0,107,,0,0,175,,0,0,175,,107,175,-38,-38,-38,-38
S,NormGroupDiscriminant,The valuation of the discriminant of the class field corresponding to the subgroup G of the unit group of a local ring/field,0,2,0,0,0,0,0,0,0,107,,0,0,175,,148,-38,-38,-38,-38,-38
S,ClassField,"Let K be a p-adic field and U,m:=UnitGroup(K). Let G be a subgroup of U of finite index. Return a list of extensions of K, containing the class fields corresponding to the cyclic factors of U/G",0,2,0,0,0,0,0,0,0,107,,0,0,175,,-1,-38,-38,-38,-38,-38
