174,1
S,IsInertial,Returns true if the polynomial g is inertial,0,1,0,0,0,0,0,0,0,312,,36,-38,-38,-38,-38,-38
S,IsEisenstein,Returns true if the polynomial g is Eisenstein,0,1,0,0,0,0,0,0,0,312,,36,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,400,2,0,0,0,0,0,0,0,148,,0,0,312,,312,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,395,2,0,0,0,0,0,0,0,148,,0,0,312,,312,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,206,2,0,0,0,0,0,0,0,148,,0,0,312,,312,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,388,2,0,0,0,0,0,0,0,148,,0,0,312,,312,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,400,2,0,0,1,0,0,0,0,148,,1,1,312,,-38,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,395,2,0,0,1,0,0,0,0,148,,1,1,312,,-38,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,206,2,0,0,1,0,0,0,0,148,,1,1,312,,-38,-38,-38,-38,-38,-38
S,ShiftValuation,"Returns f * pi^n, where pi is the uniformizing element",1,0,1,312,0,388,2,0,0,1,0,0,0,0,148,,1,1,312,,-38,-38,-38,-38,-38,-38
S,InternalValuationsOfRoots,"Returns the valuations of roots, in increasing order",0,1,0,0,0,0,0,0,0,312,,-1,-38,-38,-38,-38,-38
S,Basis,The basis of the field over its coefficient field,0,1,0,0,0,0,0,0,0,400,,82,-38,-38,-38,-38,-38
S,Basis,The basis of the ring over its coefficient ring,0,1,0,0,0,0,0,0,0,395,,82,-38,-38,-38,-38,-38
S,RelativeBasis,"The k-basis of K, compatible with repeated Eltseq",0,2,0,0,0,0,0,0,0,400,,0,0,400,,82,-38,-38,-38,-38,-38
S,AbsoluteBasis,A Qp basis for K,0,1,0,0,0,0,0,0,0,400,,82,-38,-38,-38,-38,-38
S,NormalBasisGenerator,"For a normal field K, computes a generator for a normal basis as well as the valuation of the index of the Z_p submodule generated by it in the ring of integers",0,1,0,0,0,0,0,0,0,400,,401,148,-38,-38,-38,-38
S,Flat,The coefficients of the element over the prime ring,0,1,0,0,0,0,0,0,0,396,,82,-38,-38,-38,-38,-38
S,Flat,The coefficients of the element over the prime ring,0,1,0,0,0,0,0,0,0,207,,82,-38,-38,-38,-38,-38
S,Flat,The coefficients of the element over the prime ring,0,1,0,0,0,0,0,0,0,389,,82,-38,-38,-38,-38,-38
S,Flat,The coefficients of the element over the prime field,0,1,0,0,0,0,0,0,0,401,,82,-38,-38,-38,-38,-38
S,AbsoluteMinimalPolynomial,The minimal polynomial of x over the prime field,0,1,0,0,0,0,0,0,0,401,,312,-38,-38,-38,-38,-38
S,Generators,Algebra (field) generators over the prime field,0,1,0,0,0,0,0,0,0,400,,82,-38,-38,-38,-38,-38
S,RelativeBasis,An S-basis for R,0,2,0,0,0,0,0,0,0,395,,0,0,395,,82,-38,-38,-38,-38,-38
S,AbsoluteDegree,The degree over the prime field,0,1,0,0,0,0,0,0,0,400,,148,-38,-38,-38,-38,-38
S,IsRamified,Whether the F is a ramified extension of its base field,0,1,0,0,0,0,0,0,0,400,,36,-38,-38,-38,-38,-38
S,IsTotallyRamified,Whether the ramification index of F is equal to the degree of F,0,1,0,0,0,0,0,0,0,400,,36,-38,-38,-38,-38,-38
S,IsUnramified,Whether F is a unramified extension of its base field,0,1,0,0,0,0,0,0,0,400,,36,-38,-38,-38,-38,-38
S,IsTamelyRamified,Whether F is not wildly ramified,0,1,0,0,0,0,0,0,0,400,,36,-38,-38,-38,-38,-38
S,IsWildlyRamified,Whether F is a wildly ramified extension of its base field,0,1,0,0,0,0,0,0,0,400,,36,-38,-38,-38,-38,-38
S,IsRamified,Whether R is a ramified extension of its base field,0,1,0,0,0,0,0,0,0,395,,36,-38,-38,-38,-38,-38
S,IsTotallyRamified,Whether the ramification index of R is equal to the degree of R,0,1,0,0,0,0,0,0,0,395,,36,-38,-38,-38,-38,-38
S,IsUnramified,Whether R is an unramified extension of its base field,0,1,0,0,0,0,0,0,0,395,,36,-38,-38,-38,-38,-38
S,IsTamelyRamified,Whether R is not wildly ramified,0,1,0,0,0,0,0,0,0,395,,36,-38,-38,-38,-38,-38
S,IsWildlyRamified,Whether R is a wildly ramified extension of its base field,0,1,0,0,0,0,0,0,0,395,,36,-38,-38,-38,-38,-38
S,IsRamified,Whether R is a ramified extension of its base field,0,1,0,0,0,0,0,0,0,206,,36,-38,-38,-38,-38,-38
S,IsTotallyRamified,Whether the ramification index of R is equal to the degree of R,0,1,0,0,0,0,0,0,0,206,,36,-38,-38,-38,-38,-38
S,IsUnramified,Whether R is an unramified extension of its base field,0,1,0,0,0,0,0,0,0,206,,36,-38,-38,-38,-38,-38
S,IsTamelyRamified,Whether R is not wildly ramified,0,1,0,0,0,0,0,0,0,206,,36,-38,-38,-38,-38,-38
S,IsWildlyRamified,Whether R is a wildly ramified extension of its base field,0,1,0,0,0,0,0,0,0,206,,36,-38,-38,-38,-38,-38
S,IsRamified,Whether R is a ramified extension of its base field,0,1,0,0,0,0,0,0,0,388,,36,-38,-38,-38,-38,-38
S,IsTotallyRamified,Whether the ramification index of R is equal to the degree of R,0,1,0,0,0,0,0,0,0,388,,36,-38,-38,-38,-38,-38
S,IsUnramified,Whether R is an unramified extension of its base field,0,1,0,0,0,0,0,0,0,388,,36,-38,-38,-38,-38,-38
S,IsTamelyRamified,Whether R is not wildly ramified,0,1,0,0,0,0,0,0,0,388,,36,-38,-38,-38,-38,-38
S,IsWildlyRamified,Whether R is a wildly ramified extension of its base field,0,1,0,0,0,0,0,0,0,388,,36,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The Frobenius of R,0,1,0,0,0,0,0,0,0,395,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The Frobenius of R,0,1,0,0,0,0,0,0,0,400,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The Frobenius of R,0,1,0,0,0,0,0,0,0,206,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The Frobenius of R,0,1,0,0,0,0,0,0,0,388,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The Frobenius of R,0,1,0,0,0,0,0,0,0,395,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The Frobenius of R,0,1,0,0,0,0,0,0,0,400,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The Frobenius of R,0,1,0,0,0,0,0,0,0,206,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The Frobenius of R,0,1,0,0,0,0,0,0,0,388,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,395,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,400,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,206,,175,-38,-38,-38,-38,-38
S,FrobeniusAutomorphism,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,388,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,395,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,400,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,206,,175,-38,-38,-38,-38,-38
S,FrobeniusMap,The i-th power of the Frobenius of R,0,2,0,0,0,0,0,0,0,148,,0,0,388,,175,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the Frobenius,0,1,0,0,0,0,0,0,0,396,,396,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the Frobenius,0,1,0,0,0,0,0,0,0,401,,401,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the Frobenius,0,1,0,0,0,0,0,0,0,207,,207,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the Frobenius,0,1,0,0,0,0,0,0,0,389,,389,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the i-th power of the Frobenius,0,2,0,0,0,0,0,0,0,148,,0,0,396,,396,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the i-th power of the Frobenius,0,2,0,0,0,0,0,0,0,148,,0,0,401,,401,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the i-th power of the Frobenius,0,2,0,0,0,0,0,0,0,148,,0,0,207,,207,-38,-38,-38,-38,-38
S,FrobeniusImage,The image of x under the i-th power of the Frobenius,0,2,0,0,0,0,0,0,0,148,,0,0,389,,389,-38,-38,-38,-38,-38
S,VerschiebungMap,The Verschiebungs map for R unramified,0,1,0,0,0,0,0,0,0,395,,175,-38,-38,-38,-38,-38
S,VerschiebungMap,The Verschiebungs map for R unramified,0,1,0,0,0,0,0,0,0,400,,175,-38,-38,-38,-38,-38
S,VerschiebungMap,The Verschiebungs map for R unramified,0,1,0,0,0,0,0,0,0,206,,175,-38,-38,-38,-38,-38
S,VerschiebungMap,The Verschiebungs map for R unramified,0,1,0,0,0,0,0,0,0,388,,175,-38,-38,-38,-38,-38
S,VerschiebungImage,The image of x under the Verschiebung map,0,1,0,0,0,0,0,0,0,396,,396,-38,-38,-38,-38,-38
S,VerschiebungImage,The image of x under the Verschiebung map,0,1,0,0,0,0,0,0,0,401,,401,-38,-38,-38,-38,-38
S,VerschiebungImage,The image of x under the Verschiebung map,0,1,0,0,0,0,0,0,0,207,,207,-38,-38,-38,-38,-38
S,VerschiebungImage,The image of x under the Verschiebung map,0,1,0,0,0,0,0,0,0,389,,389,-38,-38,-38,-38,-38
S,SetPrecision,Sets the precision of K to n and ensures that the precision of the coefficient ring is adjusted as well,0,2,0,0,1,0,0,0,0,148,,0,0,400,,-38,-38,-38,-38,-38,-38
S,SetPrecision,Sets the precision of K to n and ensures that the precision of the coefficient ring is adjusted as well,0,2,0,0,1,0,0,0,0,148,,0,0,395,,-38,-38,-38,-38,-38,-38
S,Gamma,Compute the p-adic Gamma function,0,1,0,0,0,0,0,0,0,401,,401,-38,-38,-38,-38,-38
S,Gamma,Compute the p-adic Gamma function,0,1,0,0,0,0,0,0,0,396,,396,-38,-38,-38,-38,-38
