174,1
T,GrpDrch,GrpDrchElt,0
A,GrpDrch,22,BaseRing,RootOf1,PowersOfRoot,OrderOfRoot,Modulus,Exponent,UGroup,UnitsMap,Elements,OrdersUGroup,OrdersGens,Images,Labels,AbGrp,AbGrpMap,EltArray,NF,Pairing,Residue_map,Zeta,DecompositionParents,ValsAtMinus1
T,GrpDrchElt,-,0
A,GrpDrchElt,7,Parent,BaseRing,Modulus,Conductor,Element,ValueList,GaussSum
S,TorsionUnitGroup,The m-torsion subgroup of the unit group of the ring R,0,2,0,0,0,0,0,0,0,148,,0,0,319,,107,175,-38,-38,-38,-38
S,TorsionUnitGroup,The m-torsion subgroup of the unit group of the ring R,0,2,0,0,0,0,0,0,0,148,,0,0,262,,107,175,-38,-38,-38,-38
S,TorsionUnitGroup,The m-torsion subgroup of the unit group of the ring R,0,2,0,0,0,0,0,0,0,148,,0,0,215,,107,175,-38,-38,-38,-38
S,TorsionUnitGroup,The m-torsion subgroup of the unit group of the ring R,0,2,0,0,0,0,0,0,0,148,,0,0,-9,,107,175,-38,-38,-38,-38
S,ValueList,"[The values [eps(1), eps(2), ..., eps(N)], where N is the modulus",0,1,0,0,0,0,0,0,0,GrpDrchElt,,82,-38,-38,-38,-38,-38
S,DirichletGroup,The group of Dirichlet characters mod m with image in RationalField(). This is a group of exponent at most 2,0,1,0,0,0,0,0,0,0,148,,GrpDrch,-38,-38,-38,-38,-38
S,DirichletGroup,The group of Dirichlet characters mod m with image in the ring R,0,2,0,0,0,0,0,0,0,-44,,0,0,148,,GrpDrch,-38,-38,-38,-38,-38
S,DirichletGroup,The group of Dirichlet characters mod m with image in the order-r cyclic subgroup of R generated by the root of unity z,0,4,0,0,0,0,0,0,0,148,,0,0,-45,,0,0,-44,,0,0,148,,GrpDrch,-38,-38,-38,-38,-38
S,DirichletGroupCopy,Clone G,0,1,0,0,0,0,0,0,0,GrpDrch,,GrpDrch,-38,-38,-38,-38,-38
S,DirichletGroupFull,Same as FullDirichletGroup,0,1,0,0,0,0,0,0,0,148,,GrpDrch,-38,-38,-38,-38,-38
S,FullDirichletGroup,"The group of Dirichlet characters modulo N with values in Q(zeta_m), where m is the exponent of (Z/N)^*",0,1,0,0,0,0,0,0,0,148,,GrpDrch,-38,-38,-38,-38,-38
S,AbelianGroup,"An abstract abelian group A isomorphic to G, and a map A -> G",0,1,0,0,0,0,0,0,0,GrpDrch,,107,175,-38,-38,-38,-38
S,Elements,The Dirichlet characters in G,0,1,0,0,0,0,0,0,0,GrpDrch,,82,-38,-38,-38,-38,-38
S,Random,A random element of G,0,1,0,0,0,0,0,0,0,GrpDrch,,GrpDrchElt,-38,-38,-38,-38,-38
S,IsCoercible,,0,2,0,0,0,0,0,0,0,-1,,0,0,GrpDrch,,36,GrpDrchElt,-38,-38,-38,-38
S,NumberOfNames,,0,1,0,0,0,0,0,0,0,GrpDrch,,148,-38,-38,-38,-38,-38
S,AssignNames,Assign names to the generators of G,1,1,1,82,0,298,2,0,0,1,0,0,0,0,82,,1,1,GrpDrch,,-38,-38,-38,-38,-38,-38
S,Name,The ith generator,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrch,,GrpDrchElt,-38,-38,-38,-38,-38
S,.,The ith generator,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrch,,GrpDrchElt,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,GrpDrch,,-38,-38,-38,-38,-38,-38
S,Print,,0,2,0,0,1,0,0,0,0,298,,0,0,GrpDrchElt,,-38,-38,-38,-38,-38,-38
S,in,Returns true if x is in X,0,2,0,0,0,0,0,0,0,GrpDrch,,0,0,-1,,36,-38,-38,-38,-38,-38
S,Parent,,0,1,0,0,0,0,0,0,0,GrpDrchElt,,GrpDrch,-38,-38,-38,-38,-38
S,eq,True iff the given groups of Dirichlet characters are functionally the same,0,2,0,0,0,0,0,0,0,GrpDrch,,0,0,GrpDrch,,36,-38,-38,-38,-38,-38
S,eq,True iff the given Dirichlet characters have the same modulus and values,0,2,0,0,0,0,0,0,0,GrpDrchElt,,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,BaseRing,The base ring of G,0,1,0,0,0,0,0,0,0,GrpDrch,,-44,-38,-38,-38,-38,-38
S,BaseRing,"The base ring, i.e. the codomain, of x",0,1,0,0,0,0,0,0,0,GrpDrchElt,,-44,-38,-38,-38,-38,-38
S,Domain,The integers,0,1,0,0,0,0,0,0,0,GrpDrchElt,,-44,-38,-38,-38,-38,-38
S,Codomain,The coefficient ring in which x takes values,0,1,0,0,0,0,0,0,0,GrpDrchElt,,-44,-38,-38,-38,-38,-38
S,Exponent,The exponent of G,0,1,0,0,0,0,0,0,0,GrpDrch,,148,-38,-38,-38,-38,-38
S,Order,The order of G,0,1,0,0,0,0,0,0,0,GrpDrch,,148,-38,-38,-38,-38,-38
S,#,The order of G,0,1,0,0,0,0,0,0,0,GrpDrch,,148,-38,-38,-38,-38,-38
S,Order,The order of x,0,1,0,0,0,0,0,0,0,GrpDrchElt,,148,-38,-38,-38,-38,-38
S,Generators,A sequence containing the generators for G,0,1,0,0,0,0,0,0,0,GrpDrch,,82,-38,-38,-38,-38,-38
S,GeneratorsSequence,A sequence containing the generators for G,0,1,0,0,0,0,0,0,0,GrpDrch,,82,-38,-38,-38,-38,-38
S,UnitGenerators,"The ordered sequence of integers that reduce to ""canonical"" generators of (Z/m)^*, where m is the modulus of G",0,1,0,0,0,0,0,0,0,GrpDrch,,82,-38,-38,-38,-38,-38
S,NumberOfGenerators,The number of generators for G,0,1,0,0,0,0,0,0,0,GrpDrch,,148,-38,-38,-38,-38,-38
S,Modulus,The modulus of the group G of Dirichlet characters,0,1,0,0,0,0,0,0,0,GrpDrch,,148,-38,-38,-38,-38,-38
S,Modulus,The modulus of the Dirichlet character x,0,1,0,0,0,0,0,0,0,GrpDrchElt,,148,-38,-38,-38,-38,-38
S,Conductor,The conductor of the Dirichlet character x,0,1,0,0,0,0,0,0,0,GrpDrchElt,,148,-38,-38,-38,-38,-38
S,IsIdentity,True iff chi is the trivial character,0,1,0,0,0,0,0,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,IsTrivial,True iff chi is the trivial character,0,1,0,0,0,0,0,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,IsEven,True iff the Dirichlet character chi satisfies chi(-1) = 1,0,1,0,0,0,0,0,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,IsOdd,True iff the Dirichlet character chi satisfies chi(-1) = -1,0,1,0,0,0,0,0,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,IsTotallyEven,"For a Dirichlet character chi, this is true iff every character in Decomposition(chi) is even",0,1,0,0,0,0,0,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,IsPrimitive,True iff the conductor equals the modulus,0,1,0,0,0,0,0,0,0,GrpDrchElt,,36,-38,-38,-38,-38,-38
S,AssociatedPrimitiveCharacter,The corresponding character on Z/N where N is the conductor of x,0,1,0,0,0,0,0,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,Evaluate,The evaluation of x at n,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrchElt,,-45,-38,-38,-38,-38,-38
S,Evaluate,Evaluation x(n),0,2,0,0,0,0,0,0,0,321,,0,0,GrpDrchElt,,-45,-38,-38,-38,-38,-38
S,@,Evaluation x(n),0,2,0,0,0,0,0,0,0,GrpDrchElt,,0,0,148,,-45,-38,-38,-38,-38,-38
S,@,Evaluation x(n),0,2,0,0,0,0,0,0,0,GrpDrchElt,,0,0,321,,-45,-38,-38,-38,-38,-38
S,*,"The product of x and y. This is a Dirichlet character of modulus equal to the least common multiple of the moduli of x and y. If the parents of x and y are not equal, then the product lies in a new Dirichlet group. If the base rings or roots are not equal then the base ring has to be cyclotomic",0,2,0,0,0,0,0,0,0,GrpDrchElt,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,/,The quotient of x and y. This is a Dirichlet character of modulus equal to the least common multiple of the moduli of x and y. The base rings and chosen roots of unity of the parents of x and y must be equal,0,2,0,0,0,0,0,0,0,GrpDrchElt,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,^,The n-th power of the Dirichlet character x,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,Extend,Extension of x to a Dirichlet character mod m,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,Extend,Extension of x to an element of H,0,2,0,0,0,0,0,0,0,GrpDrch,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,Eltseq,For internal use,0,1,0,0,0,0,0,0,0,GrpDrchElt,,82,-38,-38,-38,-38,-38
S,Decomposition,Decomposition of x as a product of Dirichlet characters of prime power modulus,0,1,0,0,0,0,0,0,0,GrpDrchElt,,168,-38,-38,-38,-38,-38
S,Restrict,The associated mod-m Dirichlet character. The conductor of x must divide m,0,2,0,0,0,0,0,0,0,148,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,Restrict,The associated Dirichlet character in H,0,2,0,0,0,0,0,0,0,GrpDrch,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,BaseExtend,Base extension of G to R,0,2,0,0,0,0,0,0,0,-44,,0,0,GrpDrch,,GrpDrch,-38,-38,-38,-38,-38
S,BaseExtend,Base extension of G to R that identifies the distinguished root of unity of the base ring of G with z,0,3,0,0,0,0,0,0,0,-45,,0,0,-44,,0,0,GrpDrch,,GrpDrch,-38,-38,-38,-38,-38
S,BaseExtend,Base extension of eps to R,0,2,0,0,0,0,0,0,0,-44,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,BaseExtend,Base extension of eps to R,0,3,0,0,0,0,0,0,0,-45,,0,0,-44,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,BaseExtend,Base extension of G to Codomain(f),0,2,0,0,0,0,0,0,0,175,,0,0,GrpDrch,,GrpDrch,-38,-38,-38,-38,-38
S,BaseExtend,Base extension of eps to Codomain(R),0,2,0,0,0,0,0,0,0,175,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,DistinguishedRoot,The distinguished root of unity in the base ring of G and its order,0,1,0,0,0,0,0,0,0,GrpDrch,,-45,148,-38,-38,-38,-38
S,KroneckerCharacter,"The Kronecker character (D'/n), where D' is the fundamental discriminant associated to D",0,1,0,0,0,0,0,0,0,148,,GrpDrchElt,-38,-38,-38,-38,-38
S,KroneckerCharacter,"The Kronecker character (D'/n), where D' is the fundamental discriminant associated to D",0,2,0,0,0,0,0,0,0,-44,,0,0,148,,GrpDrchElt,-38,-38,-38,-38,-38
S,GaloisConjugacyRepresentatives,Representatives for the Gal(Qbar/Q)-conjugacy classes of G,0,1,0,0,0,0,0,0,0,GrpDrch,,82,-38,-38,-38,-38,-38
S,GaloisConjugacyRepresentatives,Representatives for the Gal(Qbar/Q)-conjugacy classes of Dirichlet characters contained in the given sequence S,1,0,1,82,0,GrpDrchElt,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,MinimalBaseRingCharacter,"Return an equivalent character, but defined over a base ring that is generated by the values",0,1,0,0,0,0,0,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,ValuesOnUnitGenerators,"The values of x on the ordered sequence generators of (Z/m)^*, where m is the modulus of x",0,1,0,0,0,0,0,0,0,GrpDrchElt,,82,-38,-38,-38,-38,-38
S,DirichletCharacterFromValuesOnUnitGenerators,Creates a Dirichlet character belonging to G whose values on the chosen generators of (Z/m)^* match the given sequence v,0,2,0,0,0,0,0,0,0,82,,0,0,GrpDrch,,GrpDrchElt,-38,-38,-38,-38,-38
S,ApplyAutomorphism,Same as x^phi,0,2,0,0,0,0,0,0,0,-1,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,^,The image of the Dirichlet character x under the automorphism phi,0,2,0,0,0,0,0,0,0,-1,,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
S,OrderOfRootOfUnity,"Given an element r of some ring, assumed to satisfy r^n = 1, this returns the smallest integer m such that r^m = 1",0,2,0,0,0,0,0,0,0,148,,0,0,-45,,148,-38,-38,-38,-38,-38
S,Sqrt,"A square root of eps, where eps is a Dirichlet character of odd order",0,1,0,0,0,0,0,0,0,GrpDrchElt,,GrpDrchElt,-38,-38,-38,-38,-38
