174,1
S,Representation,The vector corresponding to x in the underlying vector space corresponding to the parent of x,0,1,0,0,0,0,0,0,0,ModSymElt,,160,-38,-38,-38,-38,-38
S,Representation,"The vector space V underlying M, the map V --> M, and the map M --> V",0,1,0,0,0,0,0,0,0,ModSym,,159,175,175,-38,-38,-38
S,VectorSpace,"The vector space V underlying M, the map V --> M, and the map M --> V",0,1,0,0,0,0,0,0,0,ModSym,,159,175,175,-38,-38,-38
S,DualRepresentation,Same as DualVectorSpace,0,1,0,0,0,0,0,0,0,ModSym,,159,175,175,-38,-38,-38
S,DualVectorSpace,The subspace of the dual space of VectorSpace(AmbientSpace(M)) that is isomorphic to M as module of the Hecke algebra,0,1,0,0,0,0,0,0,0,ModSym,,159,-38,-38,-38,-38,-38
S,Lattice,"A basis over the integers for the integral modular symbols in the VectorSpace(M). This is the intersection of M with the Z-lattice generated by all modular symbols X^iY^(k-2-i){a,b}. The base field of M must be RationalField()",0,1,0,0,0,0,0,0,0,ModSym,,164,175,-38,-38,-38,-38
S,IntegralRepresentation,"A basis over the integers for the integral modular symbols in the vector space representation of M. This is the intersection of M with the Z-lattice generated by all modular symbols X^iY^(k-2-i){a,b}. If the base field is a number field not equal to Q, then we view M as a Q-vector space using restriction of scalars, and return a lattice and set-theoretic map from the lattice to M",0,1,0,0,0,0,0,0,0,ModSym,,164,-38,-38,-38,-38,-38
S,DualLattice,A basis over the integers for the integral modular symbols in the DualVectorSpace(M). The base field of M must be RationalField(),0,1,0,0,0,0,0,0,0,ModSym,,164,175,-38,-38,-38,-38
