174,1
S,ZeroSubspace,The zero subspace of M,0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,CuspidalSubspace,The cuspidal subspace of M. This is the kernel of BoundaryMap(M),0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,EisensteinSubspace,The Eisenstein subspace of M. The is the complement in M of the cuspidal subspace of M,0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,-,A synonym for Complement(M),0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,BasisPlus,Basis for the +1 eigenspace of StarInvolution on M,0,1,0,0,0,0,0,0,0,ModSym,,82,-38,-38,-38,-38,-38
S,BasisMinus,Basis for the -1 eigenspace of StarInvolution on M,0,1,0,0,0,0,0,0,0,ModSym,,82,-38,-38,-38,-38,-38
S,IntegralBasisPlus,Integral basis for the +1 eigenspace of StarInvolution on M,0,1,0,0,0,0,0,0,0,ModSym,,82,-38,-38,-38,-38,-38
S,IntegralBasisMinus,Integral basis for the -1 eigenspace of StarInvolution on M,0,1,0,0,0,0,0,0,0,ModSym,,82,-38,-38,-38,-38,-38
S,NewSubspace,"The p-new subspace of M. This is the complement in M of the subspace generated by the modular symbols of level equal to the level of M divided by p and character the restriction of the character of M. If the character of M does not restrict, then NewSubspace(M,p) is equal to M. Note that M is required to be cuspidal",0,2,0,0,0,0,0,0,0,148,,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,NewSubspace,"The new subspace of the cuspidal modular symbols space M. This is the intersection of NewSubspace(M,p) as p varies over all prime divisors of the level of M",0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,Complement,The space of modular symbols complementary to M in AmbientSpace(M). Thus the ambient space of M is equal to the direct sum of M and Complement(M),0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,OldSubspace,The old subspace of M. This is simply the complement in M of NewSubspace(M). Note that M is required to be cuspidal,0,1,0,0,0,0,0,0,0,ModSym,,ModSym,-38,-38,-38,-38,-38
S,Projection,The (Hecke-invariant) projection from the ambient space of M onto M,0,1,0,0,0,0,0,0,0,ModSym,,175,-38,-38,-38,-38,-38
S,ProjectionMap,The (Hecke-invariant) projection from the ambient space of M onto M,0,1,0,0,0,0,0,0,0,ModSym,,175,-38,-38,-38,-38,-38
S,ProjectionMatrix,The (Hecke-invariant) projection from the ambient space of M onto M,0,1,0,0,0,0,0,0,0,ModSym,,177,-38,-38,-38,-38,-38
