174,1
A,GaloisData,5,IsInt,GetPrec,RecoData,BaseMap,CycleTypes
V,GaloisTower,3
S,GaloisGroup,The Galois group of a number field represented as a simple relative extension,1,0,1,27,1,27,0,262,1,0,0,0,0,0,0,0,27,,224,82,GaloisData,-38,-38,-38
S,GaloisData,The data structure for the Galois group computation for a number field represented as a simple relative extension,1,0,1,27,1,27,0,262,1,0,0,0,0,0,0,0,27,,GaloisData,-38,-38,-38,-38,-38
S,GaloisGroup,The Galois group of a number field represented as a multiple relative extension,0,1,0,0,0,0,0,0,0,27,,224,82,GaloisData,-38,-38,-38
S,InternalGaloisDataCreate,,0,1,0,0,0,0,0,0,0,217,,GaloisData,-38,-38,-38,-38,-38
S,ConjugatesToPowerSums,"Given elements in c, compute the power sums, ie. &+ [x^j : x in c]",0,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,ElementarySymmetricToPowerSums,"Given the elementary symmetric functions, compute the power sums",0,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,PolynomialToElementarySymmetric,"Given a polynomial, return the sequence of the elementatry symmetric functions",0,1,0,0,0,0,0,0,0,312,,82,-38,-38,-38,-38,-38
S,PolynomialToPowerSums,"Given a polynomial, return the sequence of power sums of the roots",0,1,0,0,0,0,0,0,0,312,,82,-38,-38,-38,-38,-38
S,PowerSumToCoefficients,"Given power sums in c, use Newton's relations to obtain the coefficients of the corresponding polynomial",0,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,CoefficientsToElementarySymmetric,"Given an array of coefficients of a monic polynomial, transform into the array of elementary symmetric polynomials",1,0,1,82,0,-45,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,ElementarySymmetricToCoefficients,"Given an array containing the elementary symmetric polynomials evaluated at the roots, return the coefficients array",1,0,1,82,0,-45,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,PowerSumToElementarySymmetric,"Given an array containing power sums, use Newton relations to compute the elementary symmetric polynomials",1,0,1,82,0,-45,1,0,0,0,0,0,0,0,82,,82,-38,-38,-38,-38,-38
S,&*,,0,1,0,0,0,0,0,0,0,303,,-1,-38,-38,-38,-38,-38
S,Norm,For compatibility,0,2,0,0,0,0,0,0,0,319,,0,0,148,,148,-38,-38,-38,-38,-38
S,Norm,For compatibility,0,2,0,0,0,0,0,0,0,319,,0,0,267,,148,-38,-38,-38,-38,-38
S,Conjugates,For compatibility,1,0,1,-10,0,-9,1,0,0,0,0,0,0,0,-10,,82,-38,-38,-38,-38,-38
S,GaloisSubfieldTower,"Given a descending chain if subgroups of the Galois group G, return the corresponding tower of fields",1,1,1,82,0,224,2,0,0,0,0,0,0,0,82,,0,0,GaloisData,,-9,82,41,41,-38,-38
S,GaloisSplittingField,Computes a splitting field for f (as a tower) and returns the roots in it,1,0,1,312,0,262,1,0,0,0,0,0,0,0,312,,27,82,224,-38,-38,-38
S,GaloisSplittingField,Computes a splitting field for f (as a tower) and returns the roots in it,1,0,1,312,0,319,1,0,0,0,0,0,0,0,312,,27,82,224,-38,-38,-38
S,CyclicToRadical,"For K being a cyclic extension which automorphism group generated by the map sending K.1 to Aut and Zeta a root of unity of Degree(K), find a Kummer generator for K",0,3,0,0,0,0,0,0,0,-45,,0,0,28,,0,0,27,,27,-38,-38,-38,-38,-38
S,SolveByRadicals,Compute a splitting field as a radical tower and the roots of f as elements in this tower. Return also the non-trivial roots of unity used,1,0,1,312,0,319,1,0,0,0,0,0,0,0,312,,27,82,82,-38,-38,-38
S,SolveByRadicals,Compute a splitting field as a radical tower and the roots of f as elements in this tower. Return also the non-trivial roots of unity used,1,0,1,312,0,262,1,0,0,0,0,0,0,0,312,,27,82,82,-38,-38,-38
